# Generated by Django 5.1.15 on 2026-08-20 15:30

import django.db.models.deletion
import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BarcodeLabelTemplate',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Template Name')),
                ('width_mm', models.PositiveIntegerField(default=50, help_text='Width in millimeters')),
                ('height_mm', models.PositiveIntegerField(default=25, help_text='Height in millimeters')),
                ('show_shop_name', models.BooleanField(default=True)),
                ('show_mrp', models.BooleanField(default=True)),
                ('show_product_code', models.BooleanField(default=True)),
                ('show_estimate_tag', models.BooleanField(default=True, help_text="Prints non-IRD disclaimer or 'EST' badge on barcode sticker")),
                ('custom_note', models.CharField(blank=True, default='Incl. All Taxes', max_length=50, null=True)),
            ],
            options={
                'verbose_name': 'Barcode Label Template',
                'verbose_name_plural': 'Barcode Label Templates',
                'db_table': 'prod_barcode_templates',
            },
        ),
        migrations.CreateModel(
            name='ProductPriceTier',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('tier_type', models.CharField(choices=[('RETAIL', 'Standard Retail (खुद्रा मूल्य)'), ('WHOLESALE', 'Wholesale Rate (थोक मूल्य)'), ('DEALER', 'Dealer / Bulk Rate'), ('SPECIAL', 'Special VIP Rate')], db_index=True, max_length=20)),
                ('min_quantity', models.DecimalField(decimal_places=3, default=Decimal('1.000'), help_text='Minimum base units required to qualify for this rate', max_digits=10)),
                ('price_per_unit', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Price (NPR)')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='price_tiers', to='inventory.product')),
            ],
            options={
                'verbose_name': 'Product Price Tier',
                'verbose_name_plural': 'Product Price Tiers',
                'db_table': 'prod_price_tiers',
                'ordering': ['product', 'min_quantity'],
                'unique_together': {('product', 'tier_type', 'min_quantity')},
            },
        ),
    ]
