# Generated by Django 5.1.15 on 2026-08-22 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='barcodelabeltemplate',
            name='show_model_number',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='barcodelabeltemplate',
            name='show_variant_info',
            field=models.BooleanField(default=True, help_text='Print RAM/Storage & Color variant on sticker'),
        ),
        migrations.AddField(
            model_name='barcodelabeltemplate',
            name='show_warranty_badge',
            field=models.BooleanField(default=True, help_text='Print e.g. 1 Year Warranty on label'),
        ),
        migrations.AlterField(
            model_name='barcodelabeltemplate',
            name='show_estimate_tag',
            field=models.BooleanField(default=True, help_text="Prints 'EST' or 'Proforma' badge on barcode sticker"),
        ),
    ]
