# Generated by Django 5.1.15 on 2026-09-17 14:09

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0015_product_is_discountable'),
        ('products', '0002_barcodelabeltemplate_show_model_number_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalProduct',
            fields=[
            ],
            options={
                'verbose_name': 'Historical Migration Placeholder Product',
                'verbose_name_plural': 'Historical Migration Placeholder Products',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('inventory.product',),
        ),
        migrations.AlterField(
            model_name='barcodelabeltemplate',
            name='custom_note',
            field=models.CharField(blank=True, default='Incl. All Taxes', max_length=50, null=True, verbose_name='Custom Sticker Footer Note'),
        ),
        migrations.AlterField(
            model_name='barcodelabeltemplate',
            name='show_estimate_tag',
            field=models.BooleanField(default=True, help_text="Prints 'EST' or 'Proforma' badge on barcode sticker", verbose_name='Print Estimation / Proforma Badge'),
        ),
        migrations.AlterField(
            model_name='barcodelabeltemplate',
            name='show_model_number',
            field=models.BooleanField(default=True, verbose_name='Print Model Number'),
        ),
        migrations.AlterField(
            model_name='barcodelabeltemplate',
            name='show_mrp',
            field=models.BooleanField(default=True, verbose_name='Print Selling Price / MRP'),
        ),
        migrations.AlterField(
            model_name='barcodelabeltemplate',
            name='show_product_code',
            field=models.BooleanField(default=True, verbose_name='Print Product SKU Code'),
        ),
        migrations.AlterField(
            model_name='barcodelabeltemplate',
            name='show_shop_name',
            field=models.BooleanField(default=True, verbose_name='Print Shop Business Name'),
        ),
        migrations.AlterField(
            model_name='barcodelabeltemplate',
            name='show_variant_info',
            field=models.BooleanField(default=True, help_text='Print RAM/Storage & Color variant on sticker', verbose_name='Print Variant Info'),
        ),
        migrations.AlterField(
            model_name='barcodelabeltemplate',
            name='show_warranty_badge',
            field=models.BooleanField(default=True, help_text='Print e.g. 1 Year Warranty on label', verbose_name='Print Warranty Badge'),
        ),
        migrations.AlterField(
            model_name='productpricetier',
            name='min_quantity',
            field=models.DecimalField(decimal_places=3, default=Decimal('1.000'), help_text='Minimum base units required to qualify for this rate', max_digits=10, verbose_name='Minimum Quantity Qualifying Threshold'),
        ),
        migrations.AlterField(
            model_name='productpricetier',
            name='price_per_unit',
            field=models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Price per Base Unit (NPR)'),
        ),
        migrations.AlterField(
            model_name='productpricetier',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='price_tiers', to='inventory.product', verbose_name='Catalog Product'),
        ),
        migrations.AlterField(
            model_name='productpricetier',
            name='tier_type',
            field=models.CharField(choices=[('RETAIL', 'Standard Retail (खुद्रा मूल्य)'), ('WHOLESALE', 'Wholesale Rate (थोक मूल्य)'), ('DEALER', 'Dealer / Bulk Rate'), ('SPECIAL', 'Special VIP Rate')], db_index=True, max_length=20, verbose_name='Customer Tier Type'),
        ),
    ]
