# Generated by Django 5.1.15 on 2026-10-03 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0017_productbatch_expiry_date_and_more'),
        ('products', '0003_historicalproduct_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productpricetier',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True, help_text='Designates whether this price tier rule is active and available for billing.', verbose_name='Is Active'),
        ),
        migrations.AddIndex(
            model_name='productpricetier',
            index=models.Index(fields=['product', 'tier_type', 'is_active'], name='idx_tier_prod_type_active'),
        ),
    ]
