# Generated by Django 5.1.15 on 2026-08-20 15:30

import django.db.models.deletion
import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('branches', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SalesEstimateItem',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('quantity', models.DecimalField(decimal_places=3, default=Decimal('1.000'), max_digits=10)),
                ('conversion_factor', models.DecimalField(decimal_places=3, default=Decimal('1.000'), max_digits=10)),
                ('base_unit_quantity', models.DecimalField(decimal_places=3, max_digits=12)),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Unit Price (NPR)')),
                ('cost_price', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('discount_percent', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5)),
                ('discount_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('is_vat_applicable', models.BooleanField(default=True)),
                ('vat_rate', models.DecimalField(decimal_places=2, default=Decimal('13.00'), max_digits=5)),
                ('taxable_line_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('tax_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('line_total', models.DecimalField(decimal_places=2, max_digits=14)),
                ('imei_number', models.CharField(blank=True, max_length=35, null=True)),
                ('warranty_expiry_date', models.DateField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Sales Estimate Item',
                'verbose_name_plural': 'Sales Estimate Items',
                'db_table': 'pos_sales_estimate_items',
            },
        ),
        migrations.CreateModel(
            name='SalesPaymentTransaction',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('payment_mode', models.CharField(choices=[('CASH', 'Cash (नगद)'), ('ESEWA', 'eSewa (ईसेवा)'), ('KHALTI', 'Khalti (खल्ती)'), ('FONEPAY', 'FonePay QR (फोनपे)'), ('CARD', 'POS Card Swipe (कार्ड)'), ('BANK_TRANSFER', 'Bank Transfer / ConnectIPS'), ('CREDIT', 'Udhaari / Account Balance (उधारो)')], db_index=True, max_length=30)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('transaction_ref', models.CharField(blank=True, help_text='QR / Bank / Card Auth Reference', max_length=100, null=True)),
                ('notes', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'verbose_name': 'Payment Transaction',
                'verbose_name_plural': 'Payment Transactions',
                'db_table': 'pos_payment_transactions',
            },
        ),
        migrations.CreateModel(
            name='SalesReturn',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('return_number', models.CharField(db_index=True, max_length=50, unique=True)),
                ('total_refund_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('refund_mode', models.CharField(choices=[('CASH', 'Cash Refund'), ('STORE_CREDIT', 'Customer Store Credit'), ('EXCHANGE_ADJUST', 'Adjusted in Exchange Bill')], default='CASH', max_length=30)),
                ('reason', models.TextField(verbose_name='Reason for Return')),
            ],
            options={
                'verbose_name': 'Sales Return',
                'verbose_name_plural': 'Sales Returns',
                'db_table': 'pos_sales_returns',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SalesReturnItem',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('return_quantity', models.DecimalField(decimal_places=3, max_digits=10)),
                ('base_unit_quantity', models.DecimalField(decimal_places=3, max_digits=12)),
                ('refund_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('restock_to_inventory', models.BooleanField(default=True, help_text='Re-add returned item back to active branch stock')),
                ('is_defective', models.BooleanField(default=False, help_text='Mark item as defective/damaged for supplier return')),
            ],
            options={
                'verbose_name': 'Sales Return Item',
                'verbose_name_plural': 'Sales Return Items',
                'db_table': 'pos_sales_return_items',
            },
        ),
        migrations.CreateModel(
            name='SalesEstimate',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('estimate_number', models.CharField(db_index=True, max_length=50, unique=True, verbose_name='Estimate Slip No.')),
                ('customer_name_manual', models.CharField(blank=True, max_length=200, null=True, verbose_name='Walk-in Customer Name')),
                ('customer_phone_manual', models.CharField(blank=True, max_length=25, null=True, verbose_name='Walk-in Phone')),
                ('customer_pan', models.CharField(blank=True, max_length=15, null=True, verbose_name='Customer PAN (Optional)')),
                ('bill_date_ad', models.DateField(auto_now_add=True, db_index=True)),
                ('bill_date_bs', models.CharField(blank=True, max_length=15, null=True, verbose_name='Bill Date (BS)')),
                ('subtotal', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('item_discount_total', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('bill_discount_percent', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5)),
                ('bill_discount_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('is_vat_applicable', models.BooleanField(default=True, help_text='Calculates 13% estimation breakdown on taxable line items')),
                ('taxable_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('non_taxable_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('vat_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('round_off', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=6)),
                ('grand_total', models.DecimalField(db_index=True, decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('paid_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('due_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('change_returned', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft / On Hold (होल्ड)'), ('COMPLETED', 'Completed / Finalized (सम्पन्न)'), ('CANCELLED', 'Cancelled (रद्द गरिएको)'), ('RETURNED', 'Fully Returned (फिर्ता भएको)'), ('PARTIALLY_RETURNED', 'Partially Returned (आंशिक फिर्ता)')], db_index=True, default='COMPLETED', max_length=25)),
                ('payment_status', models.CharField(choices=[('PAID', 'Fully Paid (पूरा भुक्तानी)'), ('PARTIAL', 'Partial Payment (आंशिक)'), ('DUE', 'Full Udhaari / Due (उधारो)')], db_index=True, default='PAID', max_length=20)),
                ('cancellation_reason', models.TextField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sales_estimates', to='branches.branch')),
            ],
            options={
                'verbose_name': 'Sales Estimate Slip',
                'verbose_name_plural': 'Sales Estimate Slips',
                'db_table': 'pos_sales_estimates',
                'ordering': ['-created_at'],
            },
        ),
    ]
