# Generated by Django 5.1.15 on 2026-08-20 15:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('branches', '0002_initial'),
        ('customers', '0002_initial'),
        ('inventory', '0002_initial'),
        ('sales', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='salesestimate',
            name='cashier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='billed_estimates', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='salesestimate',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sales_estimates', to='customers.customer'),
        ),
        migrations.AddField(
            model_name='salesestimate',
            name='manager_override_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_discounts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='salesestimateitem',
            name='estimate',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='sales.salesestimate'),
        ),
        migrations.AddField(
            model_name='salesestimateitem',
            name='item_instance',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sold_records', to='inventory.iteminstance'),
        ),
        migrations.AddField(
            model_name='salesestimateitem',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sales_lines', to='inventory.product'),
        ),
        migrations.AddField(
            model_name='salesestimateitem',
            name='unit_conversion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.unitconversion'),
        ),
        migrations.AddField(
            model_name='salespaymenttransaction',
            name='estimate',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_transactions', to='sales.salesestimate'),
        ),
        migrations.AddField(
            model_name='salesreturn',
            name='branch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sales_returns', to='branches.branch'),
        ),
        migrations.AddField(
            model_name='salesreturn',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='returns', to='customers.customer'),
        ),
        migrations.AddField(
            model_name='salesreturn',
            name='original_estimate',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='returns', to='sales.salesestimate'),
        ),
        migrations.AddField(
            model_name='salesreturn',
            name='processed_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='processed_returns', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='salesreturnitem',
            name='estimate_item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='sales.salesestimateitem'),
        ),
        migrations.AddField(
            model_name='salesreturnitem',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventory.product'),
        ),
        migrations.AddField(
            model_name='salesreturnitem',
            name='sales_return',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='sales.salesreturn'),
        ),
    ]
