# Generated by Django 5.1.15 on 2026-08-22 05:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='salesestimate',
            name='salesperson',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='credited_sales', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='salesestimateitem',
            name='device_condition',
            field=models.CharField(blank=True, default='Brand New', max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='salesestimateitem',
            name='secondary_imei',
            field=models.CharField(blank=True, max_length=35, null=True),
        ),
        migrations.AddField(
            model_name='salesestimateitem',
            name='serial_number',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
        migrations.AddField(
            model_name='salesestimateitem',
            name='warranty_months',
            field=models.PositiveIntegerField(default=12),
        ),
        migrations.AddField(
            model_name='salesestimateitem',
            name='warranty_start_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='salesestimateitem',
            name='warranty_terms',
            field=models.CharField(blank=True, default='1 Year Official Brand Warranty', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='salesreturn',
            name='technician_notes',
            field=models.TextField(blank=True, null=True, verbose_name='Diagnostic / Inspection Findings'),
        ),
        migrations.AddField(
            model_name='salesreturnitem',
            name='defect_reason',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='salesreturnitem',
            name='returned_imei',
            field=models.CharField(blank=True, max_length=35, null=True),
        ),
        migrations.AlterField(
            model_name='salesestimate',
            name='is_vat_applicable',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='salesestimateitem',
            name='imei_number',
            field=models.CharField(blank=True, db_index=True, max_length=35, null=True),
        ),
        migrations.AlterField(
            model_name='salesreturnitem',
            name='is_defective',
            field=models.BooleanField(default=False, help_text='Mark item as defective/damaged for vendor warranty claim'),
        ),
    ]
