# Generated by Django 5.1.15 on 2026-08-22 07:08

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0003_salesestimate_salesperson_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesestimate',
            name='total_cost_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14, verbose_name='Total Acquisition Cost (COGS) (NPR)'),
        ),
        migrations.AddField(
            model_name='salesestimate',
            name='total_gross_profit',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14, verbose_name='Gross Profit Realized (NPR)'),
        ),
        migrations.AddField(
            model_name='salesestimateitem',
            name='batch_reference',
            field=models.CharField(blank=True, help_text='Associated Batch Identifier', max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='salesestimateitem',
            name='cost_price',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='Exact Acquisition Cost Price (NPR)'),
        ),
        migrations.AlterField(
            model_name='salesestimateitem',
            name='unit_price',
            field=models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Unit Selling Price (NPR)'),
        ),
    ]
