# Generated by Django 5.1.15 on 2026-08-23 06:19

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0004_salesestimate_total_cost_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesestimateitem',
            name='base_taxable_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14, verbose_name='Pre-Tax Base Amount'),
        ),
        migrations.AddField(
            model_name='salesestimateitem',
            name='tax_pricing_type',
            field=models.CharField(choices=[('INCLUSIVE', 'Tax-Inclusive (Price includes 13% VAT / कर सहित)'), ('EXCLUSIVE', 'Tax-Exclusive (13% VAT added on top / कर बाहेक)'), ('EXEMPT', 'Tax-Exempt / Non-VAT (0% Tax / कर नलाग्ने)')], default='INCLUSIVE', max_length=20, verbose_name='Line Tax Pricing Mode'),
        ),
        migrations.AlterField(
            model_name='salesestimate',
            name='bill_discount_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='Bill Discount (NPR)'),
        ),
        migrations.AlterField(
            model_name='salesestimate',
            name='bill_discount_percent',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5, verbose_name='Bill Discount (%)'),
        ),
        migrations.AlterField(
            model_name='salesestimate',
            name='grand_total',
            field=models.DecimalField(db_index=True, decimal_places=2, default=Decimal('0.00'), max_digits=14, verbose_name='Payable Grand Total'),
        ),
        migrations.AlterField(
            model_name='salesestimate',
            name='item_discount_total',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='Total Line Discounts'),
        ),
        migrations.AlterField(
            model_name='salesestimate',
            name='non_taxable_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14, verbose_name='Non-Taxable / Exempt Amount'),
        ),
        migrations.AlterField(
            model_name='salesestimate',
            name='round_off',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=6, verbose_name='Round Off Offset'),
        ),
        migrations.AlterField(
            model_name='salesestimate',
            name='subtotal',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14, verbose_name='Gross Items Subtotal'),
        ),
        migrations.AlterField(
            model_name='salesestimate',
            name='taxable_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14, verbose_name='Taxable Base Amount'),
        ),
        migrations.AlterField(
            model_name='salesestimate',
            name='vat_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='Total Calculated VAT (13%)'),
        ),
        migrations.AlterField(
            model_name='salesestimateitem',
            name='line_total',
            field=models.DecimalField(decimal_places=2, max_digits=14, verbose_name='Final Line Total'),
        ),
        migrations.AlterField(
            model_name='salesestimateitem',
            name='tax_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='Calculated VAT Amount'),
        ),
    ]
