# Generated by Django 5.1.15 on 2026-08-23 07:54

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0005_salesestimateitem_base_taxable_amount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salesestimate',
            name='is_vat_applicable',
            field=models.BooleanField(default=False, verbose_name='Is Tax Applicable'),
        ),
        migrations.AlterField(
            model_name='salesestimate',
            name='vat_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='Total Tax / VAT Amount'),
        ),
        migrations.AlterField(
            model_name='salesestimateitem',
            name='is_vat_applicable',
            field=models.BooleanField(default=False, verbose_name='Is Tax Applicable'),
        ),
        migrations.AlterField(
            model_name='salesestimateitem',
            name='tax_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='Calculated Tax Amount'),
        ),
        migrations.AlterField(
            model_name='salesestimateitem',
            name='tax_pricing_type',
            field=models.CharField(choices=[('INCLUSIVE', 'Tax-Inclusive (Price includes applicable Tax / कर सहित)'), ('EXCLUSIVE', 'Tax-Exclusive (Tax added on top / कर बाहेक)'), ('EXEMPT', 'Tax-Exempt / Non-Tax (0% Tax / गैर-कर)')], default='EXEMPT', max_length=20, verbose_name='Line Tax Pricing Mode'),
        ),
        migrations.AlterField(
            model_name='salesestimateitem',
            name='vat_rate',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5, verbose_name='Tax / VAT Rate (%)'),
        ),
    ]
