# Generated by Django 5.1.15 on 2026-08-23 14:02

import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('branches', '0002_initial'),
        ('customers', '0002_initial'),
        ('inventory', '0009_iteminstance_mdms_remarks_iteminstance_mdms_status_and_more'),
        ('sales', '0006_alter_salesestimate_is_vat_applicable_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='salesestimate',
            name='has_trade_in_exchange',
            field=models.BooleanField(default=False, verbose_name='Has Old Phone Trade-In Exchange'),
        ),
        migrations.AddField(
            model_name='salesestimate',
            name='trade_in_discount_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Amount deducted directly from bill total for traded-in old handset.', max_digits=12, verbose_name='Trade-In Buy-Back Valuation Credit (NPR)'),
        ),
        migrations.AddField(
            model_name='salesestimate',
            name='trade_in_voucher_reference',
            field=models.CharField(blank=True, db_index=True, max_length=50, null=True, verbose_name='Trade-In Voucher No.'),
        ),
        migrations.CreateModel(
            name='PhoneExchangeTradeIn',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('voucher_number', models.CharField(db_index=True, max_length=50, unique=True, verbose_name='Trade-In Voucher No.')),
                ('customer_name_manual', models.CharField(max_length=150, verbose_name='Customer Name')),
                ('customer_phone_manual', models.CharField(db_index=True, max_length=30, verbose_name='Customer Phone')),
                ('brand_name', models.CharField(max_length=80, verbose_name='Brand (e.g. Apple, Samsung)')),
                ('model_name', models.CharField(max_length=120, verbose_name='Phone Model (e.g. iPhone 13)')),
                ('ram_capacity', models.CharField(blank=True, max_length=30, null=True, verbose_name='RAM (e.g. 6GB)')),
                ('storage_capacity', models.CharField(max_length=30, verbose_name='Storage (e.g. 128GB)')),
                ('color_variant', models.CharField(blank=True, max_length=50, null=True, verbose_name='Color / Finish')),
                ('imei_1', models.CharField(db_index=True, max_length=35, verbose_name='Primary IMEI 1')),
                ('imei_2', models.CharField(blank=True, max_length=35, null=True, verbose_name='Secondary IMEI 2')),
                ('serial_number', models.CharField(blank=True, max_length=60, null=True, verbose_name='Serial Number')),
                ('mdms_status', models.CharField(choices=[('REGISTERED_OFFICIAL', 'NTA MDMS Registered (Official Nepal Distributor)'), ('GRAY_UNREGISTERED', 'Unregistered / Gray Channel (Subject to NTA Notice)'), ('INDIVIDUAL_CUSTOMS_PAID', 'Individual Passenger Import (Customs Duty Paid)'), ('EXEMPT', 'Exempt / Non-Cellular Device')], default='REGISTERED_OFFICIAL', max_length=30, verbose_name='Old Device NTA MDMS Status')),
                ('market_base_value', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='Benchmark Market Value (Pristine Condition) (NPR)')),
                ('total_deductions', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='Total Defect & Physical Deductions (NPR)')),
                ('shop_margin_deduction', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='Shop Buy-Back Margin Buffer (NPR)')),
                ('final_trade_in_value', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='Final Buy-Back / Trade-In Offer Value (NPR)')),
                ('recommended_condition_grade', models.CharField(choices=[('BRAND_NEW', 'Brand New / Sealed Box'), ('OPEN_BOX', 'Open Box / Like New'), ('REFURBISHED', 'Official Refurbished (Certified)'), ('USED_GRADE_A', 'Pre-Owned Grade A (Flawless / Trade-In)'), ('USED_GRADE_B', 'Pre-Owned Grade B (Minor Scratches / Trade-In)'), ('USED_GRADE_C', 'Pre-Owned Grade C (Heavy Wear / Trade-In)')], default='USED_GRADE_B', max_length=25, verbose_name='Calculated Condition Grade')),
                ('status', models.CharField(choices=[('DRAFT', '1. Inspection In-Progress (जाँच हुँदै)'), ('VALUATED', '2. Valuated / Offer Generated (मूल्याङ्कन तयार)'), ('ATTACHED_TO_BILL', '3. Deducted Against POS Bill (बिलमा समायोजन)'), ('RESTOCKED', '4. Added to Used Inventory (मौज्दातमा दर्ता)'), ('CANCELLED', '5. Cancelled / Customer Rejected (रद्द)')], db_index=True, default='DRAFT', max_length=30)),
                ('evaluation_notes', models.TextField(blank=True, null=True)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='trade_in_vouchers', to='branches.branch')),
                ('cashier', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='processed_trade_ins', to=settings.AUTH_USER_MODEL)),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='trade_in_vouchers', to='customers.customer')),
                ('inspector_technician', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inspected_trade_ins', to=settings.AUTH_USER_MODEL)),
                ('pos_estimate', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='trade_in_exchanges', to='sales.salesestimate')),
                ('restocked_item_instance', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='trade_in_origin', to='inventory.iteminstance')),
                ('restocked_product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='trade_in_origins', to='inventory.product')),
            ],
            options={
                'verbose_name': 'Phone Exchange / Trade-In Voucher',
                'verbose_name_plural': 'Phone Exchange / Trade-In Vouchers',
                'db_table': 'pos_phone_trade_in_exchanges',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TradeInInspectionChecklist',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('touch_and_display', models.CharField(choices=[('PASS_FLAWLESS', 'Pass: Flawless Screen & Touch (0% Deduction)'), ('MINOR_SCRATCHES', 'Minor Hairline Scratches (-5% Deduction)'), ('GREEN_LINE_BLEED', 'Display Lines / OLED Bleed (-35% Deduction)'), ('CRACKED_GLASS', 'Front Glass Cracked (-40% Deduction)'), ('DEAD_TOUCH', 'Dead Touch Digitizer / Black Display (-60% Deduction)')], default='PASS_FLAWLESS', max_length=30)),
                ('front_and_back_cameras', models.CharField(choices=[('BOTH_WORKING', 'Both Front & Rear Cameras Clear (0% Deduction)'), ('FRONT_DEFECTIVE', 'Front Selfie Camera Blurry/Dead (-10% Deduction)'), ('REAR_DEFECTIVE', 'Rear Main Camera Lens/Focus Broken (-15% Deduction)'), ('BOTH_DEFECTIVE', 'Both Cameras Defective (-25% Deduction)')], default='BOTH_WORKING', max_length=30)),
                ('charging_and_battery', models.CharField(choices=[('HEALTH_GOOD_85_PLUS', 'Battery Health 85%+ / Normal Backup (0% Deduction)'), ('HEALTH_FAIR_70_85', 'Battery Health 70-85% / Fair Backup (-8% Deduction)'), ('POOR_DRAINING_FAST', 'Battery Draining Rapidly / Service Needed (-15% Deduction)'), ('PORT_FAULTY', 'Charging Port Loose / Intermittent (-10% Deduction)')], default='HEALTH_GOOD_85_PLUS', max_length=30)),
                ('wifi_bluetooth_gps', models.CharField(choices=[('ALL_WORKING', 'Wi-Fi, Bluetooth & GPS All Working (0% Deduction)'), ('WIFI_FAULTY', 'Wi-Fi Greyed Out / Cannot Connect (-20% Deduction)'), ('BT_FAULTY', 'Bluetooth Failure (-10% Deduction)'), ('NO_SIGNAL', 'Baseband / Signal Chip Failure (-40% Deduction)')], default='ALL_WORKING', max_length=30)),
                ('cellular_calling_mic_speaker', models.CharField(choices=[('ALL_CLEAR', 'Mic, Earpiece & Loudspeaker Clear (0% Deduction)'), ('MIC_FAULTY', 'Primary Microphone Not Working (-10% Deduction)'), ('EARPIECE_FAULTY', 'Ear Speaker Muffled (-8% Deduction)'), ('LOUDSPEAKER_CRACKLE', 'Loudspeaker Crackling / Distorted (-8% Deduction)')], default='ALL_CLEAR', max_length=30)),
                ('biometrics_security', models.CharField(choices=[('FINGERPRINT_FACEID_OK', 'Fingerprint & Face ID Fully Functional (0% Deduction)'), ('FINGERPRINT_DEAD', 'Fingerprint Sensor Dead (-10% Deduction)'), ('FACEID_FAIL', 'Face ID / TrueDepth Disabled (-18% Deduction)'), ('NOT_SUPPORTED', 'Not Supported on this Model (0% Deduction)')], default='FINGERPRINT_FACEID_OK', max_length=30)),
                ('body_frame_condition', models.CharField(choices=[('PRISTINE_GRADE_A', 'Grade A: Pristine / Near Mint Condition (0% Deduction)'), ('LIGHT_SCUFFS_GRADE_B', 'Grade B: Normal Scuffs / Minor Edge Wear (-6% Deduction)'), ('CORNER_DENTS_GRADE_C', 'Grade C: Noticeable Drop Dents / Back Scratches (-12% Deduction)'), ('BENT_FRAME_GRADE_D', 'Grade D: Bent Frame / Heavy Structural Damage (-25% Deduction)')], default='LIGHT_SCUFFS_GRADE_B', max_length=30)),
                ('liquid_ingress_ldi', models.CharField(choices=[('WHITE_NO_LIQUID', 'White / Clean: No Liquid Ingress (0% Deduction)'), ('PINK_RED_TRIGGERED', 'Pink / Red: Liquid Damage Indicator Triggered (-30% Deduction)')], default='WHITE_NO_LIQUID', max_length=30)),
                ('original_accessories_available', models.CharField(choices=[('BOX_AND_ORIGINAL_CHARGER', 'Original Box + Original Fast Charger (0% Deduction)'), ('CHARGER_ONLY', 'Charger Only (No Box) (-4% Deduction)'), ('BOX_ONLY', 'Box Only (No Charger) (-4% Deduction)'), ('HANDSET_ONLY', 'Handset Only (No Box / No Charger) (-8% Deduction)')], default='HANDSET_ONLY', max_length=30)),
                ('account_lock_factory_reset', models.CharField(choices=[('ICLOUD_MI_ACCOUNT_REMOVED', 'iCloud / Mi Account / Google FRP Fully Removed (Ready for Sale)'), ('FRP_LOCKED_CANNOT_RESET', 'Account Locked / Cannot Reset (PROHIBITED - Zero Value)')], default='ICLOUD_MI_ACCOUNT_REMOVED', max_length=35)),
                ('diagnostic_score_percent', models.DecimalField(decimal_places=2, default=Decimal('100.00'), max_digits=5, verbose_name='Diagnostic Condition Score (%)')),
                ('technician_remarks', models.TextField(blank=True, null=True)),
                ('trade_in_voucher', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='inspection_checklist', to='sales.phoneexchangetradein')),
            ],
            options={
                'verbose_name': 'Trade-In 10-Point Inspection Checklist',
                'verbose_name_plural': 'Trade-In 10-Point Inspection Checklists',
                'db_table': 'pos_trade_in_inspection_checklists',
            },
        ),
        migrations.CreateModel(
            name='TradeInLegalUndertaking',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('customer_full_name', models.CharField(max_length=150, verbose_name='Customer Full Name (English/Nepali)')),
                ('customer_father_or_spouse_name', models.CharField(blank=True, max_length=150, null=True, verbose_name='Father / Spouse Name')),
                ('id_type', models.CharField(choices=[('CITIZENSHIP', 'Nepali Citizenship Card (नागरिकता प्रमाणपत्र)'), ('NATIONAL_ID', 'National Identity Card (राष्ट्रिय परिचयपत्र)'), ('DRIVING_LICENSE', 'Smart Driving License (सवारी चालक अनुमतिपत्र)'), ('PASSPORT', 'Passport (राहदानी)')], default='CITIZENSHIP', max_length=30)),
                ('id_number', models.CharField(db_index=True, max_length=60, verbose_name='Identification / Citizenship No.')),
                ('id_issued_district', models.CharField(default='Kathmandu', max_length=100, verbose_name='Issued District')),
                ('id_issued_date_bs', models.CharField(blank=True, max_length=20, null=True, verbose_name='Issued Date (BS)')),
                ('permanent_address', models.CharField(max_length=255, verbose_name='Permanent Address (District, Ward, Municipality)')),
                ('current_address', models.CharField(blank=True, max_length=255, null=True, verbose_name='Current Residence / Room Address')),
                ('id_front_image', models.ImageField(blank=True, null=True, upload_to='trade_in/kyc/%Y/%m/', verbose_name='Citizenship / NID Front Photo')),
                ('id_back_image', models.ImageField(blank=True, null=True, upload_to='trade_in/kyc/%Y/%m/', verbose_name='Citizenship / NID Back Photo')),
                ('customer_live_photo', models.ImageField(blank=True, null=True, upload_to='trade_in/kyc/%Y/%m/', verbose_name='Customer Live Photo Snapshot (Holding Phone)')),
                ('customer_digital_signature', models.TextField(blank=True, help_text='Base64 string of digital signature or thumbprint canvas data', null=True)),
                ('declaration_text', models.TextField(verbose_name='Full Undertaking Text')),
                ('declaration_accepted', models.BooleanField(default=True, verbose_name='Customer Accepted Legal Ownership Responsibility')),
                ('trade_in_voucher', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='legal_undertaking', to='sales.phoneexchangetradein')),
                ('verified_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='verified_trade_in_undertakings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Customer Ownership Undertaking (Police Compliance)',
                'verbose_name_plural': 'Customer Ownership Undertakings (Police Compliance)',
                'db_table': 'pos_trade_in_legal_undertakings',
            },
        ),
    ]
