# Generated by Django 5.1.15 on 2026-08-26 06:04

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('branches', '0002_initial'),
        ('customers', '0002_initial'),
        ('inventory', '0011_iteminstance_unique_imei_2_when_present'),
        ('sales', '0007_salesestimate_has_trade_in_exchange_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='phoneexchangetradein',
            index=models.Index(fields=['branch', 'status'], name='idx_tradein_branch_status'),
        ),
        migrations.AddIndex(
            model_name='phoneexchangetradein',
            index=models.Index(fields=['imei_1'], name='idx_tradein_imei1'),
        ),
        migrations.AddIndex(
            model_name='phoneexchangetradein',
            index=models.Index(fields=['voucher_number'], name='idx_tradein_voucher_no'),
        ),
        migrations.AddIndex(
            model_name='salesestimate',
            index=models.Index(fields=['bill_date_ad', 'status', 'branch'], name='idx_est_date_status_branch'),
        ),
        migrations.AddIndex(
            model_name='salesestimate',
            index=models.Index(fields=['branch', 'payment_status', 'created_at'], name='idx_est_branch_pay_created'),
        ),
        migrations.AddIndex(
            model_name='salesestimate',
            index=models.Index(fields=['customer', 'bill_date_ad'], name='idx_est_cust_date'),
        ),
        migrations.AddIndex(
            model_name='salesestimate',
            index=models.Index(fields=['salesperson', 'bill_date_ad'], name='idx_est_salesperson_date'),
        ),
        migrations.AddIndex(
            model_name='salesestimateitem',
            index=models.Index(fields=['estimate', 'product'], name='idx_estitem_est_prod'),
        ),
        migrations.AddIndex(
            model_name='salesestimateitem',
            index=models.Index(fields=['imei_number'], name='idx_estitem_imei'),
        ),
        migrations.AddIndex(
            model_name='salespaymenttransaction',
            index=models.Index(fields=['estimate', 'payment_mode'], name='idx_pay_est_mode'),
        ),
        migrations.AddIndex(
            model_name='salespaymenttransaction',
            index=models.Index(fields=['payment_mode', 'created_at'], name='idx_pay_mode_date'),
        ),
        migrations.AddIndex(
            model_name='salesreturn',
            index=models.Index(fields=['branch', 'created_at'], name='idx_return_branch_date'),
        ),
        migrations.AddIndex(
            model_name='salesreturn',
            index=models.Index(fields=['return_number'], name='idx_return_num'),
        ),
        migrations.AddIndex(
            model_name='salesreturnitem',
            index=models.Index(fields=['sales_return', 'product'], name='idx_retitem_ret_prod'),
        ),
        migrations.AddIndex(
            model_name='tradeinlegalundertaking',
            index=models.Index(fields=['id_number', 'id_type'], name='idx_undertaking_id'),
        ),
    ]
