# Generated by Django 5.1.15 on 2026-09-04 03:42

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0008_phoneexchangetradein_idx_tradein_branch_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesestimate',
            name='bill_discount_input_value',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Raw input value entered by cashier in UI (e.g. 5.00 for 5%, or 1000.00 for flat Rs. 1,000).', max_digits=12, verbose_name='Bill Discount Input Value'),
        ),
        migrations.AddField(
            model_name='salesestimate',
            name='bill_discount_type',
            field=models.CharField(choices=[('NONE', 'No Discount (छुट छैन)'), ('PERCENTAGE', 'Percentage Concession (%)'), ('FIXED', 'Fixed Amount Concession (नगद रकम छुट)')], db_index=True, default='PERCENTAGE', max_length=15, verbose_name='Bill Discount Type'),
        ),
        migrations.AddField(
            model_name='salesestimate',
            name='discount_approved_at',
            field=models.DateTimeField(blank=True, help_text='Exact timestamp when manager override PIN authorized the discount/price override.', null=True, verbose_name='Discount Approval Timestamp'),
        ),
        migrations.AddField(
            model_name='salesestimate',
            name='discount_reason',
            field=models.CharField(blank=True, help_text='e.g. Customer Negotiation, Clearance, Damaged Packaging, VIP Loyalty.', max_length=255, null=True, verbose_name='Commercial Discount Reason / Justification'),
        ),
        migrations.AddField(
            model_name='salesestimateitem',
            name='discount_input_value',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Raw input value entered by cashier (e.g. 5.00 for 5%, or 500.00 for flat Rs. 500).', max_digits=12, verbose_name='Discount Input Value'),
        ),
        migrations.AddField(
            model_name='salesestimateitem',
            name='discount_type',
            field=models.CharField(choices=[('NONE', 'No Discount (छुट छैन)'), ('PERCENTAGE', 'Percentage Concession (%)'), ('FIXED', 'Fixed Amount Concession (नगद रकम छुट)')], db_index=True, default='PERCENTAGE', max_length=15, verbose_name='Discount Type'),
        ),
        migrations.AddField(
            model_name='salesestimateitem',
            name='official_unit_price',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Official catalog price at the moment of billing before any cashier price override.', max_digits=12, verbose_name='Official Catalog Price (NPR)'),
        ),
        migrations.AddField(
            model_name='salesestimateitem',
            name='price_override_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Total concession: (official_unit_price - unit_price) * quantity.', max_digits=12, verbose_name='Price Override Concession Amount (NPR)'),
        ),
        migrations.AlterField(
            model_name='salesestimate',
            name='trade_in_discount_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text="Agreed buy-back valuation of customer's old phone deducted directly from bill payable total.", max_digits=12, verbose_name='Trade-In Buy-Back Valuation Credit (NPR)'),
        ),
    ]
