# Generated by Django 5.1.15 on 2026-09-04 08:32

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0015_product_is_discountable'),
        ('sales', '0009_salesestimate_bill_discount_input_value_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesestimateitem',
            name='allocated_bill_discount_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text="Line item's proportionate share of the invoice-level bill discount.", max_digits=12, verbose_name='Allocated Bill Discount (NPR)'),
        ),
        migrations.AddField(
            model_name='salesestimateitem',
            name='effective_discount_percent',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Secondary control percentage calculated against line selling base for authorization, limits, and audit.', max_digits=5, verbose_name='Effective Discount (%)'),
        ),
        migrations.AddField(
            model_name='salesestimateitem',
            name='item_discount_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Actual monetary deduction resulting strictly from the item discount input (strictly isolated from bill discounts).', max_digits=12, verbose_name='Actual Item Discount Amount (NPR)'),
        ),
        migrations.AddField(
            model_name='salesreturnitem',
            name='discount_input_value',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='Original Discount Input Value'),
        ),
        migrations.AddField(
            model_name='salesreturnitem',
            name='discount_type',
            field=models.CharField(choices=[('NONE', 'No Discount (छुट छैन)'), ('PERCENTAGE', 'Percentage Concession (%)'), ('AMOUNT', 'Fixed Amount Concession (नगद रकम छुट)'), ('FIXED', 'Fixed Amount [Legacy Alias] (नगद रकम छुट)')], db_index=True, default='NONE', max_length=15, verbose_name='Original Item Discount Type'),
        ),
        migrations.AddField(
            model_name='salesreturnitem',
            name='effective_discount_percent',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5, verbose_name='Original Effective Discount (%)'),
        ),
        migrations.AddField(
            model_name='salesreturnitem',
            name='item_discount_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='Original Item Discount Amount (NPR)'),
        ),
        migrations.AlterField(
            model_name='salesestimate',
            name='bill_discount_type',
            field=models.CharField(choices=[('NONE', 'No Discount (छुट छैन)'), ('PERCENTAGE', 'Percentage Concession (%)'), ('AMOUNT', 'Fixed Amount Concession (नगद रकम छुट)'), ('FIXED', 'Fixed Amount [Legacy Alias] (नगद रकम छुट)')], db_index=True, default='PERCENTAGE', max_length=15, verbose_name='Bill Discount Type'),
        ),
        migrations.AlterField(
            model_name='salesestimateitem',
            name='discount_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Total line concession: item_discount_amount + allocated_bill_discount_amount.', max_digits=12, verbose_name='Total Line Discount Concession (NPR)'),
        ),
        migrations.AlterField(
            model_name='salesestimateitem',
            name='discount_input_value',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Exact numeric input typed by cashier (e.g. 5.00 for 5%, or 2500.00 for Rs. 2,500).', max_digits=12, verbose_name='Discount Input Value'),
        ),
        migrations.AlterField(
            model_name='salesestimateitem',
            name='discount_percent',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Synchronized with effective_discount_percent for backward compatibility.', max_digits=5, verbose_name='Legacy Discount (%)'),
        ),
        migrations.AlterField(
            model_name='salesestimateitem',
            name='discount_type',
            field=models.CharField(choices=[('NONE', 'No Discount (छुट छैन)'), ('PERCENTAGE', 'Percentage Concession (%)'), ('AMOUNT', 'Fixed Amount Concession (नगद रकम छुट)'), ('FIXED', 'Fixed Amount [Legacy Alias] (नगद रकम छुट)')], db_index=True, default='NONE', max_length=15, verbose_name='Discount Type'),
        ),
        migrations.AddIndex(
            model_name='salesestimateitem',
            index=models.Index(fields=['discount_type'], name='idx_estitem_disc_type'),
        ),
        migrations.AddIndex(
            model_name='salesreturnitem',
            index=models.Index(fields=['discount_type'], name='idx_retitem_disc_type'),
        ),
    ]
