# Generated by Django 5.1.15 on 2026-09-08 07:49

import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('branches', '0006_alter_branch_city_alter_branch_district'),
        ('customers', '0002_initial'),
        ('inventory', '0015_product_is_discountable'),
        ('sales', '0010_salesestimateitem_allocated_bill_discount_amount_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='phoneexchangetradein',
            options={'ordering': ['-intake_date_ad', '-created_at'], 'verbose_name': 'Phone Exchange / Trade-In Voucher', 'verbose_name_plural': 'Phone Exchange / Trade-In Vouchers'},
        ),
        migrations.AlterModelOptions(
            name='salesestimate',
            options={'ordering': ['-bill_date_ad', '-created_at'], 'verbose_name': 'Sales Estimate Slip', 'verbose_name_plural': 'Sales Estimate Slips'},
        ),
        migrations.AlterModelOptions(
            name='salesreturn',
            options={'ordering': ['-return_date_ad', '-created_at'], 'verbose_name': 'Sales Return', 'verbose_name_plural': 'Sales Returns'},
        ),
        migrations.AddField(
            model_name='phoneexchangetradein',
            name='fiscal_year',
            field=models.CharField(blank=True, db_index=True, max_length=10, null=True, verbose_name='Fiscal Year (BS)'),
        ),
        migrations.AddField(
            model_name='phoneexchangetradein',
            name='intake_date_ad',
            field=models.DateField(db_index=True, default=django.utils.timezone.now, verbose_name='Trade-In Date (AD)'),
        ),
        migrations.AddField(
            model_name='phoneexchangetradein',
            name='intake_date_bs',
            field=models.CharField(blank=True, db_index=True, max_length=15, null=True, verbose_name='Trade-In Date (BS)'),
        ),
        migrations.AddField(
            model_name='salesestimate',
            name='fiscal_year',
            field=models.CharField(blank=True, db_index=True, help_text='Nepali Fiscal Year derived from BS date (e.g. 2080/81, 2081/82).', max_length=10, null=True, verbose_name='Fiscal Year (BS)'),
        ),
        migrations.AddField(
            model_name='salesreturn',
            name='fiscal_year',
            field=models.CharField(blank=True, db_index=True, max_length=10, null=True, verbose_name='Fiscal Year (BS)'),
        ),
        migrations.AddField(
            model_name='salesreturn',
            name='return_date_ad',
            field=models.DateField(db_index=True, default=django.utils.timezone.now, verbose_name='Return Date (AD)'),
        ),
        migrations.AddField(
            model_name='salesreturn',
            name='return_date_bs',
            field=models.CharField(blank=True, db_index=True, max_length=15, null=True, verbose_name='Return Date (BS)'),
        ),
        migrations.AlterField(
            model_name='salesestimate',
            name='bill_date_ad',
            field=models.DateField(db_index=True, default=django.utils.timezone.now, help_text='Gregorian date for database indexing and accounting. Allows historical import dates.', verbose_name='Bill Date (AD)'),
        ),
        migrations.AlterField(
            model_name='salesestimate',
            name='bill_date_bs',
            field=models.CharField(blank=True, db_index=True, help_text='Bikram Sambat formatted date string (YYYY-MM-DD).', max_length=15, null=True, verbose_name='Bill Date (BS)'),
        ),
        migrations.AlterField(
            model_name='salesestimateitem',
            name='item_discount_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Actual monetary deduction resulting strictly from the item discount input (isolated from bill discounts).', max_digits=12, verbose_name='Actual Item Discount Amount (NPR)'),
        ),
        migrations.AddIndex(
            model_name='phoneexchangetradein',
            index=models.Index(fields=['fiscal_year', 'branch'], name='idx_tradein_fy_branch'),
        ),
        migrations.AddIndex(
            model_name='salesestimate',
            index=models.Index(fields=['fiscal_year', 'branch'], name='idx_est_fy_branch'),
        ),
        migrations.AddIndex(
            model_name='salesreturn',
            index=models.Index(fields=['return_date_ad', 'branch'], name='idx_ret_date_branch'),
        ),
        migrations.AddIndex(
            model_name='salesreturn',
            index=models.Index(fields=['fiscal_year', 'branch'], name='idx_ret_fy_branch'),
        ),
    ]
