# Generated by Django 5.1.15 on 2026-09-17 14:29

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('branches', '0006_alter_branch_city_alter_branch_district'),
        ('customers', '0003_alter_customer_current_credit_balance'),
        ('inventory', '0015_product_is_discountable'),
        ('sales', '0011_alter_phoneexchangetradein_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='salesestimate',
            name='branch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sales_estimates', to='branches.branch', verbose_name='Store Branch'),
        ),
        migrations.AlterField(
            model_name='salesestimate',
            name='cashier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='billed_estimates', to=settings.AUTH_USER_MODEL, verbose_name='Billed Cashier'),
        ),
        migrations.AlterField(
            model_name='salesestimate',
            name='change_returned',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='Change Returned'),
        ),
        migrations.AlterField(
            model_name='salesestimate',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sales_estimates', to='customers.customer', verbose_name='Linked Customer Profile'),
        ),
        migrations.AlterField(
            model_name='salesestimate',
            name='due_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14, verbose_name='Due / Udhaari Amount'),
        ),
        migrations.AlterField(
            model_name='salesestimate',
            name='fiscal_year',
            field=models.CharField(blank=True, db_index=True, help_text='Nepali Fiscal Year derived from BS date (e.g. 2080/81, 2081/82, 2082/83, 2083/84).', max_length=10, null=True, verbose_name='Fiscal Year (BS)'),
        ),
        migrations.AlterField(
            model_name='salesestimate',
            name='manager_override_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_discounts', to=settings.AUTH_USER_MODEL, verbose_name='Authorized Manager Override'),
        ),
        migrations.AlterField(
            model_name='salesestimate',
            name='paid_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14, verbose_name='Paid Amount'),
        ),
        migrations.AlterField(
            model_name='salesestimate',
            name='salesperson',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='credited_sales', to=settings.AUTH_USER_MODEL, verbose_name='Credited Salesperson'),
        ),
        migrations.AlterField(
            model_name='salesestimate',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Draft / On Hold (होल्ड)'), ('COMPLETED', 'Completed / Finalized (सम्पन्न)'), ('CANCELLED', 'Cancelled / Voided (रद्द गरिएको)'), ('RETURNED', 'Fully Returned (फिर्ता भएको)'), ('PARTIALLY_RETURNED', 'Partially Returned (आंशिक फिर्ता)')], db_index=True, default='COMPLETED', max_length=25),
        ),
        migrations.AlterField(
            model_name='salesestimateitem',
            name='imei_number',
            field=models.CharField(blank=True, db_index=True, max_length=35, null=True, verbose_name='Sold IMEI 1'),
        ),
        migrations.AlterField(
            model_name='salesestimateitem',
            name='secondary_imei',
            field=models.CharField(blank=True, max_length=35, null=True, verbose_name='Sold IMEI 2'),
        ),
        migrations.AlterField(
            model_name='salesreturn',
            name='branch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sales_returns', to='branches.branch', verbose_name='Store Branch'),
        ),
        migrations.AlterField(
            model_name='salesreturn',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='returns', to='customers.customer', verbose_name='Customer'),
        ),
        migrations.AlterField(
            model_name='salesreturn',
            name='original_estimate',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='returns', to='sales.salesestimate', verbose_name='Original Sales Invoice'),
        ),
        migrations.AlterField(
            model_name='salesreturn',
            name='processed_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='processed_returns', to=settings.AUTH_USER_MODEL, verbose_name='Processed By'),
        ),
        migrations.AlterField(
            model_name='salesreturn',
            name='refund_mode',
            field=models.CharField(choices=[('CASH', 'Cash Refund'), ('STORE_CREDIT', 'Customer Store Credit'), ('EXCHANGE_ADJUST', 'Adjusted in Exchange Bill')], default='CASH', max_length=30, verbose_name='Refund Mode'),
        ),
        migrations.AlterField(
            model_name='salesreturn',
            name='return_number',
            field=models.CharField(db_index=True, max_length=50, unique=True, verbose_name='Return Voucher No.'),
        ),
        migrations.AlterField(
            model_name='salesreturn',
            name='total_refund_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14, verbose_name='Total Refund Amount'),
        ),
        migrations.AlterField(
            model_name='salesreturnitem',
            name='base_unit_quantity',
            field=models.DecimalField(decimal_places=3, max_digits=12, verbose_name='Base Unit Quantity'),
        ),
        migrations.AlterField(
            model_name='salesreturnitem',
            name='estimate_item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='sales.salesestimateitem', verbose_name='Original Sales Line'),
        ),
        migrations.AlterField(
            model_name='salesreturnitem',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventory.product', verbose_name='Returned Product'),
        ),
        migrations.AlterField(
            model_name='salesreturnitem',
            name='refund_amount',
            field=models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Net Refund Amount'),
        ),
        migrations.AlterField(
            model_name='salesreturnitem',
            name='return_quantity',
            field=models.DecimalField(decimal_places=3, max_digits=10, verbose_name='Return Quantity'),
        ),
        migrations.AlterField(
            model_name='salesreturnitem',
            name='returned_imei',
            field=models.CharField(blank=True, max_length=35, null=True, verbose_name='Returned IMEI'),
        ),
    ]
