# Generated by Django 5.1.15 on 2026-09-23 05:17

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('branches', '0006_alter_branch_city_alter_branch_district'),
        ('customers', '0004_alter_customer_options_and_more'),
        ('sales', '0012_alter_salesestimate_branch_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='salesestimate',
            name='customer_name_manual',
            field=models.CharField(blank=True, db_index=True, max_length=200, null=True, verbose_name='Walk-in Customer Name'),
        ),
        migrations.AlterField(
            model_name='salesestimate',
            name='customer_pan',
            field=models.CharField(blank=True, db_index=True, max_length=15, null=True, verbose_name='Customer PAN (Optional)'),
        ),
        migrations.AlterField(
            model_name='salesestimate',
            name='customer_phone_manual',
            field=models.CharField(blank=True, db_index=True, max_length=25, null=True, verbose_name='Walk-in Phone'),
        ),
        migrations.AddIndex(
            model_name='salesestimate',
            index=models.Index(fields=['customer_phone_manual'], name='idx_est_cust_phone_man'),
        ),
        migrations.AddIndex(
            model_name='salesestimate',
            index=models.Index(fields=['customer_name_manual'], name='idx_est_cust_name_man'),
        ),
        migrations.AddIndex(
            model_name='salesestimate',
            index=models.Index(fields=['customer_pan'], name='idx_est_cust_pan'),
        ),
        migrations.AddIndex(
            model_name='salesestimate',
            index=models.Index(fields=['branch', 'customer_phone_manual'], name='idx_est_branch_cust_phone'),
        ),
    ]
