# Generated by Django 5.1.15 on 2026-09-26 09:35

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0013_alter_salesestimate_customer_name_manual_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salesestimate',
            name='grand_total',
            field=models.DecimalField(db_index=True, decimal_places=2, default=Decimal('0.00'), help_text='Full commercial value of merchandise sold + taxes. Trade-in allowances act as a tender offset against this total.', max_digits=14, verbose_name='Gross Merchandise Grand Total'),
        ),
        migrations.AlterField(
            model_name='salesestimate',
            name='trade_in_discount_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text="Agreed buy-back valuation of customer's old phone treated as a payment tender offset (barter settlement).", max_digits=12, verbose_name='Trade-In Buy-Back Valuation Allowance (NPR)'),
        ),
        migrations.AlterField(
            model_name='tradeinlegalundertaking',
            name='declaration_text',
            field=models.TextField(blank=True, default='', help_text='Statutory declaration text (defaults to system configuration text if left blank).', verbose_name='Full Undertaking Text'),
        ),
    ]
