# Generated by Django 5.1.15 on 2026-10-02 05:15

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('branches', '0006_alter_branch_city_alter_branch_district'),
        ('customers', '0005_alter_customerudhaariledger_options_and_more'),
        ('sales', '0014_alter_salesestimate_grand_total_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='salesestimate',
            name='bill_type',
            field=models.CharField(choices=[('SALES', 'Official VAT / Sales Invoice (कर बिजक)'), ('ESTIMATE', 'Internal Estimation Slip (अनुमानित पर्चा)')], db_index=True, default='SALES', help_text='Designates whether this transaction is an official VAT sales invoice or an internal estimation voucher.', max_length=20, verbose_name='Document / Bill Type'),
        ),
        migrations.AddIndex(
            model_name='salesestimate',
            index=models.Index(fields=['bill_type', 'status'], name='idx_est_type_status'),
        ),
    ]
