# Generated by Django 5.1.15 on 2026-10-07 09:01

from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('branches', '0006_alter_branch_city_alter_branch_district'),
        ('customers', '0005_alter_customerudhaariledger_options_and_more'),
        ('inventory', '0017_productbatch_expiry_date_and_more'),
        ('sales', '0015_salesestimate_bill_type_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='salesreturn',
            name='non_taxable_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Total non-taxable / exempt merchandise amount reversed across line items.', max_digits=14, verbose_name='Non-Taxable Return Amount (NPR)'),
        ),
        migrations.AddField(
            model_name='salesreturn',
            name='taxable_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Total net taxable base reversed across line items.', max_digits=14, verbose_name='Taxable Return Amount (NPR)'),
        ),
        migrations.AddField(
            model_name='salesreturn',
            name='vat_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Total output VAT reversed across all returned lines in this voucher.', max_digits=12, verbose_name='VAT Reversal Amount (NPR)'),
        ),
        migrations.AddField(
            model_name='salesreturnitem',
            name='non_taxable_return_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Exempt or non-taxable amount reversed for this line item.', max_digits=14, verbose_name='Non-Taxable Return Amount (NPR)'),
        ),
        migrations.AddField(
            model_name='salesreturnitem',
            name='taxable_return_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Pre-tax taxable base reversed for this line item.', max_digits=14, verbose_name='Taxable Return Amount (NPR)'),
        ),
        migrations.AddField(
            model_name='salesreturnitem',
            name='vat_rate',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='VAT percentage applicable to the returned item at the time of return (e.g. 13.00% or 0.00%).', max_digits=5, verbose_name='VAT Rate at Return (%)'),
        ),
        migrations.AddField(
            model_name='salesreturnitem',
            name='vat_reversal_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Output VAT amount reversed for this line item.', max_digits=12, verbose_name='VAT Reversal Amount (NPR)'),
        ),
        migrations.AlterField(
            model_name='salesreturnitem',
            name='base_unit_quantity',
            field=models.DecimalField(decimal_places=3, default=Decimal('1.000'), max_digits=12, verbose_name='Base Unit Quantity'),
        ),
        migrations.AlterField(
            model_name='salesreturnitem',
            name='refund_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='Net Refund Amount'),
        ),
        migrations.AlterField(
            model_name='salesreturnitem',
            name='return_quantity',
            field=models.DecimalField(decimal_places=3, default=Decimal('1.000'), max_digits=10, verbose_name='Return Quantity'),
        ),
        migrations.AddIndex(
            model_name='salesreturn',
            index=models.Index(fields=['branch', 'return_date_ad'], name='idx_ret_br_date_ad'),
        ),
        migrations.AddIndex(
            model_name='salesreturnitem',
            index=models.Index(fields=['vat_rate'], name='idx_retitem_vat_rate'),
        ),
        migrations.AddIndex(
            model_name='salesreturnitem',
            index=models.Index(fields=['sales_return', 'vat_reversal_amount'], name='idx_retitem_ret_vat'),
        ),
    ]
