# Generated by Django 5.1.15 on 2026-08-20 15:30

import django.db.models.deletion
import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('branches', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('name', models.CharField(db_index=True, max_length=200, verbose_name='Customer / Business Name')),
                ('phone_number', models.CharField(db_index=True, max_length=25, unique=True, verbose_name='Mobile / Phone Number')),
                ('alt_phone_number', models.CharField(blank=True, max_length=25, null=True, verbose_name='Alternate Phone')),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('address', models.CharField(blank=True, max_length=255, null=True, verbose_name='Address / City')),
                ('pan_number', models.CharField(blank=True, max_length=15, null=True, verbose_name='PAN Number (For Business/Wholesale)')),
                ('customer_type', models.CharField(choices=[('RETAIL', 'Retail Customer (व्यक्तिगत)'), ('WHOLESALE', 'Wholesale Buyer (थोक बिक्रेता)'), ('VIP', 'VIP / Regular Customer')], db_index=True, default='RETAIL', max_length=20)),
                ('credit_limit', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Maximum allowed credit / udhaari balance (0.00 for no credit allowed)', max_digits=12)),
                ('current_credit_balance', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Outstanding Udhaari payable to the shop', max_digits=12)),
                ('total_spent', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Cumulative sales amount spent across all visits', max_digits=14)),
                ('date_of_birth_bs', models.CharField(blank=True, max_length=15, null=True, verbose_name='DOB (BS: YYYY-MM-DD)')),
                ('date_of_birth_ad', models.DateField(blank=True, null=True, verbose_name='DOB (AD)')),
                ('notes', models.TextField(blank=True, null=True)),
                ('preferred_branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='customers', to='branches.branch')),
            ],
            options={
                'verbose_name': 'Customer',
                'verbose_name_plural': 'Customers',
                'db_table': 'customer_records',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='CustomerUdhaariLedger',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('entry_type', models.CharField(choices=[('DEBIT', 'Credit Purchase (उधारो सामान)'), ('CREDIT', 'Payment Received (रकम भुक्तानी)'), ('ADJUSTMENT', 'Discount / Balance Adjustment')], db_index=True, max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('previous_balance', models.DecimalField(decimal_places=2, max_digits=12)),
                ('resulting_balance', models.DecimalField(decimal_places=2, max_digits=12)),
                ('reference_invoice', models.CharField(blank=True, help_text='Estimate/Invoice Slip No.', max_length=50, null=True)),
                ('payment_mode', models.CharField(blank=True, help_text='Cash, eSewa, Khalti, FonePay, Bank', max_length=30, null=True)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('branch', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='customer_ledgers', to='branches.branch')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='credit_ledger_entries', to='customers.customer')),
            ],
            options={
                'verbose_name': 'Customer Udhaari Entry',
                'verbose_name_plural': 'Customer Udhaari Ledgers',
                'db_table': 'customer_udhaari_ledger',
                'ordering': ['-created_at'],
            },
        ),
    ]
