# Generated by Django 5.1.15 on 2026-09-11 15:05

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='current_credit_balance',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Outstanding Udhaari payable to the shop (calculated strictly from customer credit ledger)', max_digits=12),
        ),
    ]
