# Generated by Django 5.1.15 on 2026-09-17 17:56

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('branches', '0006_alter_branch_city_alter_branch_district'),
        ('customers', '0003_alter_customer_current_credit_balance'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customer',
            options={'ordering': ['name'], 'verbose_name': 'Customer Profile', 'verbose_name_plural': 'Customer Profiles'},
        ),
        migrations.AlterModelOptions(
            name='customerudhaariledger',
            options={'ordering': ['-created_at'], 'verbose_name': 'Customer Udhaari Ledger Entry', 'verbose_name_plural': 'Customer Udhaari Ledger Entries'},
        ),
        migrations.AlterField(
            model_name='customer',
            name='credit_limit',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Maximum allowed credit / udhaari balance (0.00 for cash-only)', max_digits=12, verbose_name='Credit Limit (NPR)'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='current_credit_balance',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Calculated strictly from customer credit sub-ledger entries.', max_digits=12, verbose_name='Outstanding Udhaari Balance (NPR)'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='customer_type',
            field=models.CharField(choices=[('RETAIL', 'Retail Customer (व्यक्तिगत)'), ('WHOLESALE', 'Wholesale / B2B Buyer (थोक बिक्रेता)'), ('VIP', 'VIP / Regular Customer')], db_index=True, default='RETAIL', max_length=20, verbose_name='Customer Category'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email Address'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='notes',
            field=models.TextField(blank=True, null=True, verbose_name='Internal Notes / Terms'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='pan_number',
            field=models.CharField(blank=True, db_index=True, help_text='9-Digit IRD PAN for Institutional / Wholesale Buyers', max_length=15, null=True, verbose_name='Permanent Account Number (PAN)'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='preferred_branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='customers', to='branches.branch', verbose_name='Preferred Store Branch'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='total_spent',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Total invoice purchases spent across all store visits.', max_digits=14, verbose_name='Cumulative Lifetime Spend (NPR)'),
        ),
        migrations.AlterField(
            model_name='customerudhaariledger',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Transaction Amount (NPR)'),
        ),
        migrations.AlterField(
            model_name='customerudhaariledger',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='customer_ledgers', to='branches.branch', verbose_name='Store Branch'),
        ),
        migrations.AlterField(
            model_name='customerudhaariledger',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='credit_ledger_entries', to='customers.customer', verbose_name='Customer Profile'),
        ),
        migrations.AlterField(
            model_name='customerudhaariledger',
            name='entry_type',
            field=models.CharField(choices=[('DEBIT', 'Credit Purchase / Udhaari Taken (+) (उधारो सामान)'), ('CREDIT', 'Payment Received / Settlement (-) (रकम भुक्तानी)'), ('ADJUSTMENT', 'Discount / Balance Adjustment (-) (हिसाब मिलान)')], db_index=True, max_length=20, verbose_name='Entry Type'),
        ),
        migrations.AlterField(
            model_name='customerudhaariledger',
            name='payment_mode',
            field=models.CharField(blank=True, choices=[('CASH', 'Cash (नगद)'), ('ESEWA', 'eSewa (ईसेवा)'), ('KHALTI', 'Khalti (खल्ती)'), ('FONEPAY', 'FonePay QR (फोनपे)'), ('BANK', 'Bank Transfer / ConnectIPS (बैंक)'), ('OTHER', 'Other / Store Credit Adjustment')], default='CASH', max_length=30, null=True, verbose_name='Payment Channel'),
        ),
        migrations.AlterField(
            model_name='customerudhaariledger',
            name='previous_balance',
            field=models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Balance Prior to Entry'),
        ),
        migrations.AlterField(
            model_name='customerudhaariledger',
            name='recorded_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recorded_customer_ledgers', to=settings.AUTH_USER_MODEL, verbose_name='Recorded By Cashier'),
        ),
        migrations.AlterField(
            model_name='customerudhaariledger',
            name='reference_invoice',
            field=models.CharField(blank=True, db_index=True, max_length=50, null=True, verbose_name='Reference Invoice / Slip No.'),
        ),
        migrations.AlterField(
            model_name='customerudhaariledger',
            name='remarks',
            field=models.TextField(blank=True, null=True, verbose_name='Ledger Remarks'),
        ),
        migrations.AlterField(
            model_name='customerudhaariledger',
            name='resulting_balance',
            field=models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Resulting Outstanding Balance'),
        ),
        migrations.AddIndex(
            model_name='customer',
            index=models.Index(fields=['pan_number'], name='idx_cust_pan'),
        ),
        migrations.AddIndex(
            model_name='customer',
            index=models.Index(fields=['customer_type', 'is_active'], name='idx_cust_type_active'),
        ),
        migrations.AddIndex(
            model_name='customer',
            index=models.Index(fields=['current_credit_balance'], name='idx_cust_credit_bal'),
        ),
        migrations.AddIndex(
            model_name='customerudhaariledger',
            index=models.Index(fields=['customer', 'created_at'], name='idx_cledger_cust_date'),
        ),
        migrations.AddIndex(
            model_name='customerudhaariledger',
            index=models.Index(fields=['reference_invoice'], name='idx_cledger_ref_inv'),
        ),
        migrations.AddIndex(
            model_name='customerudhaariledger',
            index=models.Index(fields=['entry_type', 'payment_mode'], name='idx_cledger_type_mode'),
        ),
    ]
