# Generated by Django 5.1.15 on 2026-09-30 05:53

import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('branches', '0006_alter_branch_city_alter_branch_district'),
        ('customers', '0004_alter_customer_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customerudhaariledger',
            options={'ordering': ['-entry_date', '-created_at'], 'verbose_name': 'Customer Udhaari Ledger Entry', 'verbose_name_plural': 'Customer Udhaari Ledger Entries'},
        ),
        migrations.RemoveIndex(
            model_name='customerudhaariledger',
            name='idx_cledger_cust_date',
        ),
        migrations.AddField(
            model_name='customerudhaariledger',
            name='entry_date',
            field=models.DateField(db_index=True, default=django.utils.timezone.now, help_text='Gregorian date of the transaction or repayment. Accurately preserves backdated bills.', verbose_name='Transaction Date (AD)'),
        ),
        migrations.AddField(
            model_name='customerudhaariledger',
            name='entry_date_bs',
            field=models.CharField(blank=True, db_index=True, help_text='Nepali Bikram Sambat date string (YYYY-MM-DD).', max_length=15, null=True, verbose_name='Transaction Date (BS)'),
        ),
        migrations.AddIndex(
            model_name='customerudhaariledger',
            index=models.Index(fields=['customer', '-entry_date'], name='idx_cledger_cust_edate'),
        ),
        migrations.AddIndex(
            model_name='customerudhaariledger',
            index=models.Index(fields=['customer', '-created_at'], name='idx_cledger_cust_date'),
        ),
        migrations.AddIndex(
            model_name='customerudhaariledger',
            index=models.Index(fields=['branch', '-entry_date'], name='idx_cledger_br_edate'),
        ),
        migrations.AddIndex(
            model_name='customerudhaariledger',
            index=models.Index(fields=['entry_date_bs'], name='idx_cledger_bs_date'),
        ),
    ]
