# Generated by Django 5.1.15 on 2026-08-20 15:30

import django.db.models.deletion
import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('branches', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaxPeriodSummary',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('nepali_year', models.PositiveIntegerField(default=2081, verbose_name='BS Year (e.g. 2081)')),
                ('nepali_month', models.PositiveIntegerField(choices=[(1, 'Baishakh (वैशाख)'), (2, 'Jestha (जेठ)'), (3, 'Ashadh (असार)'), (4, 'Shrawan (साउन)'), (5, 'Bhadra (भदौ)'), (6, 'Ashwin (असोज)'), (7, 'Kartik (कार्तिक)'), (8, 'Mangsir (मंसिर)'), (9, 'Poush (पुस)'), (10, 'Magh (माघ)'), (11, 'Falgun (फागुन)'), (12, 'Chaitra (चैत)')], verbose_name='BS Month')),
                ('total_sales_taxable', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('total_sales_non_taxable', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('total_sales_vat', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('total_purchase_taxable', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('total_purchase_non_taxable', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('total_purchase_vat', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('net_vat_payable', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('is_estimation_report', models.BooleanField(default=True, help_text='Mandatory disclaimer flag signifying proforma non-tax status')),
                ('is_locked', models.BooleanField(default=False, verbose_name='Lock Period')),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tax_summaries', to='branches.branch')),
            ],
            options={
                'verbose_name': 'Tax Period Summary',
                'verbose_name_plural': 'Tax Period Summaries',
                'db_table': 'tax_period_summaries',
                'ordering': ['-nepali_year', '-nepali_month'],
            },
        ),
    ]
