# Generated by Django 5.1.15 on 2026-09-08 11:35

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('branches', '0006_alter_branch_city_alter_branch_district'),
        ('taxation', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='taxperiodsummary',
            name='fiscal_year',
            field=models.CharField(blank=True, db_index=True, help_text="Official Nepali Fiscal Year (e.g. '2080/81', '2081/82') derived from Shrawan-Ashadh cycle.", max_length=15, verbose_name='Nepali Fiscal Year (आर्थिक वर्ष)'),
        ),
        migrations.AddField(
            model_name='taxperiodsummary',
            name='period_end_ad',
            field=models.DateField(blank=True, db_index=True, null=True, verbose_name='Period End Date (AD)'),
        ),
        migrations.AddField(
            model_name='taxperiodsummary',
            name='period_start_ad',
            field=models.DateField(blank=True, db_index=True, null=True, verbose_name='Period Start Date (AD)'),
        ),
        migrations.AlterField(
            model_name='taxperiodsummary',
            name='branch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tax_summaries', to='branches.branch', verbose_name='Branch / Store Outlet'),
        ),
        migrations.AlterField(
            model_name='taxperiodsummary',
            name='closed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='closed_tax_periods', to=settings.AUTH_USER_MODEL, verbose_name='Reconciled / Closed By'),
        ),
        migrations.AlterField(
            model_name='taxperiodsummary',
            name='is_estimation_report',
            field=models.BooleanField(default=True, help_text='Mandatory disclaimer flag signifying proforma non-tax status.', verbose_name='Proforma / Estimation Notice Active'),
        ),
        migrations.AlterField(
            model_name='taxperiodsummary',
            name='is_locked',
            field=models.BooleanField(db_index=True, default=False, verbose_name='Period Locked / Reconciled'),
        ),
        migrations.AlterField(
            model_name='taxperiodsummary',
            name='nepali_month',
            field=models.PositiveIntegerField(choices=[(1, 'Baishakh (वैशाख)'), (2, 'Jestha (जेठ)'), (3, 'Ashadh (असार)'), (4, 'Shrawan (साउन)'), (5, 'Bhadra (भदौ)'), (6, 'Ashwin (असोज)'), (7, 'Kartik (कार्तिक)'), (8, 'Mangsir (मंसिर)'), (9, 'Poush (पुस)'), (10, 'Magh (माघ)'), (11, 'Falgun (फागुन)'), (12, 'Chaitra (चैत)')], db_index=True, verbose_name='BS Month'),
        ),
        migrations.AlterField(
            model_name='taxperiodsummary',
            name='nepali_year',
            field=models.PositiveIntegerField(db_index=True, default=2081, verbose_name='BS Year (e.g. 2080, 2081)'),
        ),
        migrations.AlterField(
            model_name='taxperiodsummary',
            name='net_vat_payable',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Calculated as Output VAT - Input VAT.', max_digits=14, verbose_name='Net VAT Payable / (Refundable) (NPR)'),
        ),
        migrations.AlterField(
            model_name='taxperiodsummary',
            name='total_purchase_non_taxable',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14, verbose_name='Total Non-Taxable / Exempt Purchases (NPR)'),
        ),
        migrations.AlterField(
            model_name='taxperiodsummary',
            name='total_purchase_taxable',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14, verbose_name='Total Taxable Purchases (NPR)'),
        ),
        migrations.AlterField(
            model_name='taxperiodsummary',
            name='total_purchase_vat',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='Input VAT Paid (NPR)'),
        ),
        migrations.AlterField(
            model_name='taxperiodsummary',
            name='total_sales_non_taxable',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14, verbose_name='Total Non-Taxable / Exempt Sales (NPR)'),
        ),
        migrations.AlterField(
            model_name='taxperiodsummary',
            name='total_sales_taxable',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14, verbose_name='Total Taxable Sales (NPR)'),
        ),
        migrations.AlterField(
            model_name='taxperiodsummary',
            name='total_sales_vat',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='Output VAT Collected (NPR)'),
        ),
        migrations.AddIndex(
            model_name='taxperiodsummary',
            index=models.Index(fields=['fiscal_year', 'branch'], name='idx_tax_fy_branch'),
        ),
        migrations.AddIndex(
            model_name='taxperiodsummary',
            index=models.Index(fields=['nepali_year', 'nepali_month'], name='idx_tax_yr_mo'),
        ),
        migrations.AddIndex(
            model_name='taxperiodsummary',
            index=models.Index(fields=['period_start_ad', 'period_end_ad'], name='idx_tax_period_dates'),
        ),
    ]
