# Generated by Django 5.1.15 on 2026-08-20 15:30

import django.db.models.deletion
import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('branches', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemConfiguration',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('company_name_en', models.CharField(default='Mobile & Optical Gallery Nepal', max_length=255, verbose_name='Company Name (English)')),
                ('company_name_np', models.CharField(blank=True, default='मोबाइल तथा अप्टिकल ग्यालरी', max_length=255, verbose_name='Company Name (Nepali)')),
                ('pan_number', models.CharField(blank=True, max_length=15, null=True, verbose_name='Permanent Account Number (PAN)')),
                ('vat_number', models.CharField(blank=True, max_length=20, null=True, verbose_name='VAT Registration No.')),
                ('is_vat_registered', models.BooleanField(default=True, help_text='Indicates whether shop applies VAT calculation for estimates & internal ledgers')),
                ('default_vat_rate', models.DecimalField(decimal_places=2, default=Decimal('13.00'), max_digits=5, verbose_name='Default VAT Rate (%)')),
                ('is_estimation_bill_only', models.BooleanField(default=True, help_text='Mandatory flag for non-tax approved estimates/proforma billing')),
                ('bill_header_title', models.CharField(default='ESTIMATE BILL / ESTIMATION SLIP', max_length=100, verbose_name='Bill Title Header')),
                ('bill_estimate_disclaimer', models.TextField(default='NOTICE: This is an internal quotation / estimation slip only and NOT an official VAT/PAN Tax Invoice approved by IRD Nepal.', verbose_name='Estimate Disclaimer Notice')),
                ('currency_symbol', models.CharField(default='Rs.', max_length=10)),
                ('currency_code', models.CharField(default='NPR', max_length=5)),
                ('enable_nepali_calendar', models.BooleanField(default=True, verbose_name='Enable Bikram Sambat (BS) View')),
                ('default_language', models.CharField(choices=[('en', 'English'), ('np', 'Nepali (नेपाली)')], default='en', max_length=5)),
                ('allow_negative_stock', models.BooleanField(default=False, help_text='Allow sales transactions even when calculated system inventory is zero or below.')),
                ('require_manager_approval_discount', models.DecimalField(decimal_places=2, default=Decimal('10.00'), help_text='Discount percentage above which cashier requires Manager override PIN.', max_digits=5)),
                ('thermal_printer_paper_width', models.CharField(choices=[('80mm', '80mm Roll (Thermal POS)'), ('58mm', '58mm Roll (Mini Thermal)'), ('a4', 'Standard A4')], default='80mm', max_length=10)),
            ],
            options={
                'verbose_name': 'System Configuration',
                'verbose_name_plural': 'System Configurations',
                'db_table': 'core_system_configuration',
            },
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('action_type', models.CharField(choices=[('CREATE', 'Creation'), ('UPDATE', 'Modification'), ('DELETE', 'Deletion / Soft Delete'), ('BILL_CANCEL', 'Bill Cancellation'), ('PRICE_OVERRIDE', 'Price Override'), ('STOCK_ADJUST', 'Manual Stock Adjustment'), ('LOGIN_FAIL', 'Failed Login Limit Warning')], db_index=True, max_length=30)),
                ('module', models.CharField(help_text='e.g. POS, Inventory, Purchase, Branch', max_length=50)),
                ('object_repr', models.CharField(max_length=255)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('details', models.JSONField(blank=True, default=dict)),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to='branches.branch')),
            ],
            options={
                'verbose_name': 'Audit Log',
                'verbose_name_plural': 'Audit Logs',
                'db_table': 'core_audit_log',
                'ordering': ['-timestamp'],
            },
        ),
    ]
