# Generated by Django 5.1.15 on 2026-08-23 07:28

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemconfiguration',
            name='tax_system_mode',
            field=models.CharField(choices=[('VAT', 'VAT Registered Shop (Issues VAT Estimates / Invoices)'), ('PAN', 'PAN Only Registered Shop (Issues Non-VAT / PAN Estimates)'), ('NO_TAX', 'Simple Counter / No-Tax Shop (Issues Simple Cash Estimates)')], db_index=True, default='PAN', help_text='Controls whether the POS calculates VAT, operates in zero-tax PAN mode, or simple estimation.', max_length=20, verbose_name='Shop Operating Tax Mode'),
        ),
        migrations.AlterField(
            model_name='systemconfiguration',
            name='bill_estimate_disclaimer',
            field=models.TextField(default='NOTICE: This is an internal quotation / estimation slip only and NOT an official Tax Invoice approved by IRD Nepal.', verbose_name='Estimate Disclaimer Notice'),
        ),
        migrations.AlterField(
            model_name='systemconfiguration',
            name='bill_header_title',
            field=models.CharField(default='SALES ESTIMATE SLIP', help_text="e.g., 'ESTIMATE SLIP', 'PAN ESTIMATE BILL', 'PROFORMA INVOICE', 'CASH MEMO'", max_length=100, verbose_name='Bill Title Header'),
        ),
        migrations.AlterField(
            model_name='systemconfiguration',
            name='company_name_en',
            field=models.CharField(default='Smart Mobile & Optics Hub', max_length=255, verbose_name='Company Name (English)'),
        ),
        migrations.AlterField(
            model_name='systemconfiguration',
            name='company_name_np',
            field=models.CharField(blank=True, default='स्मार्ट मोबाइल तथा अप्टिकल हब', max_length=255, verbose_name='Company Name (Nepali)'),
        ),
        migrations.AlterField(
            model_name='systemconfiguration',
            name='default_vat_rate',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Set to 0.00% for PAN/No-Tax shops, or your applicable VAT % (e.g. 13.00, 5.00).', max_digits=5, verbose_name='Default Tax / VAT Rate (%)'),
        ),
        migrations.AlterField(
            model_name='systemconfiguration',
            name='is_estimation_bill_only',
            field=models.BooleanField(default=True, help_text='Indicates that all printed bills are internal proforma estimations (Non-IRD Tax Invoices).'),
        ),
        migrations.AlterField(
            model_name='systemconfiguration',
            name='is_vat_registered',
            field=models.BooleanField(default=False, help_text='Synchronized automatically based on selected Shop Operating Tax Mode.', verbose_name='Is VAT Registered'),
        ),
    ]
