# Generated by Django 5.1.15 on 2026-08-23 13:25

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_systemconfiguration_tax_system_mode_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemconfiguration',
            name='default_trade_in_margin_percent',
            field=models.DecimalField(decimal_places=2, default=Decimal('15.00'), help_text='Buffer percentage deducted from market fair value to safeguard store buy-back profitability.', max_digits=5, verbose_name='Default Trade-In Profit Margin (%)'),
        ),
        migrations.AddField(
            model_name='systemconfiguration',
            name='enable_nta_mdms_tracking',
            field=models.BooleanField(default=True, help_text='Enforce MDMS registration status verification on all imported and sold handsets.', verbose_name='Enable NTA MDMS Tracking'),
        ),
        migrations.AddField(
            model_name='systemconfiguration',
            name='undertaking_declaration_text_np',
            field=models.TextField(default='म यस पसलमा मेरो स्वामित्वमा रहेको पुरानो मोबाइल फोन बिक्री/साटासाट गर्न आएको र उक्त फोन कुनै पनि चोरी, ठगी वा गैरकानुनी कार्यमा संलग्न नरहेको पूर्ण व्यहोरा सत्य हो। यदि भविष्यमा उक्त फोनका सम्बन्धमा कुनै कानुनी विवाद वा प्रहरी छानबिन भएमा म स्वयम् प्रचलित नेपाल कानुन बमोजिम पूर्ण जिम्मेवार रहनेछु भनी यो जिम्मानामा तथा मञ्जुरीनामा फारममा सहिछाप गरिदिएँ।', verbose_name='Police-Compliant Handover Undertaking Declaration (Nepali)'),
        ),
        migrations.AddField(
            model_name='systemconfiguration',
            name='warn_on_gray_market_sale',
            field=models.BooleanField(default=True, help_text='Displays an alert banner and prints a customer disclaimer when selling a non-MDMS phone.', verbose_name='Warn On Unregistered / Gray Market Sale'),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='action_type',
            field=models.CharField(choices=[('CREATE', 'Creation'), ('UPDATE', 'Modification'), ('DELETE', 'Deletion / Soft Delete'), ('BILL_CANCEL', 'Bill Cancellation'), ('PRICE_OVERRIDE', 'Price Override'), ('STOCK_ADJUST', 'Manual Stock Adjustment'), ('MDMS_OVERRIDE', 'NTA MDMS Status Override'), ('TRADE_IN_PURCHASE', 'Trade-In / Old Phone Buy-Back Intake'), ('LOGIN_FAIL', 'Failed Login Limit Warning')], db_index=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='module',
            field=models.CharField(help_text='e.g. POS, Inventory, TradeIn, MDMS, Purchase, Branch', max_length=50),
        ),
        migrations.AlterField(
            model_name='systemconfiguration',
            name='default_vat_rate',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Set to 0.00% for PAN/No-Tax shops, or applicable VAT % (e.g. 13.00, 5.00).', max_digits=5, verbose_name='Default Tax / VAT Rate (%)'),
        ),
    ]
