# Generated by Django 5.1.15 on 2026-08-25 09:49

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('branches', '0002_initial'),
        ('core', '0004_systemconfiguration_default_trade_in_margin_percent_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='systemconfiguration',
            name='is_vat_registered',
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='module',
            field=models.CharField(db_index=True, help_text='e.g. POS, Inventory, TradeIn, MDMS, Purchase, Branch', max_length=50),
        ),
        migrations.AlterField(
            model_name='systemconfiguration',
            name='bill_header_title',
            field=models.CharField(default='SALES ESTIMATE SLIP', help_text="e.g. 'ESTIMATE SLIP', 'PAN ESTIMATE BILL', 'PROFORMA INVOICE', 'CASH MEMO'", max_length=100, verbose_name='Bill Title Header'),
        ),
        migrations.AlterField(
            model_name='systemconfiguration',
            name='is_estimation_bill_only',
            field=models.BooleanField(default=True, help_text='Indicates that printed receipts are internal estimations (Non-IRD Tax Invoices).'),
        ),
        migrations.AlterField(
            model_name='systemconfiguration',
            name='warn_on_gray_market_sale',
            field=models.BooleanField(default=True, help_text='Displays an alert banner and customer disclaimer when selling a non-MDMS phone.', verbose_name='Warn On Unregistered / Gray Market Sale'),
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['timestamp', 'module'], name='core_audit__timesta_bbb3d8_idx'),
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['action_type', 'timestamp'], name='core_audit__action__9c4f3a_idx'),
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['branch', 'timestamp'], name='core_audit__branch__a42fe2_idx'),
        ),
    ]
