# Generated by Django 5.1.15 on 2026-08-29 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_remove_systemconfiguration_is_vat_registered_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='systemconfiguration',
            name='bill_header_title',
            field=models.CharField(default='SALES ESTIMATE SLIP', help_text="e.g. 'SALES ESTIMATE SLIP', 'ESTIMATE SLIP', 'PAN ESTIMATE BILL', 'PROFORMA INVOICE'", max_length=100, verbose_name='Bill Title Header'),
        ),
    ]
