# Generated by Django 5.1.15 on 2026-08-30 04:31

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_systemconfiguration_bill_header_title'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='systemconfiguration',
            options={'verbose_name': 'System Configuration', 'verbose_name_plural': 'System Configuration'},
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='action_type',
            field=models.CharField(choices=[('CREATE', 'Creation'), ('UPDATE', 'Modification'), ('DELETE', 'Deletion / Soft Delete'), ('BILL_CANCEL', 'Bill Cancellation / Void'), ('PRICE_OVERRIDE', 'Price / Discount Override'), ('STOCK_ADJUST', 'Manual Stock Adjustment'), ('MDMS_OVERRIDE', 'NTA MDMS Status Override'), ('TRADE_IN_PURCHASE', 'Trade-In / Old Phone Buy-Back Intake'), ('LOGIN_FAIL', 'Failed Login Limit Warning')], db_index=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='module',
            field=models.CharField(db_index=True, help_text='e.g. POS, Inventory, TradeIn, MDMS, Purchases, Users', max_length=50),
        ),
        migrations.AlterField(
            model_name='systemconfiguration',
            name='allow_negative_stock',
            field=models.BooleanField(default=False, help_text='Allow checkout transactions even when calculated system inventory is zero or below.', verbose_name='Allow Negative Stock'),
        ),
        migrations.AlterField(
            model_name='systemconfiguration',
            name='bill_header_title',
            field=models.CharField(default='SALES ESTIMATE SLIP', help_text="Header text printed on slips (e.g. 'SALES ESTIMATE SLIP', 'ESTIMATE BILL', 'PROFORMA INVOICE').", max_length=100, verbose_name='Bill Title Header'),
        ),
        migrations.AlterField(
            model_name='systemconfiguration',
            name='currency_code',
            field=models.CharField(default='NPR', max_length=5, verbose_name='Currency Code'),
        ),
        migrations.AlterField(
            model_name='systemconfiguration',
            name='currency_symbol',
            field=models.CharField(default='Rs.', max_length=10, verbose_name='Currency Symbol'),
        ),
        migrations.AlterField(
            model_name='systemconfiguration',
            name='default_language',
            field=models.CharField(choices=[('en', 'English'), ('np', 'Nepali (नेपाली)')], default='en', max_length=5, verbose_name='Default Language'),
        ),
        migrations.AlterField(
            model_name='systemconfiguration',
            name='default_trade_in_margin_percent',
            field=models.DecimalField(decimal_places=2, default=Decimal('15.00'), help_text='Percentage deducted from market fair value to safeguard store buy-back profitability.', max_digits=5, verbose_name='Default Trade-In Profit Margin (%)'),
        ),
        migrations.AlterField(
            model_name='systemconfiguration',
            name='default_vat_rate',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Set to 13.00% for VAT shops, or 0.00% for PAN/No-Tax stores.', max_digits=5, verbose_name='Default Tax / VAT Rate (%)'),
        ),
        migrations.AlterField(
            model_name='systemconfiguration',
            name='enable_nta_mdms_tracking',
            field=models.BooleanField(default=True, help_text='Enforces MDMS registration status verification on all imported and sold handsets.', verbose_name='Enable NTA MDMS Tracking'),
        ),
        migrations.AlterField(
            model_name='systemconfiguration',
            name='is_estimation_bill_only',
            field=models.BooleanField(default=True, help_text='Indicates printed receipts are internal estimations (Non-IRD Tax Invoices).', verbose_name='Is Estimation Slip Only'),
        ),
        migrations.AlterField(
            model_name='systemconfiguration',
            name='require_manager_approval_discount',
            field=models.DecimalField(decimal_places=2, default=Decimal('10.00'), help_text='Cashier discounts exceeding this percentage require a Manager Override PIN to checkout.', max_digits=5, verbose_name='Manager Override Discount Threshold (%)'),
        ),
        migrations.AlterField(
            model_name='systemconfiguration',
            name='tax_system_mode',
            field=models.CharField(choices=[('VAT', 'VAT Registered Shop (Calculates 13% VAT on Taxable Items)'), ('PAN', 'PAN Only Registered Shop (Operates in 0.00% Non-VAT Mode)'), ('NO_TAX', 'Simple Counter / No-Tax Mode (Internal Proforma Quotations)')], db_index=True, default='PAN', help_text='Controls whether the POS calculates VAT, operates in zero-tax PAN mode, or simple estimation.', max_length=20, verbose_name='Shop Operating Tax Mode'),
        ),
        migrations.AlterField(
            model_name='systemconfiguration',
            name='thermal_printer_paper_width',
            field=models.CharField(choices=[('80mm', '80mm Roll (Standard Thermal POS)'), ('58mm', '58mm Roll (Mini Thermal)'), ('a4', 'Standard A4 Sheet')], default='80mm', max_length=10, verbose_name='Thermal Printer Width'),
        ),
    ]
