# Generated by Django 5.1.15 on 2026-09-15 14:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0002_journalentry_source_id_journalentry_source_module_and_more'),
        ('core', '0007_alter_systemconfiguration_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemconfiguration',
            name='default_bank_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='config_bank_accounts', to='accounting.account', verbose_name='Default Primary Bank Account (GL 1020)'),
        ),
        migrations.AddField(
            model_name='systemconfiguration',
            name='default_card_clearing_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='config_card_clearing_accounts', to='accounting.account', verbose_name='Default POS Card Clearing Account (GL 1160)'),
        ),
        migrations.AddField(
            model_name='systemconfiguration',
            name='default_cash_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='config_cash_accounts', to='accounting.account', verbose_name='Default Cash in Hand Account (GL 1010)'),
        ),
        migrations.AddField(
            model_name='systemconfiguration',
            name='default_cogs_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='config_cogs_accounts', to='accounting.account', verbose_name='Default Cost of Goods Sold / COGS (GL 5010)'),
        ),
        migrations.AddField(
            model_name='systemconfiguration',
            name='default_discount_expense_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='config_discount_accounts', to='accounting.account', verbose_name='Default Sales Discount Expense Account (GL 4030)'),
        ),
        migrations.AddField(
            model_name='systemconfiguration',
            name='default_drawings_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='config_drawings_accounts', to='accounting.account', verbose_name='Default Owner Drawings Account (GL 3130)'),
        ),
        migrations.AddField(
            model_name='systemconfiguration',
            name='default_esewa_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='config_esewa_accounts', to='accounting.account', verbose_name='Default eSewa Wallet Clearing Account (GL 1140)'),
        ),
        migrations.AddField(
            model_name='systemconfiguration',
            name='default_fonepay_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='config_fonepay_accounts', to='accounting.account', verbose_name='Default FonePay QR Clearing Account (GL 1130)'),
        ),
        migrations.AddField(
            model_name='systemconfiguration',
            name='default_gateway_fee_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='config_gateway_fee_accounts', to='accounting.account', verbose_name='Default Payment Gateway / MDR Fee Account (GL 6190)'),
        ),
        migrations.AddField(
            model_name='systemconfiguration',
            name='default_interest_expense_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='config_interest_accounts', to='accounting.account', verbose_name='Default Finance & Loan Interest Account (GL 6210)'),
        ),
        migrations.AddField(
            model_name='systemconfiguration',
            name='default_inventory_asset_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='config_inventory_accounts', to='accounting.account', verbose_name='Default Merchandise Inventory Asset (GL 1300)'),
        ),
        migrations.AddField(
            model_name='systemconfiguration',
            name='default_khalti_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='config_khalti_accounts', to='accounting.account', verbose_name='Default Khalti Wallet Clearing Account (GL 1150)'),
        ),
        migrations.AddField(
            model_name='systemconfiguration',
            name='default_payable_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='config_payable_accounts', to='accounting.account', verbose_name='Default Accounts Payable / Creditors (GL 2010)'),
        ),
        migrations.AddField(
            model_name='systemconfiguration',
            name='default_receivable_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='config_receivable_accounts', to='accounting.account', verbose_name='Default Accounts Receivable / Debtors (GL 1200)'),
        ),
        migrations.AddField(
            model_name='systemconfiguration',
            name='default_sales_revenue_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='config_sales_accounts', to='accounting.account', verbose_name='Default Sales Revenue Account (GL 4010)'),
        ),
        migrations.AddField(
            model_name='systemconfiguration',
            name='default_shrinkage_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='config_shrinkage_accounts', to='accounting.account', verbose_name='Default Inventory Shrinkage & Loss Account (GL 5030)'),
        ),
        migrations.AddField(
            model_name='systemconfiguration',
            name='default_vat_input_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='config_vat_input_accounts', to='accounting.account', verbose_name='Default Input VAT Receivable 13% (GL 1400)'),
        ),
        migrations.AddField(
            model_name='systemconfiguration',
            name='default_vat_output_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='config_vat_output_accounts', to='accounting.account', verbose_name='Default Output VAT Payable 13% (GL 2020)'),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='module',
            field=models.CharField(db_index=True, help_text='e.g. POS, Inventory, TradeIn, MDMS, Purchases, Users, Accounting', max_length=50),
        ),
    ]
