# Generated by Django 5.1.15 on 2026-09-23 04:09

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('branches', '0006_alter_branch_city_alter_branch_district'),
        ('core', '0008_systemconfiguration_default_bank_account_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditlog',
            name='object_repr',
            field=models.CharField(db_index=True, help_text='Primary target identifier (Invoice #, IMEI, Product SKU, or Username).', max_length=255),
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['object_repr'], name='core_audit__object__f0be02_idx'),
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['module', 'object_repr'], name='core_audit__module_1c6f7d_idx'),
        ),
    ]
