# Generated by Django 5.1.15 on 2026-09-27 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_alter_auditlog_object_repr_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemconfiguration',
            name='enforce_imei_tracking',
            field=models.BooleanField(db_index=True, default=True, help_text='When unchecked (Backlog Mode), phones can be added, purchased, and sold using simple quantities without typing IMEIs. When checked (Live Mode), all phone transactions strictly demand IMEIs.', verbose_name='Enforce Mandatory Handset IMEI Tracking'),
        ),
    ]
