# Generated by Django 5.1.15 on 2026-09-30 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_systemconfiguration_enforce_imei_tracking'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemconfiguration',
            name='allow_cashier_backdating',
            field=models.BooleanField(db_index=True, default=False, help_text='When enabled (Backlog Mode), cashiers and counter sales staff can freely backdate bills and select historical dates without requiring a Supervisor / Manager Override PIN. When disabled (Live Mode), cashiers must provide a Manager PIN to backdate bills.', verbose_name='Allow Staff / Cashier Backdating (Backlog Mode)'),
        ),
    ]
