# Generated by Django 5.1.15 on 2026-09-15 14:54

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0001_initial'),
        ('branches', '0006_alter_branch_city_alter_branch_district'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='journalentry',
            name='source_id',
            field=models.CharField(blank=True, db_index=True, max_length=100, null=True, verbose_name='Source Document Identifier (Invoice / GRN / Slip No)'),
        ),
        migrations.AddField(
            model_name='journalentry',
            name='source_module',
            field=models.CharField(choices=[('MANUAL', 'Manual Journal Voucher'), ('POS_SALE', 'Point of Sale (POS) Checkout'), ('SALES_RETURN', 'Sales Return / Credit Note'), ('PURCHASE_GRN', 'Purchase GRN Intake'), ('PURCHASE_RETURN', 'Purchase Return / Debit Note'), ('CUSTOMER_PAYMENT', 'Customer Debt / Credit Collection'), ('SUPPLIER_PAYMENT', 'Supplier Bill Payment'), ('EXPENSE_VOUCHER', 'Shop Operating Expense'), ('STOCK_ADJUSTMENT', 'Inventory Adjustment (Damage/Loss/Surplus)'), ('TRADE_IN', 'Used Device Trade-In / Buy-Back Intake'), ('REPAIR_SERVICE', 'Workshop & Repair Billing'), ('BANK_CONTRA', 'Bank / Cash Contra Transfer'), ('PAYROLL', 'Staff Salary / Payroll Disbursement'), ('DEPRECIATION', 'Asset Depreciation Voucher'), ('YEAR_END_CLOSING', 'Fiscal Year Closing / Retained Earnings Transfer')], db_index=True, default='MANUAL', max_length=30, verbose_name='Originating Business Module'),
        ),
        migrations.AlterField(
            model_name='account',
            name='code',
            field=models.CharField(db_index=True, max_length=30, unique=True, verbose_name='Account Code (e.g. 1010-01, 1130-KTM)'),
        ),
        migrations.AlterField(
            model_name='account',
            name='system_tag',
            field=models.CharField(choices=[('NONE', 'Standard Custom Ledger'), ('CASH', 'Cash in Hand (Counter Float)'), ('BANK', 'Bank Account / Checking Account'), ('FONEPAY', 'FonePay Merchant Clearing / Dynamic QR'), ('ESEWA', 'eSewa Digital Wallet Clearing'), ('KHALTI', 'Khalti Digital Wallet Clearing'), ('CARD_CLEARING', 'Card POS Merchant Settlement / In-Transit'), ('ACCOUNTS_RECEIVABLE', 'Accounts Receivable / Trade Debtors (Customer Control)'), ('ACCOUNTS_PAYABLE', 'Accounts Payable / Trade Creditors (Supplier Control)'), ('INVENTORY_ASSET', 'Merchandise Inventory Asset (Sellable Stock)'), ('DEFECTIVE_INVENTORY_ASSET', 'Quarantined Defective Inventory Asset'), ('INVENTORY_SHRINKAGE', 'Stock Shrinkage & Damage Write-Off Expense'), ('INVENTORY_SURPLUS', 'Inventory Count Surplus & Gain'), ('ACCUMULATED_DEPRECIATION', 'Accumulated Depreciation (Contra-Asset)'), ('COGS', 'Cost of Goods Sold (COGS)'), ('SALES_REVENUE', 'Sales Revenue'), ('SALES_RETURN', 'Sales Returns & Deductions'), ('SALES_DISCOUNT', 'Sales Merchandise Discounts Expense'), ('OUTPUT_VAT', 'Output VAT / Tax Payable 13%'), ('INPUT_VAT', 'Input VAT / Tax Receivable 13%'), ('REPAIR_SERVICE_INCOME', 'Repair & Workshop Service Revenue'), ('REPAIR_PARTS_COGS', 'Repair Spare Parts Consumed Expense'), ('LOAN_PRINCIPAL', 'Bank Loan & Long-Term Borrowings (Liability)'), ('INTEREST_EXPENSE', 'Finance & Interest Charges Expense'), ('PAYMENT_GATEWAY_FEE', 'Payment Gateway MDR / POS Commission Expense'), ('OWNER_CAPITAL', 'Proprietor Capital / Equity'), ('OWNER_DRAWINGS', 'Owner Drawings (Contra-Equity)'), ('RETAINED_EARNINGS', 'Retained Earnings / Current Year P&L'), ('OPENING_BALANCE_EQUITY', 'Opening Balance Equity Offset')], db_index=True, default='NONE', max_length=35, verbose_name='System Automation Tag'),
        ),
        migrations.AlterField(
            model_name='journalentry',
            name='reference_document',
            field=models.CharField(blank=True, db_index=True, max_length=100, null=True, verbose_name='External Reference (Cheque No, Bank Ref, Deposit Slip)'),
        ),
        migrations.AddIndex(
            model_name='journalentry',
            index=models.Index(fields=['source_module', 'source_id'], name='idx_je_src_module_id'),
        ),
        migrations.AddConstraint(
            model_name='journalentry',
            constraint=models.UniqueConstraint(condition=models.Q(('source_id__isnull', False), ('status', 'POSTED'), models.Q(('source_id', ''), _negated=True)), fields=('source_module', 'source_id', 'voucher_type'), name='unique_posted_source_module_id_voucher'),
        ),
    ]
