# Generated by Django 5.1.15 on 2026-09-17 16:07

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0002_journalentry_source_id_journalentry_source_module_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountingfiscalyear',
            name='closed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Closed At Timestamp'),
        ),
        migrations.AlterField(
            model_name='accountingfiscalyear',
            name='closed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='closed_fiscal_years', to=settings.AUTH_USER_MODEL, verbose_name='Closed By User'),
        ),
        migrations.AlterField(
            model_name='accountingfiscalyear',
            name='is_closed',
            field=models.BooleanField(db_index=True, default=False, help_text='Locked years reject any new journal entries, sales, or financial modifications.', verbose_name='Is Fiscal Year Closed / Audited'),
        ),
        migrations.AlterField(
            model_name='accountingfiscalyear',
            name='name',
            field=models.CharField(db_index=True, max_length=20, unique=True, verbose_name='Fiscal Year Label (e.g., 2080/81, 2081/82, 2082/83, 2083/84)'),
        ),
        migrations.AlterField(
            model_name='bankreconciliation',
            name='gl_book_balance',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14, verbose_name='System GL Book Balance (NPR)'),
        ),
        migrations.AlterField(
            model_name='expensevoucher',
            name='payment_account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payment_vouchers_issued', to='accounting.account', verbose_name='Payment Source Ledger (Cash or Bank)'),
        ),
        migrations.AlterField(
            model_name='journalentry',
            name='source_id',
            field=models.CharField(blank=True, db_index=True, max_length=100, null=True, verbose_name='Source Document Identifier'),
        ),
    ]
