# Generated by Django 5.1.15 on 2026-09-23 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0003_alter_accountingfiscalyear_closed_at_and_more'),
        ('branches', '0006_alter_branch_city_alter_branch_district'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='name_np',
            field=models.CharField(blank=True, db_index=True, max_length=200, null=True, verbose_name='Account Ledger Name (Nepali / देवनागरी)'),
        ),
        migrations.AddIndex(
            model_name='account',
            index=models.Index(fields=['code'], name='idx_acc_code'),
        ),
        migrations.AddIndex(
            model_name='account',
            index=models.Index(fields=['name'], name='idx_acc_name'),
        ),
        migrations.AddIndex(
            model_name='account',
            index=models.Index(fields=['code', 'name'], name='idx_acc_code_name'),
        ),
        migrations.AddIndex(
            model_name='account',
            index=models.Index(fields=['name_np'], name='idx_acc_name_np'),
        ),
        migrations.AddIndex(
            model_name='account',
            index=models.Index(fields=['branch', 'code'], name='idx_acc_branch_code'),
        ),
        migrations.AddIndex(
            model_name='account',
            index=models.Index(fields=['branch', 'name'], name='idx_acc_branch_name'),
        ),
        migrations.AddIndex(
            model_name='accountgroup',
            index=models.Index(fields=['code', 'name'], name='idx_accgrp_code_name'),
        ),
        migrations.AddIndex(
            model_name='accountgroup',
            index=models.Index(fields=['category', 'nature'], name='idx_accgrp_cat_nat'),
        ),
    ]
