# Generated by Django 5.1.15 on 2026-09-27 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0004_alter_account_name_np_account_idx_acc_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='code',
            field=models.CharField(db_index=True, max_length=30, unique=True, verbose_name='Account Code (e.g. 1110-01, 2150-KTM, 5050-NR)'),
        ),
        migrations.AlterField(
            model_name='account',
            name='system_tag',
            field=models.CharField(choices=[('NONE', 'Standard Custom Ledger'), ('CASH', 'Cash in Hand (Counter Float / Main Drawer)'), ('BANK', 'Bank Account / Checking Account'), ('FONEPAY', 'FonePay Merchant Clearing / Dynamic QR'), ('ESEWA', 'eSewa Digital Wallet Clearing'), ('KHALTI', 'Khalti Digital Wallet Clearing'), ('CARD_CLEARING', 'Card POS Merchant Settlement / In-Transit'), ('ACCOUNTS_RECEIVABLE', 'Accounts Receivable / Trade Debtors (Customer Control)'), ('ACCOUNTS_PAYABLE', 'Accounts Payable / Trade Creditors (Supplier Control)'), ('TRADE_IN_CLEARING', 'Trade-In Buy-Back Clearing / Payable (Account 2150)'), ('INVENTORY_ASSET', 'Merchandise Inventory Asset (Sellable Stock)'), ('DEFECTIVE_INVENTORY_ASSET', 'Quarantined Defective Inventory Asset'), ('INVENTORY_SHRINKAGE', 'Stock Shrinkage & Damage Write-Off Expense'), ('INVENTORY_SURPLUS', 'Inventory Count Surplus & Gain'), ('ACCUMULATED_DEPRECIATION', 'Accumulated Depreciation (Contra-Asset)'), ('COGS', 'Cost of Goods Sold (COGS)'), ('SALES_REVENUE', 'Sales Revenue'), ('SALES_RETURN', 'Sales Returns & Deductions'), ('SALES_DISCOUNT', 'Sales Merchandise Discounts Expense'), ('OUTPUT_VAT', 'Output VAT / Tax Payable 13%'), ('INPUT_VAT', 'Input VAT / Tax Receivable 13%'), ('REPAIR_SERVICE_INCOME', 'Repair & Workshop Service Revenue'), ('REPAIR_PARTS_COGS', 'Repair Spare Parts Consumed Expense'), ('LOAN_PRINCIPAL', 'Bank Loan & Long-Term Borrowings (Liability)'), ('INTEREST_EXPENSE', 'Finance & Interest Charges Expense'), ('PAYMENT_GATEWAY_FEE', 'Payment Gateway MDR / POS Commission Expense'), ('CASH_SHORTAGE', 'Cash Drawer Shortage Expense (Account 5050)'), ('CASH_SURPLUS', 'Cash Drawer Excess & Surplus Income (Account 4040)'), ('MISC_INCOME', 'Miscellaneous Operating Income / Surplus'), ('OWNER_CAPITAL', 'Proprietor Capital / Equity'), ('OWNER_DRAWINGS', 'Owner Drawings (Contra-Equity)'), ('RETAINED_EARNINGS', 'Retained Earnings / Current Year P&L'), ('OPENING_BALANCE_EQUITY', 'Opening Balance Equity Offset')], db_index=True, default='NONE', max_length=35, verbose_name='System Automation Tag'),
        ),
    ]
