# Generated by Django 5.1.15 on 2026-09-30 05:29

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0005_alter_account_code_alter_account_system_tag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expensevoucher',
            name='expense_date',
            field=models.DateField(db_index=True, default=django.utils.timezone.now, help_text='Gregorian date for database indexing.', verbose_name='Expense Date (AD)'),
        ),
        migrations.AlterField(
            model_name='expensevoucher',
            name='expense_date_bs',
            field=models.CharField(blank=True, help_text='Bikram Sambat formatted date string (YYYY-MM-DD).', max_length=15, null=True, verbose_name='Expense Date (BS)'),
        ),
        migrations.AlterField(
            model_name='journalentry',
            name='entry_date',
            field=models.DateField(db_index=True, default=django.utils.timezone.now, help_text='Gregorian date for database indexing and accounting.', verbose_name='Voucher Date (AD)'),
        ),
        migrations.AlterField(
            model_name='journalentry',
            name='entry_date_bs',
            field=models.CharField(blank=True, db_index=True, help_text='Bikram Sambat formatted date string. Takes precedence if provided.', max_length=15, null=True, verbose_name='Voucher Date (BS: YYYY-MM-DD)'),
        ),
        migrations.AlterField(
            model_name='journalentry',
            name='fiscal_year',
            field=models.CharField(blank=True, db_index=True, help_text='Nepali Fiscal Year derived from BS date (e.g. 2080/81 to 2083/84).', max_length=15, null=True, verbose_name='Nepali Fiscal Year (आर्थिक वर्ष)'),
        ),
    ]
