# Generated by Django 5.1.15 on 2026-08-20 15:30

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('branches', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('role', models.CharField(choices=[('OWNER', 'Shop Owner / Central Admin (मालिक)'), ('MANAGER', 'Branch Manager (शाखा प्रबन्धक)'), ('STAFF', 'Cashier / Sales Staff (विक्रेता)'), ('ACCOUNTANT', 'Accountant (लेखापाल)')], db_index=True, default='STAFF', max_length=20, verbose_name='System Role')),
                ('phone_number', models.CharField(max_length=20, unique=True, verbose_name='Mobile Number (Nepal 98XXXXXXXX)')),
                ('pin_code', models.CharField(blank=True, help_text='4-6 Digit Quick PIN for POS terminal unlocking & discount overrides', max_length=6, null=True)),
                ('failed_login_attempts', models.PositiveIntegerField(default=0)),
                ('is_locked', models.BooleanField(default=False)),
                ('assigned_branch', models.ForeignKey(blank=True, help_text='Default branch assigned to this staff member', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='staff_members', to='branches.branch')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'System User',
                'verbose_name_plural': 'System Users',
                'db_table': 'auth_users',
                'ordering': ['username'],
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
