# Generated by Django 5.1.15 on 2026-08-26 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='pin_code',
            field=models.CharField(blank=True, help_text='Salted PBKDF2 hash of the 4-6 digit PIN used for POS overrides', max_length=128, null=True, verbose_name='Manager Override PIN (Hashed)'),
        ),
    ]
