# Generated by Django 5.1.15 on 2026-08-30 04:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('branches', '0004_alter_stocktransferrequest_options_and_more'),
        ('users', '0002_alter_user_pin_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='assigned_branch',
            field=models.ForeignKey(blank=True, help_text='Standard Cashiers and Sales Staff are strictly locked to this store branch.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='staff_members', to='branches.branch', verbose_name='Assigned Store Branch'),
        ),
        migrations.AlterField(
            model_name='user',
            name='failed_login_attempts',
            field=models.PositiveIntegerField(default=0, verbose_name='Failed Login Counter'),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_locked',
            field=models.BooleanField(default=False, verbose_name='Account Locked'),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone_number',
            field=models.CharField(help_text='Primary 10-digit mobile number for terminal login and notifications.', max_length=20, unique=True, verbose_name='Mobile Number (Nepal 98XXXXXXXX)'),
        ),
        migrations.AlterField(
            model_name='user',
            name='pin_code',
            field=models.CharField(blank=True, help_text='Salted cryptographic hash of the 4-6 digit numeric PIN used for POS authorizations.', max_length=128, null=True, verbose_name='Manager Override PIN (Salted Hash)'),
        ),
    ]
