# Generated by Django 5.1.15 on 2026-09-23 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('branches', '0006_alter_branch_city_alter_branch_district'),
        ('users', '0003_alter_user_assigned_branch_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='phone_number',
            field=models.CharField(db_index=True, help_text='Primary 10-digit mobile number for terminal login and notifications.', max_length=20, unique=True, verbose_name='Mobile Number (Nepal 98XXXXXXXX)'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['role', 'assigned_branch'], name='auth_users_role_6ae512_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['is_active', 'assigned_branch'], name='auth_users_is_acti_082631_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['role', 'is_active'], name='auth_users_role_1dc74c_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['phone_number'], name='auth_users_phone_n_061fb4_idx'),
        ),
    ]
