# Generated by Django 5.1.15 on 2026-08-20 15:30

import django.db.models.deletion
import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('branches', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Brand Name')),
                ('origin_country', models.CharField(blank=True, default='Nepal', max_length=50)),
            ],
            options={
                'verbose_name': 'Brand',
                'verbose_name_plural': 'Brands',
                'db_table': 'inv_brands',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ProductCategory',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Category Name')),
                ('name_np', models.CharField(blank=True, max_length=100, null=True, verbose_name='Category Name (Nepali)')),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='Code (e.g. MOB, ACC, OPT)')),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Product Category',
                'verbose_name_plural': 'Product Categories',
                'db_table': 'inv_categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='UnitConversion',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('unit_name', models.CharField(max_length=50, verbose_name='Packaging Unit Name (e.g. Box, Dozen, Carton)')),
                ('conversion_factor', models.DecimalField(decimal_places=3, help_text='How many base units are inside this unit? (e.g., 1 Box = 50 pcs -> Factor = 50.000)', max_digits=10)),
                ('selling_price_per_unit', models.DecimalField(blank=True, decimal_places=2, help_text='Custom price when sold in this unit package (Optional)', max_digits=12, null=True)),
                ('barcode', models.CharField(blank=True, help_text='Unique barcode for this package', max_length=100, null=True, unique=True)),
            ],
            options={
                'verbose_name': 'Unit Packaging Conversion',
                'verbose_name_plural': 'Unit Packaging Conversions',
                'db_table': 'inv_unit_conversions',
            },
        ),
        migrations.CreateModel(
            name='UnitOfMeasurement',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Unit Name (e.g. Piece, Pair)')),
                ('name_np', models.CharField(blank=True, max_length=50, null=True, verbose_name='Nepali Unit Name (e.g. पिस, जोडी)')),
                ('code', models.CharField(max_length=10, unique=True, verbose_name='Short Code (e.g. PCS, PR, BOX)')),
                ('allow_decimal', models.BooleanField(default=False, help_text='Enable for kg, meter, weight items.')),
            ],
            options={
                'verbose_name': 'Unit of Measurement',
                'verbose_name_plural': 'Units of Measurement',
                'db_table': 'inv_units_of_measurement',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('name', models.CharField(db_index=True, max_length=255, verbose_name='Product Name')),
                ('sku', models.CharField(db_index=True, max_length=50, unique=True, verbose_name='SKU / Product Code')),
                ('barcode', models.CharField(db_index=True, max_length=100, unique=True, verbose_name='Barcode Number')),
                ('model_number', models.CharField(blank=True, max_length=100, null=True)),
                ('color_variant', models.CharField(blank=True, max_length=50, null=True, verbose_name='Color / Variant')),
                ('size_dimension', models.CharField(blank=True, max_length=50, null=True, verbose_name='Size (Glasses/Straps)')),
                ('purchase_price', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='Cost Price (NPR)')),
                ('selling_price', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Selling Price / MRP (NPR)')),
                ('wholesale_price', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Wholesale Price (NPR)')),
                ('max_discount_percent', models.DecimalField(decimal_places=2, default=Decimal('10.00'), max_digits=5, verbose_name='Max Allowed Discount %')),
                ('is_vat_applicable', models.BooleanField(default=True, verbose_name='VAT Applicable (13% Calculation)')),
                ('vat_rate', models.DecimalField(decimal_places=2, default=Decimal('13.00'), max_digits=5)),
                ('requires_imei_tracking', models.BooleanField(default=False, help_text='Check for smartphones/tablets.')),
                ('requires_serial_tracking', models.BooleanField(default=False, help_text='Check for premium smartwatches/devices.')),
                ('warranty_months', models.PositiveIntegerField(default=0, verbose_name='Warranty (Months)')),
                ('reorder_level', models.DecimalField(decimal_places=2, default=Decimal('5.00'), max_digits=10, verbose_name='Global Reorder Level')),
                ('image', models.ImageField(blank=True, null=True, upload_to='products/%Y/%m/')),
                ('description', models.TextField(blank=True, null=True)),
                ('brand', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='inventory.brand')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='products', to='inventory.productcategory')),
            ],
            options={
                'verbose_name': 'Product',
                'verbose_name_plural': 'Products',
                'db_table': 'inv_products',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ItemInstance',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('imei_1', models.CharField(blank=True, db_index=True, max_length=30, null=True, unique=True, verbose_name='IMEI 1')),
                ('imei_2', models.CharField(blank=True, max_length=30, null=True, verbose_name='IMEI 2')),
                ('serial_number', models.CharField(blank=True, db_index=True, max_length=50, null=True, unique=True, verbose_name='Serial Number')),
                ('status', models.CharField(choices=[('IN_STOCK', 'In Stock (उपलब्ध)'), ('SOLD', 'Sold (बिक्री भएको)'), ('RETURNED_DEFECTIVE', 'Returned Defective (खराब फिर्ता)'), ('TRANSFERRED', 'In Transit Transfer')], db_index=True, default='IN_STOCK', max_length=25)),
                ('purchase_reference', models.CharField(blank=True, max_length=50, null=True)),
                ('sold_invoice_reference', models.CharField(blank=True, max_length=50, null=True)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tracked_instances', to='branches.branch')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tracked_instances', to='inventory.product')),
            ],
            options={
                'verbose_name': 'IMEI / Serial Instance',
                'verbose_name_plural': 'IMEI / Serial Instances',
                'db_table': 'inv_item_instances',
            },
        ),
        migrations.CreateModel(
            name='BranchStock',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('quantity', models.DecimalField(db_index=True, decimal_places=3, default=Decimal('0.000'), max_digits=12, verbose_name='Quantity (Base Unit)')),
                ('low_stock_threshold', models.DecimalField(decimal_places=2, default=Decimal('5.00'), max_digits=10, verbose_name='Branch Alert Threshold')),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='branch_stocks', to='branches.branch')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='branch_stocks', to='inventory.product')),
            ],
            options={
                'verbose_name': 'Branch Stock Level',
                'verbose_name_plural': 'Branch Stock Levels',
                'db_table': 'inv_branch_stocks',
            },
        ),
        migrations.CreateModel(
            name='ProductSubCategory',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('name', models.CharField(max_length=100, verbose_name='Sub-Category Name')),
                ('code', models.CharField(blank=True, max_length=20, null=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subcategories', to='inventory.productcategory')),
            ],
            options={
                'verbose_name': 'Product Sub-Category',
                'verbose_name_plural': 'Product Sub-Categories',
                'db_table': 'inv_subcategories',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='product',
            name='subcategory',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='inventory.productsubcategory'),
        ),
        migrations.CreateModel(
            name='StockMovementLog',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('movement_type', models.CharField(choices=[('PURCHASE', 'Purchase Received (GRN)'), ('SALE', 'POS Billing Sale (बिक्री)'), ('SALE_RETURN', 'Customer Return (फिर्ता)'), ('TRANSFER_OUT', 'Branch Transfer Out'), ('TRANSFER_IN', 'Branch Transfer In'), ('ADJUSTMENT_ADD', 'Stock Count Correction (+)'), ('ADJUSTMENT_SUB', 'Damage / Lost / Expired (-)')], db_index=True, max_length=25)),
                ('quantity_delta', models.DecimalField(decimal_places=3, help_text='Signed change in base units (+ for additions, - for reductions)', max_digits=12)),
                ('previous_quantity', models.DecimalField(decimal_places=3, max_digits=12)),
                ('new_quantity', models.DecimalField(decimal_places=3, max_digits=12)),
                ('reference_document', models.CharField(blank=True, help_text='Bill No, Transfer No, GRN No', max_length=100, null=True)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movement_logs', to='branches.branch')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movement_logs', to='inventory.product')),
            ],
            options={
                'verbose_name': 'Stock Movement Log',
                'verbose_name_plural': 'Stock Movement Logs',
                'db_table': 'inv_stock_movement_logs',
                'ordering': ['-created_at'],
            },
        ),
    ]
