# Generated by Django 5.1.15 on 2026-08-20 15:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventory', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='stockmovementlog',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='unitconversion',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='unit_conversions', to='inventory.product'),
        ),
        migrations.AddField(
            model_name='product',
            name='base_unit',
            field=models.ForeignKey(help_text='The atomic unit in which warehouse stock is stored.', on_delete=django.db.models.deletion.PROTECT, related_name='base_products', to='inventory.unitofmeasurement'),
        ),
        migrations.AlterUniqueTogether(
            name='branchstock',
            unique_together={('branch', 'product')},
        ),
        migrations.AlterUniqueTogether(
            name='productsubcategory',
            unique_together={('category', 'name')},
        ),
        migrations.AlterUniqueTogether(
            name='unitconversion',
            unique_together={('product', 'unit_name')},
        ),
    ]
