# Generated by Django 5.1.15 on 2026-08-22 05:03

import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('branches', '0002_initial'),
        ('inventory', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='iteminstance',
            options={'ordering': ['-created_at'], 'verbose_name': 'IMEI / Serial Device Instance', 'verbose_name_plural': 'IMEI / Serial Device Instances'},
        ),
        migrations.AddField(
            model_name='branchstock',
            name='reserved_quantity',
            field=models.DecimalField(decimal_places=3, default=Decimal('0.000'), max_digits=12, verbose_name='Reserved Stock'),
        ),
        migrations.AddField(
            model_name='iteminstance',
            name='activation_status',
            field=models.CharField(choices=[('SEALED_INACTIVE', 'Sealed / Not Activated'), ('ACTIVATED', 'Carrier / Manufacturer Activated'), ('DEMO_UNIT', 'In-Store Live Demo Device')], default='SEALED_INACTIVE', max_length=25),
        ),
        migrations.AddField(
            model_name='iteminstance',
            name='condition',
            field=models.CharField(choices=[('BRAND_NEW', 'Brand New / Sealed Box'), ('OPEN_BOX', 'Open Box / Like New'), ('REFURBISHED', 'Official Refurbished (Certified)'), ('USED_GRADE_A', 'Pre-Owned Grade A (Flawless)'), ('USED_GRADE_B', 'Pre-Owned Grade B (Minor Scratches)'), ('USED_GRADE_C', 'Pre-Owned Grade C (Heavy Signs of Use)')], db_index=True, default='BRAND_NEW', max_length=25),
        ),
        migrations.AddField(
            model_name='iteminstance',
            name='customer_name',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='iteminstance',
            name='customer_phone',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='iteminstance',
            name='device_barcode',
            field=models.CharField(blank=True, db_index=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='iteminstance',
            name='device_uid',
            field=models.CharField(blank=True, db_index=True, max_length=60, null=True, unique=True, verbose_name='Device Unique ID'),
        ),
        migrations.AddField(
            model_name='iteminstance',
            name='landed_cost',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12),
        ),
        migrations.AddField(
            model_name='iteminstance',
            name='purchase_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='iteminstance',
            name='qr_code_payload',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='iteminstance',
            name='sale_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='iteminstance',
            name='supplier_name',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='iteminstance',
            name='warranty_end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='iteminstance',
            name='warranty_remarks',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='iteminstance',
            name='warranty_start_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='battery_capacity',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Battery Capacity (e.g. 5000 mAh)'),
        ),
        migrations.AddField(
            model_name='product',
            name='bin_location',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Specific Bin Location'),
        ),
        migrations.AddField(
            model_name='product',
            name='bluetooth_version',
            field=models.CharField(blank=True, default='Bluetooth 5.3', max_length=30, null=True, verbose_name='Bluetooth Version'),
        ),
        migrations.AddField(
            model_name='product',
            name='display_resolution',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Resolution (e.g. 1080 x 2340 pixels)'),
        ),
        migrations.AddField(
            model_name='product',
            name='display_size',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Display Size (e.g. 6.67 inches)'),
        ),
        migrations.AddField(
            model_name='product',
            name='display_type',
            field=models.CharField(blank=True, max_length=80, null=True, verbose_name='Display Type (e.g. Super AMOLED, 1.5K HDR10+)'),
        ),
        migrations.AddField(
            model_name='product',
            name='expandable_storage',
            field=models.BooleanField(default=False, verbose_name='MicroSD Slot Available'),
        ),
        migrations.AddField(
            model_name='product',
            name='face_unlock',
            field=models.BooleanField(default=True, verbose_name='Face Unlock Supported'),
        ),
        migrations.AddField(
            model_name='product',
            name='fast_charging',
            field=models.CharField(blank=True, max_length=60, null=True, verbose_name='Fast Charging (e.g. 45W Wired, 15W Wireless)'),
        ),
        migrations.AddField(
            model_name='product',
            name='fingerprint_sensor',
            field=models.CharField(blank=True, default='In-Display Optical', max_length=60, null=True, verbose_name='Fingerprint Sensor'),
        ),
        migrations.AddField(
            model_name='product',
            name='front_camera',
            field=models.CharField(blank=True, max_length=80, null=True, verbose_name='Front Camera (e.g. 32MP)'),
        ),
        migrations.AddField(
            model_name='product',
            name='gps_capabilities',
            field=models.CharField(blank=True, default='GPS, GLONASS, GALILEO, BDS', max_length=100, null=True, verbose_name='GPS / Positioning'),
        ),
        migrations.AddField(
            model_name='product',
            name='headphone_jack_35mm',
            field=models.BooleanField(default=False, verbose_name='3.5mm Headphone Jack'),
        ),
        migrations.AddField(
            model_name='product',
            name='internal_storage',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Storage (e.g. 64GB, 128GB, 256GB, 512GB, 1TB)'),
        ),
        migrations.AddField(
            model_name='product',
            name='inventory_tracking_type',
            field=models.CharField(choices=[('STANDARD', 'Standard Quantity / Batch Tracking'), ('IMEI', 'Unique IMEI Serialized Tracking (Smartphones/Tablets)'), ('SERIAL', 'Serial Number Tracking (Smartwatches/Laptops)')], default='STANDARD', max_length=20),
        ),
        migrations.AddField(
            model_name='product',
            name='max_memory_card',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Max MicroSD Capacity (e.g. Up to 1TB)'),
        ),
        migrations.AddField(
            model_name='product',
            name='model_name',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Model Name (e.g. Galaxy A55 5G)'),
        ),
        migrations.AddField(
            model_name='product',
            name='network_type',
            field=models.CharField(blank=True, choices=[('5G', '5G / LTE / 3G / 2G'), ('4G', '4G VoLTE / 3G / 2G'), ('3G', '3G / 2G Only'), ('WIFI_ONLY', 'Wi-Fi Only (Non-Cellular)')], default='5G', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='nfc_available',
            field=models.BooleanField(default=True, verbose_name='NFC Enabled'),
        ),
        migrations.AddField(
            model_name='product',
            name='operating_system',
            field=models.CharField(blank=True, max_length=80, null=True, verbose_name='OS & Version (e.g. Android 14 / One UI 6.1)'),
        ),
        migrations.AddField(
            model_name='product',
            name='processor_chipset',
            field=models.CharField(blank=True, max_length=120, null=True, verbose_name='Processor / Chipset (e.g. Snapdragon 8s Gen 3)'),
        ),
        migrations.AddField(
            model_name='product',
            name='rack_number',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Rack Number / Cabinet'),
        ),
        migrations.AddField(
            model_name='product',
            name='ram',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='RAM (e.g. 4GB, 6GB, 8GB, 12GB, 16GB)'),
        ),
        migrations.AddField(
            model_name='product',
            name='rear_camera',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Rear Camera Setup (e.g. 50MP OIS + 12MP Ultra-wide + 5MP)'),
        ),
        migrations.AddField(
            model_name='product',
            name='refresh_rate',
            field=models.CharField(blank=True, default='120Hz', max_length=30, null=True, verbose_name='Refresh Rate'),
        ),
        migrations.AddField(
            model_name='product',
            name='region_variant',
            field=models.CharField(blank=True, default='Global / Nepal Official', max_length=60, null=True, verbose_name='Region / Country Variant'),
        ),
        migrations.AddField(
            model_name='product',
            name='shelf_identifier',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Shelf / Drawer ID'),
        ),
        migrations.AddField(
            model_name='product',
            name='sim_configuration',
            field=models.CharField(blank=True, choices=[('DUAL_SIM', 'Dual Physical Nano-SIM'), ('SINGLE_SIM', 'Single Nano-SIM'), ('ESIM_DUAL', '1 Nano-SIM + 1 eSIM'), ('ESIM_ONLY', 'Dual eSIM Only')], default='DUAL_SIM', max_length=25, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='usb_port_type',
            field=models.CharField(blank=True, default='USB Type-C 2.0 (OTG)', max_length=40, null=True, verbose_name='USB Port Type'),
        ),
        migrations.AddField(
            model_name='product',
            name='variant_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Variant Tag (e.g. 8GB/256GB Black)'),
        ),
        migrations.AddField(
            model_name='product',
            name='warranty_provider',
            field=models.CharField(blank=True, default='Authorized National Distributor', max_length=120, null=True, verbose_name='Warranty Provider'),
        ),
        migrations.AddField(
            model_name='product',
            name='wifi_spec',
            field=models.CharField(blank=True, default='Wi-Fi 6 (802.11ax)', max_length=60, null=True, verbose_name='Wi-Fi Standard'),
        ),
        migrations.AddField(
            model_name='stockmovementlog',
            name='imei_or_serial_number',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='branchstock',
            name='low_stock_threshold',
            field=models.DecimalField(decimal_places=2, default=Decimal('5.00'), max_digits=10),
        ),
        migrations.AlterField(
            model_name='branchstock',
            name='quantity',
            field=models.DecimalField(db_index=True, decimal_places=3, default=Decimal('0.000'), max_digits=12),
        ),
        migrations.AlterField(
            model_name='iteminstance',
            name='imei_1',
            field=models.CharField(blank=True, db_index=True, max_length=35, null=True, unique=True, verbose_name='Primary IMEI 1'),
        ),
        migrations.AlterField(
            model_name='iteminstance',
            name='imei_2',
            field=models.CharField(blank=True, db_index=True, max_length=35, null=True, verbose_name='Secondary IMEI 2 / eSIM ID'),
        ),
        migrations.AlterField(
            model_name='iteminstance',
            name='purchase_reference',
            field=models.CharField(blank=True, help_text='GRN Inward Voucher Number', max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='iteminstance',
            name='serial_number',
            field=models.CharField(blank=True, db_index=True, max_length=60, null=True, unique=True, verbose_name='Serial Number'),
        ),
        migrations.AlterField(
            model_name='iteminstance',
            name='sold_invoice_reference',
            field=models.CharField(blank=True, help_text='Estimate/Sales Slip No.', max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='iteminstance',
            name='status',
            field=models.CharField(choices=[('IN_STOCK', 'In Stock (उपलब्ध)'), ('RESERVED', 'Reserved in Cart / Booking'), ('SOLD', 'Sold (बिक्री भएको)'), ('UNDER_SERVICE', 'Under Service / Repair'), ('RETURNED_DEFECTIVE', 'Returned Defective (खराब फिर्ता)'), ('TRANSFERRED', 'In Transit Transfer')], db_index=True, default='IN_STOCK', max_length=25),
        ),
        migrations.AlterField(
            model_name='product',
            name='base_unit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='base_products', to='inventory.unitofmeasurement'),
        ),
        migrations.AlterField(
            model_name='product',
            name='color_variant',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Color / Finish'),
        ),
        migrations.AlterField(
            model_name='product',
            name='is_vat_applicable',
            field=models.BooleanField(default=True, verbose_name='VAT Applicable (13%)'),
        ),
        migrations.AlterField(
            model_name='product',
            name='model_number',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Model Number (e.g. SM-A556E/DS)'),
        ),
        migrations.AlterField(
            model_name='product',
            name='reorder_level',
            field=models.DecimalField(decimal_places=2, default=Decimal('5.00'), max_digits=10, verbose_name='Reorder Alert Level'),
        ),
        migrations.AlterField(
            model_name='product',
            name='requires_imei_tracking',
            field=models.BooleanField(default=False, help_text='Strict 15-digit unique serial for cellular devices.'),
        ),
        migrations.AlterField(
            model_name='product',
            name='requires_serial_tracking',
            field=models.BooleanField(default=False, help_text='Unique serial validation for watches/accessories.'),
        ),
        migrations.AlterField(
            model_name='product',
            name='size_dimension',
            field=models.CharField(blank=True, max_length=60, null=True, verbose_name='Dimensions / Frame Size'),
        ),
        migrations.AlterField(
            model_name='product',
            name='warranty_months',
            field=models.PositiveIntegerField(default=12, verbose_name='Official Warranty (Months)'),
        ),
        migrations.AlterField(
            model_name='stockmovementlog',
            name='movement_type',
            field=models.CharField(choices=[('PURCHASE', 'Purchase Received (GRN Inward)'), ('SALE', 'POS Billing Sale (बिक्री)'), ('SALE_RETURN', 'Customer Return (फिर्ता)'), ('TRANSFER_OUT', 'Branch Transfer Out'), ('TRANSFER_IN', 'Branch Transfer In'), ('ADJUSTMENT_ADD', 'Stock Count Correction (+)'), ('ADJUSTMENT_SUB', 'Damage / Lost / Expired (-)'), ('SERVICE_INTAKE', 'Repair Service Intake'), ('SERVICE_RETURN', 'Repair Service Dispatched')], db_index=True, max_length=25),
        ),
        migrations.AlterField(
            model_name='stockmovementlog',
            name='quantity_delta',
            field=models.DecimalField(decimal_places=3, max_digits=12),
        ),
        migrations.AlterField(
            model_name='stockmovementlog',
            name='reference_document',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='unitconversion',
            name='barcode',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='unitconversion',
            name='conversion_factor',
            field=models.DecimalField(decimal_places=3, help_text='Multiplier to smallest base unit', max_digits=10),
        ),
        migrations.AlterField(
            model_name='unitconversion',
            name='selling_price_per_unit',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='unitconversion',
            name='unit_name',
            field=models.CharField(max_length=50, verbose_name='Packaging Unit Name (e.g. Box, Pack, Carton)'),
        ),
        migrations.CreateModel(
            name='DeviceServiceTicket',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('ticket_number', models.CharField(db_index=True, max_length=50, unique=True, verbose_name='Service Ticket No.')),
                ('imei_or_serial', models.CharField(db_index=True, max_length=50, verbose_name='Device IMEI / Serial')),
                ('customer_name', models.CharField(max_length=150, verbose_name='Customer Name')),
                ('customer_phone', models.CharField(max_length=30, verbose_name='Customer Phone')),
                ('complaint_description', models.TextField(verbose_name='Reported Fault / Problem')),
                ('technician_diagnostic_notes', models.TextField(blank=True, null=True, verbose_name='Technician Diagnostic Findings')),
                ('parts_replaced', models.TextField(blank=True, null=True, verbose_name='Parts / Components Replaced')),
                ('service_cost', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='Service / Labor Cost (NPR)')),
                ('parts_cost', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='Spare Parts Cost (NPR)')),
                ('total_service_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('service_center_name', models.CharField(blank=True, default='In-House Repair Lab', max_length=150, null=True, verbose_name='Service Center / Lab')),
                ('service_status', models.CharField(choices=[('RECEIVED', 'Received / Diagnostics Pending'), ('IN_REPAIR', 'In-Repair by Technician'), ('WAITING_PARTS', 'Waiting for Replacement Spare Parts'), ('COMPLETED', 'Repair Completed & Quality Tested'), ('DELIVERED', 'Delivered to Customer'), ('UNREPAIRABLE', 'Unrepairable / RTV (Returned to Vendor)')], db_index=True, default='RECEIVED', max_length=25)),
                ('delivered_date', models.DateTimeField(blank=True, null=True)),
                ('service_remarks', models.TextField(blank=True, null=True)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='service_tickets', to='branches.branch')),
                ('item_instance', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='service_records', to='inventory.iteminstance')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='service_tickets', to='inventory.product')),
                ('technician', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_service_repairs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Service & Repair Ticket',
                'verbose_name_plural': 'Service & Repair Tickets',
                'db_table': 'inv_device_service_tickets',
                'ordering': ['-created_at'],
            },
        ),
    ]
