# Generated by Django 5.1.15 on 2026-08-22 07:07

import django.db.models.deletion
import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('branches', '0002_initial'),
        ('inventory', '0003_alter_iteminstance_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='iteminstance',
            name='batch_reference',
            field=models.CharField(blank=True, help_text='Associated Batch Identifier', max_length=60, null=True),
        ),
        migrations.AddField(
            model_name='iteminstance',
            name='sold_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Final Selling Price (NPR)'),
        ),
        migrations.AlterField(
            model_name='iteminstance',
            name='landed_cost',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='Unit Landed Acquisition Cost (NPR)'),
        ),
        migrations.AlterField(
            model_name='iteminstance',
            name='purchase_date',
            field=models.DateField(blank=True, db_index=True, null=True, verbose_name='Purchase Inward Date'),
        ),
        migrations.AlterField(
            model_name='product',
            name='battery_capacity',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Battery Capacity (e.g. 6000 mAh)'),
        ),
        migrations.AlterField(
            model_name='product',
            name='bluetooth_version',
            field=models.CharField(blank=True, default='Bluetooth 5.0', max_length=30, null=True, verbose_name='Bluetooth Version'),
        ),
        migrations.AlterField(
            model_name='product',
            name='display_resolution',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Resolution'),
        ),
        migrations.AlterField(
            model_name='product',
            name='display_size',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Display Size'),
        ),
        migrations.AlterField(
            model_name='product',
            name='display_type',
            field=models.CharField(blank=True, max_length=80, null=True, verbose_name='Display Type'),
        ),
        migrations.AlterField(
            model_name='product',
            name='expandable_storage',
            field=models.BooleanField(default=True, verbose_name='MicroSD Slot Available'),
        ),
        migrations.AlterField(
            model_name='product',
            name='fast_charging',
            field=models.CharField(blank=True, max_length=60, null=True, verbose_name='Fast Charging (e.g. 44W FlashCharge)'),
        ),
        migrations.AlterField(
            model_name='product',
            name='fingerprint_sensor',
            field=models.CharField(blank=True, default='Side-Mounted', max_length=60, null=True, verbose_name='Fingerprint Sensor'),
        ),
        migrations.AlterField(
            model_name='product',
            name='front_camera',
            field=models.CharField(blank=True, max_length=80, null=True, verbose_name='Front Camera'),
        ),
        migrations.AlterField(
            model_name='product',
            name='headphone_jack_35mm',
            field=models.BooleanField(default=True, verbose_name='3.5mm Headphone Jack'),
        ),
        migrations.AlterField(
            model_name='product',
            name='internal_storage',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Storage (e.g. 64GB, 128GB, 256GB)'),
        ),
        migrations.AlterField(
            model_name='product',
            name='max_memory_card',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Max MicroSD Capacity'),
        ),
        migrations.AlterField(
            model_name='product',
            name='model_name',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Model Name (e.g. Vivo Y28)'),
        ),
        migrations.AlterField(
            model_name='product',
            name='model_number',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Model Number (e.g. V2352)'),
        ),
        migrations.AlterField(
            model_name='product',
            name='nfc_available',
            field=models.BooleanField(default=False, verbose_name='NFC Enabled'),
        ),
        migrations.AlterField(
            model_name='product',
            name='operating_system',
            field=models.CharField(blank=True, max_length=80, null=True, verbose_name='OS & Version'),
        ),
        migrations.AlterField(
            model_name='product',
            name='processor_chipset',
            field=models.CharField(blank=True, max_length=120, null=True, verbose_name='Processor / Chipset'),
        ),
        migrations.AlterField(
            model_name='product',
            name='purchase_price',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='Latest Cost Price (NPR)'),
        ),
        migrations.AlterField(
            model_name='product',
            name='ram',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='RAM (e.g. 4GB, 6GB, 8GB, 12GB)'),
        ),
        migrations.AlterField(
            model_name='product',
            name='rear_camera',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Rear Camera Setup'),
        ),
        migrations.AlterField(
            model_name='product',
            name='refresh_rate',
            field=models.CharField(blank=True, default='90Hz', max_length=30, null=True, verbose_name='Refresh Rate'),
        ),
        migrations.AlterField(
            model_name='product',
            name='selling_price',
            field=models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Latest Selling Price / MRP (NPR)'),
        ),
        migrations.AlterField(
            model_name='product',
            name='variant_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Variant Tag (e.g. 8GB/256GB Gleaming Orange)'),
        ),
        migrations.AlterField(
            model_name='product',
            name='wifi_spec',
            field=models.CharField(blank=True, default='Wi-Fi 5 (802.11ac)', max_length=60, null=True, verbose_name='Wi-Fi Standard'),
        ),
        migrations.CreateModel(
            name='ProductBatch',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('batch_number', models.CharField(db_index=True, max_length=60, verbose_name='Batch Number / Ref')),
                ('purchase_date', models.DateField(db_index=True, verbose_name='Intake Date')),
                ('cost_price', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Batch Cost Price (NPR)')),
                ('selling_price', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Batch Target MRP (NPR)')),
                ('quantity_received', models.DecimalField(decimal_places=3, default=Decimal('0.000'), max_digits=12)),
                ('quantity_remaining', models.DecimalField(db_index=True, decimal_places=3, default=Decimal('0.000'), max_digits=12)),
                ('is_depleted', models.BooleanField(db_index=True, default=False)),
                ('supplier_name', models.CharField(blank=True, max_length=150, null=True)),
                ('grn_reference', models.CharField(blank=True, max_length=60, null=True)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_batches', to='branches.branch')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='batches', to='inventory.product')),
            ],
            options={
                'verbose_name': 'Product Batch (FIFO / Date Tracking)',
                'verbose_name_plural': 'Product Batches (FIFO / Date Tracking)',
                'db_table': 'inv_product_batches',
                'ordering': ['purchase_date', 'created_at'],
            },
        ),
    ]
