# Generated by Django 5.1.15 on 2026-08-22 13:38

import datetime
import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('branches', '0002_initial'),
        ('inventory', '0004_iteminstance_batch_reference_iteminstance_sold_price_and_more'),
        ('purchases', '0004_grnitem_new_selling_price_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='deviceserviceticket',
            name='claim_type',
            field=models.CharField(choices=[('WARRANTY_FREE', 'Free In-Warranty Claim (नि:शुल्क वारेन्टी दावी)'), ('OUT_OF_WARRANTY_PAID', 'Paid Service / Out of Warranty (सशुल्क मर्मत)'), ('GOODWILL_DISCOUNT', 'Goodwill / Commercial Concession')], db_index=True, default='OUT_OF_WARRANTY_PAID', max_length=30),
        ),
        migrations.AddField(
            model_name='deviceserviceticket',
            name='claimed_component',
            field=models.CharField(choices=[('DEVICE', 'Main Handset / Motherboard (ह्यान्डसेट / मदरबोर्ड)'), ('SCREEN', 'Screen / Display Panel (स्क्रिन / डिस्प्ले)'), ('BATTERY', 'Internal Battery (ब्याट्री)'), ('CHARGER', 'Charging Adapter & Cable (चार्जर र केबल)'), ('CAMERA', 'Camera Module (क्यामेरा मोड्युल)'), ('SPEAKER', 'Speaker / Receiver (स्पीकर)'), ('ACCESSORY', 'In-Box Accessory / Earphones'), ('OTHER', 'Other Specific Component')], default='DEVICE', max_length=30, verbose_name='Claimed Defective Component'),
        ),
        migrations.AddField(
            model_name='deviceserviceticket',
            name='warranty_status_at_intake',
            field=models.CharField(choices=[('IN_WARRANTY', 'Eligible Under Official Warranty'), ('EXPIRED', 'Expired Coverage Date'), ('VOID_PHYSICAL_DAMAGE', 'Voided: Physical Broken Damage'), ('VOID_LIQUID_DAMAGE', 'Voided: Liquid / Water Ingress'), ('VOID_UNAUTHORIZED_OPEN', 'Voided: Third-Party Seal Broken'), ('NOT_APPLICABLE', 'Not Applicable / Accessory')], default='IN_WARRANTY', max_length=30),
        ),
        migrations.AlterField(
            model_name='deviceserviceticket',
            name='parts_replaced',
            field=models.TextField(blank=True, null=True, verbose_name='Summary of Replaced Parts (Legacy Note)'),
        ),
        migrations.AlterField(
            model_name='deviceserviceticket',
            name='service_status',
            field=models.CharField(choices=[('RECEIVED', 'Received / Diagnostics Pending'), ('IN_REPAIR', 'In-Repair by Technician'), ('WAITING_PARTS', 'Waiting for Replacement Spare Parts'), ('COMPLETED', 'Repair Completed & Quality Tested'), ('DELIVERED', 'Delivered to Customer'), ('UNREPAIRABLE', 'Unrepairable / Returned to Vendor'), ('CANCELLED', 'Service Cancelled')], db_index=True, default='RECEIVED', max_length=25),
        ),
        migrations.AlterField(
            model_name='iteminstance',
            name='sale_date',
            field=models.DateField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='warranty_months',
            field=models.PositiveIntegerField(default=12, verbose_name='Overall Device Warranty (Months)'),
        ),
        migrations.AlterField(
            model_name='stockmovementlog',
            name='movement_type',
            field=models.CharField(choices=[('PURCHASE', 'Purchase Received (GRN Inward)'), ('SALE', 'POS Billing Sale (बिक्री)'), ('SALE_RETURN', 'Customer Return (फिर्ता)'), ('TRANSFER_OUT', 'Branch Transfer Out'), ('TRANSFER_IN', 'Branch Transfer In'), ('ADJUSTMENT_ADD', 'Stock Count Correction (+)'), ('ADJUSTMENT_SUB', 'Damage / Lost / Expired (-)'), ('SERVICE_INTAKE', 'Repair Service Intake'), ('SERVICE_REPLACED_PART_DEDUCT', 'Service Spare Part Installed (-)'), ('SERVICE_RETURN', 'Repair Service Dispatched'), ('RMA_VENDOR_DISPATCH', 'Defective Part Dispatched to Vendor (-)'), ('RMA_VENDOR_REPLACEMENT_IN', 'Replacement Received from Vendor (+)')], db_index=True, max_length=35),
        ),
        migrations.CreateModel(
            name='DeviceComponentWarranty',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('component_type', models.CharField(choices=[('DEVICE', 'Main Handset / Motherboard (ह्यान्डसेट / मदरबोर्ड)'), ('SCREEN', 'Screen / Display Panel (स्क्रिन / डिस्प्ले)'), ('BATTERY', 'Internal Battery (ब्याट्री)'), ('CHARGER', 'Charging Adapter & Cable (चार्जर र केबल)'), ('CAMERA', 'Camera Module (क्यामेरा मोड्युल)'), ('SPEAKER', 'Speaker / Receiver (स्पीकर)'), ('ACCESSORY', 'In-Box Accessory / Earphones'), ('OTHER', 'Other Specific Component')], db_index=True, default='DEVICE', max_length=30)),
                ('component_name', models.CharField(max_length=120)),
                ('warranty_months', models.PositiveIntegerField(default=6)),
                ('warranty_start_date', models.DateField(db_index=True)),
                ('warranty_expiry_date', models.DateField(db_index=True)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active / In-Warranty (सक्रिय वारेन्टी)'), ('CLAIMED', 'Warranty Claimed & Replaced (दावी गरिएको)'), ('EXPIRED', 'Warranty Expired (म्याद सकिएको)'), ('VOID', 'Void / Ineligible (भौतिक/पानी क्षति)')], db_index=True, default='ACTIVE', max_length=20)),
                ('claim_count', models.PositiveIntegerField(default=0)),
                ('void_reason', models.CharField(blank=True, max_length=255, null=True)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('item_instance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='component_warranties', to='inventory.iteminstance')),
            ],
            options={
                'verbose_name': 'Active Device Component Warranty',
                'verbose_name_plural': 'Active Device Component Warranties',
                'db_table': 'inv_device_component_warranties',
                'ordering': ['item_instance', 'warranty_expiry_date'],
            },
        ),
        migrations.AddField(
            model_name='deviceserviceticket',
            name='component_warranty_record',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='service_tickets', to='inventory.devicecomponentwarranty'),
        ),
        migrations.CreateModel(
            name='ServiceReplacedPart',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('quantity', models.DecimalField(decimal_places=3, default=Decimal('1.000'), max_digits=10)),
                ('old_part_serial_number', models.CharField(blank=True, max_length=80, null=True, verbose_name='Old Defective Part S/N')),
                ('new_part_serial_number', models.CharField(blank=True, max_length=80, null=True, verbose_name='New Replacement Part S/N')),
                ('new_part_batch_number', models.CharField(blank=True, max_length=80, null=True, verbose_name='Source Batch / GRN Ref')),
                ('cost_price', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='Inventory Landed Cost (NPR)')),
                ('customer_charge', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='Billed to Customer (0.00 if Free In-Warranty)')),
                ('replacement_warranty_months', models.PositiveIntegerField(default=6, verbose_name='New Part Warranty (Months)')),
                ('replacement_warranty_start_date', models.DateField(default=datetime.date.today)),
                ('replacement_warranty_end_date', models.DateField(blank=True, null=True)),
                ('defective_part_status', models.CharField(choices=[('STORED_IN_SHOP', 'Stored Defective in Shop Quarantine'), ('QUEUED_FOR_RMA', 'Queued for Vendor RMA Claim'), ('DISPATCHED_TO_VENDOR', 'Dispatched to Manufacturer/Distributor'), ('CREDITED_BY_VENDOR', 'Reimbursed / Credited by Vendor'), ('REPLACED_BY_VENDOR', 'Replaced Stock Received from Vendor'), ('SCRAPPED', 'Scrapped / Recycled Locally')], db_index=True, default='STORED_IN_SHOP', max_length=30)),
                ('technician_notes', models.CharField(blank=True, max_length=255, null=True)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='service_part_deductions', to='branches.branch')),
                ('spare_part_product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='service_part_usages', to='inventory.product', verbose_name='Installed Replacement Spare Part')),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='replaced_part_items', to='inventory.deviceserviceticket')),
            ],
            options={
                'verbose_name': 'Service Replaced Spare Part',
                'verbose_name_plural': 'Service Replaced Spare Parts',
                'db_table': 'inv_service_replaced_parts',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='VendorRMAClaim',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('rma_number', models.CharField(db_index=True, max_length=50, unique=True, verbose_name='RMA Claim Number')),
                ('status', models.CharField(choices=[('DRAFT', 'Draft Challan / Gathering Defective Parts'), ('DISPATCHED_TO_VENDOR', 'Dispatched to Distributor Lab (पठाइएको)'), ('PARTIALLY_SETTLED', 'Partially Replaced / Credited'), ('COMPLETED', 'Fully Resolved & Closed (सम्पन्न)'), ('REJECTED', 'Rejected by Distributor (अस्वीकृत)')], db_index=True, default='DRAFT', max_length=30)),
                ('dispatch_date', models.DateField(blank=True, null=True, verbose_name='Dispatch Date (AD)')),
                ('distributor_tracking_ref', models.CharField(blank=True, max_length=100, null=True, verbose_name='Courier / Challan Ref No.')),
                ('distributor_service_center', models.CharField(blank=True, default='Authorized National Service Center', max_length=150, null=True)),
                ('resolution_date', models.DateField(blank=True, null=True)),
                ('total_claimed_parts_count', models.PositiveIntegerField(default=0)),
                ('total_credit_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('resolution_notes', models.TextField(blank=True, null=True)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='vendor_rma_claims', to='branches.branch')),
                ('dispatched_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dispatched_rmas', to=settings.AUTH_USER_MODEL)),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resolved_rmas', to=settings.AUTH_USER_MODEL)),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='vendor_rma_claims', to='purchases.supplier')),
            ],
            options={
                'verbose_name': 'Vendor RMA & Warranty Claim',
                'verbose_name_plural': 'Vendor RMA & Warranty Claims',
                'db_table': 'inv_vendor_rma_claims',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='VendorRMAClaimItem',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('defective_serial_or_imei', models.CharField(max_length=80, verbose_name='Defective Part Serial / IMEI')),
                ('defect_description', models.TextField(verbose_name='Defect Reason Reported to Vendor')),
                ('resolution', models.CharField(choices=[('PENDING', 'Pending Distributor Inspection'), ('REPLACED_WITH_NEW_PART', 'Replaced with New Factory Spare Part'), ('CREDIT_NOTE_ISSUED', 'Credit Note / Purchase Price Reimbursed'), ('RETURNED_UNREPAIRED', 'Rejected / Returned Unrepaired (Warranty Void)')], db_index=True, default='PENDING', max_length=30)),
                ('replacement_batch_or_serial', models.CharField(blank=True, max_length=80, null=True, verbose_name='New Received Replacement S/N')),
                ('credit_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='Credit Note Amount (NPR)')),
                ('vendor_notes', models.CharField(blank=True, max_length=255, null=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='vendor_rma_items', to='inventory.product')),
                ('rma_claim', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='claimed_items', to='inventory.vendorrmaclaim')),
                ('service_replaced_part', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vendor_rma_links', to='inventory.servicereplacedpart')),
            ],
            options={
                'verbose_name': 'Vendor RMA Claim Item',
                'verbose_name_plural': 'Vendor RMA Claim Items',
                'db_table': 'inv_vendor_rma_claim_items',
            },
        ),
        migrations.CreateModel(
            name='ProductComponentWarrantyRule',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('component_type', models.CharField(choices=[('DEVICE', 'Main Handset / Motherboard (ह्यान्डसेट / मदरबोर्ड)'), ('SCREEN', 'Screen / Display Panel (स्क्रिन / डिस्प्ले)'), ('BATTERY', 'Internal Battery (ब्याट्री)'), ('CHARGER', 'Charging Adapter & Cable (चार्जर र केबल)'), ('CAMERA', 'Camera Module (क्यामेरा मोड्युल)'), ('SPEAKER', 'Speaker / Receiver (स्पीकर)'), ('ACCESSORY', 'In-Box Accessory / Earphones'), ('OTHER', 'Other Specific Component')], db_index=True, default='DEVICE', max_length=30)),
                ('component_name', models.CharField(max_length=120, verbose_name='Component Name / Description')),
                ('warranty_months', models.PositiveIntegerField(default=6, verbose_name='Warranty Duration (Months)')),
                ('coverage_conditions', models.CharField(blank=True, default='Covers manufacturing defects only. Void if liquid or physical damage found.', max_length=255, null=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='component_warranty_rules', to='inventory.product')),
            ],
            options={
                'verbose_name': 'Product Component Warranty Rule',
                'verbose_name_plural': 'Product Component Warranty Rules',
                'db_table': 'inv_product_component_warranty_rules',
                'ordering': ['product', 'component_type'],
                'unique_together': {('product', 'component_type', 'component_name')},
            },
        ),
    ]
