# Generated by Django 5.1.15 on 2026-08-23 03:34

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_deviceserviceticket_claim_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servicereplacedpart',
            name='ticket',
        ),
        migrations.RemoveField(
            model_name='servicereplacedpart',
            name='branch',
        ),
        migrations.RemoveField(
            model_name='servicereplacedpart',
            name='spare_part_product',
        ),
        migrations.RemoveField(
            model_name='vendorrmaclaimitem',
            name='service_replaced_part',
        ),
        migrations.AlterModelOptions(
            name='productbatch',
            options={'ordering': ['purchase_date', 'created_at'], 'verbose_name': 'Product Batch (FIFO)', 'verbose_name_plural': 'Product Batches (FIFO)'},
        ),
        migrations.RemoveField(
            model_name='iteminstance',
            name='qr_code_payload',
        ),
        migrations.AddField(
            model_name='branchstock',
            name='quarantined_defective_quantity',
            field=models.DecimalField(db_index=True, decimal_places=3, default=Decimal('0.000'), max_digits=12, verbose_name='Defective Quarantine Stock (Waiting RMA)'),
        ),
        migrations.AddField(
            model_name='product',
            name='is_spare_part',
            field=models.BooleanField(db_index=True, default=False, verbose_name='Is Repair Spare Part (Screen/Battery/PCB)'),
        ),
        migrations.AlterField(
            model_name='branchstock',
            name='quantity',
            field=models.DecimalField(db_index=True, decimal_places=3, default=Decimal('0.000'), max_digits=12, verbose_name='Sellable Stock'),
        ),
        migrations.AlterField(
            model_name='iteminstance',
            name='batch_reference',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='iteminstance',
            name='device_uid',
            field=models.CharField(blank=True, db_index=True, max_length=60, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='iteminstance',
            name='imei_1',
            field=models.CharField(blank=True, db_index=True, max_length=35, null=True, unique=True, verbose_name='IMEI 1'),
        ),
        migrations.AlterField(
            model_name='iteminstance',
            name='imei_2',
            field=models.CharField(blank=True, db_index=True, max_length=35, null=True, verbose_name='IMEI 2'),
        ),
        migrations.AlterField(
            model_name='iteminstance',
            name='landed_cost',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12),
        ),
        migrations.AlterField(
            model_name='iteminstance',
            name='purchase_date',
            field=models.DateField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='iteminstance',
            name='purchase_reference',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='iteminstance',
            name='serial_number',
            field=models.CharField(blank=True, db_index=True, max_length=60, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='iteminstance',
            name='sold_invoice_reference',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='iteminstance',
            name='sold_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='iteminstance',
            name='status',
            field=models.CharField(choices=[('IN_STOCK', 'In Stock (उपलब्ध)'), ('RESERVED', 'Reserved in Cart / Booking'), ('SOLD', 'Sold (बिक्री भएको)'), ('UNDER_SERVICE', 'Under Service / Repair (मर्मतमा रहेको)'), ('RETURNED_DEFECTIVE', 'Returned Defective (खराब फिर्ता)'), ('TRANSFERRED', 'In Transit Transfer')], db_index=True, default='IN_STOCK', max_length=25),
        ),
        migrations.AlterField(
            model_name='product',
            name='battery_capacity',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='bin_location',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Bin Location'),
        ),
        migrations.AlterField(
            model_name='product',
            name='bluetooth_version',
            field=models.CharField(blank=True, default='Bluetooth 5.0', max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='color_variant',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Color'),
        ),
        migrations.AlterField(
            model_name='product',
            name='display_resolution',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='display_size',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='display_type',
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='expandable_storage',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='face_unlock',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='fast_charging',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='fingerprint_sensor',
            field=models.CharField(blank=True, default='Side-Mounted', max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='front_camera',
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='gps_capabilities',
            field=models.CharField(blank=True, default='GPS, GLONASS, GALILEO, BDS', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='headphone_jack_35mm',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='internal_storage',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Storage'),
        ),
        migrations.AlterField(
            model_name='product',
            name='is_vat_applicable',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='max_discount_percent',
            field=models.DecimalField(decimal_places=2, default=Decimal('10.00'), max_digits=5),
        ),
        migrations.AlterField(
            model_name='product',
            name='max_memory_card',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='model_name',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Model Name'),
        ),
        migrations.AlterField(
            model_name='product',
            name='model_number',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Model Number'),
        ),
        migrations.AlterField(
            model_name='product',
            name='nfc_available',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='product',
            name='operating_system',
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='processor_chipset',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='purchase_price',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='Cost Price (NPR)'),
        ),
        migrations.AlterField(
            model_name='product',
            name='rack_number',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Rack Number'),
        ),
        migrations.AlterField(
            model_name='product',
            name='ram',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='RAM'),
        ),
        migrations.AlterField(
            model_name='product',
            name='rear_camera',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='refresh_rate',
            field=models.CharField(blank=True, default='90Hz', max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='region_variant',
            field=models.CharField(blank=True, default='Global / Nepal Official', max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='reorder_level',
            field=models.DecimalField(decimal_places=2, default=Decimal('5.00'), max_digits=10),
        ),
        migrations.AlterField(
            model_name='product',
            name='requires_imei_tracking',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='product',
            name='requires_serial_tracking',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='product',
            name='selling_price',
            field=models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Selling Price / MRP (NPR)'),
        ),
        migrations.AlterField(
            model_name='product',
            name='shelf_identifier',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Shelf ID'),
        ),
        migrations.AlterField(
            model_name='product',
            name='size_dimension',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='usb_port_type',
            field=models.CharField(blank=True, default='USB Type-C 2.0 (OTG)', max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='variant_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Variant Tag'),
        ),
        migrations.AlterField(
            model_name='product',
            name='warranty_months',
            field=models.PositiveIntegerField(default=12, verbose_name='Warranty (Months)'),
        ),
        migrations.AlterField(
            model_name='product',
            name='warranty_provider',
            field=models.CharField(blank=True, default='Authorized National Distributor', max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='wholesale_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='wifi_spec',
            field=models.CharField(blank=True, default='Wi-Fi 5 (802.11ac)', max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='productbatch',
            name='batch_number',
            field=models.CharField(db_index=True, max_length=60, verbose_name='Batch Number'),
        ),
        migrations.AlterField(
            model_name='productbatch',
            name='cost_price',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
        migrations.AlterField(
            model_name='productbatch',
            name='purchase_date',
            field=models.DateField(db_index=True),
        ),
        migrations.AlterField(
            model_name='productbatch',
            name='selling_price',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
        migrations.AlterField(
            model_name='productcomponentwarrantyrule',
            name='component_name',
            field=models.CharField(max_length=120, verbose_name='Component Description'),
        ),
        migrations.AlterField(
            model_name='productcomponentwarrantyrule',
            name='warranty_months',
            field=models.PositiveIntegerField(default=6, verbose_name='Warranty Months'),
        ),
        migrations.AlterField(
            model_name='stockmovementlog',
            name='movement_type',
            field=models.CharField(choices=[('PURCHASE', 'Purchase Received (GRN Inward)'), ('SALE', 'POS Billing Sale (बिक्री)'), ('SALE_RETURN', 'Customer Return (फिर्ता)'), ('TRANSFER_OUT', 'Branch Transfer Out'), ('TRANSFER_IN', 'Branch Transfer In'), ('ADJUSTMENT_ADD', 'Stock Count Correction (+)'), ('ADJUSTMENT_SUB', 'Damage / Lost / Expired (-)'), ('SERVICE_INTAKE', 'Repair Service Intake'), ('SERVICE_REPLACED_PART_DEDUCT', 'Service Spare Part Installed (-)'), ('SERVICE_DEFECTIVE_QUARANTINE', 'Defective Part Moved to Quarantine (+)'), ('RMA_VENDOR_DISPATCH', 'Defective Part Dispatched to Vendor (-)'), ('RMA_VENDOR_REPLACEMENT_IN', 'Replacement Received from Vendor (+)')], db_index=True, max_length=35),
        ),
        migrations.AlterField(
            model_name='unitconversion',
            name='conversion_factor',
            field=models.DecimalField(decimal_places=3, max_digits=10),
        ),
        migrations.AlterField(
            model_name='unitconversion',
            name='unit_name',
            field=models.CharField(max_length=50, verbose_name='Packaging Unit Name'),
        ),
        migrations.AlterField(
            model_name='vendorrmaclaim',
            name='dispatch_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='vendorrmaclaim',
            name='distributor_tracking_ref',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='vendorrmaclaim',
            name='rma_number',
            field=models.CharField(db_index=True, max_length=50, unique=True, verbose_name='RMA Claim No.'),
        ),
        migrations.AlterField(
            model_name='vendorrmaclaimitem',
            name='credit_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12),
        ),
        migrations.AlterField(
            model_name='vendorrmaclaimitem',
            name='defect_description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='vendorrmaclaimitem',
            name='defective_serial_or_imei',
            field=models.CharField(max_length=80),
        ),
        migrations.AlterField(
            model_name='vendorrmaclaimitem',
            name='replacement_batch_or_serial',
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
        migrations.DeleteModel(
            name='DeviceServiceTicket',
        ),
        migrations.DeleteModel(
            name='ServiceReplacedPart',
        ),
    ]
