# Generated by Django 5.1.15 on 2026-08-23 06:18

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0006_remove_servicereplacedpart_ticket_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='tax_pricing_type',
            field=models.CharField(choices=[('INCLUSIVE', 'Tax-Inclusive (Price includes 13% VAT / कर सहित)'), ('EXCLUSIVE', 'Tax-Exclusive (13% VAT added on top / कर बाहेक)'), ('EXEMPT', 'Tax-Exempt / Non-VAT (0% Tax / कर नलाग्ने)')], db_index=True, default='INCLUSIVE', help_text='Specifies whether the rate includes 13% VAT, adds 13% on top, or is 0% tax exempt.', max_length=20, verbose_name='Tax Pricing Type'),
        ),
        migrations.AlterField(
            model_name='product',
            name='is_vat_applicable',
            field=models.BooleanField(default=True, verbose_name='Is VAT Applicable'),
        ),
        migrations.AlterField(
            model_name='product',
            name='vat_rate',
            field=models.DecimalField(decimal_places=2, default=Decimal('13.00'), max_digits=5, verbose_name='VAT Rate (%)'),
        ),
    ]
