# Generated by Django 5.1.15 on 2026-08-23 07:41

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0007_product_tax_pricing_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='is_spare_part',
            field=models.BooleanField(db_index=True, default=False, verbose_name='Is Repair Spare Part'),
        ),
        migrations.AlterField(
            model_name='product',
            name='is_vat_applicable',
            field=models.BooleanField(default=False, verbose_name='Is Tax Applicable'),
        ),
        migrations.AlterField(
            model_name='product',
            name='tax_pricing_type',
            field=models.CharField(choices=[('INCLUSIVE', 'Tax-Inclusive (Price includes applicable Tax / कर सहित)'), ('EXCLUSIVE', 'Tax-Exclusive (Tax added on top / कर बाहेक)'), ('EXEMPT', 'Tax-Exempt / Non-Tax (0% Tax / गैर-कर)')], db_index=True, default='EXEMPT', help_text='Specifies whether the rate includes tax, adds tax on top, or is non-tax exempt.', max_length=20, verbose_name='Tax Pricing Mode'),
        ),
        migrations.AlterField(
            model_name='product',
            name='vat_rate',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5, verbose_name='Tax Rate (%)'),
        ),
        migrations.AlterField(
            model_name='product',
            name='warranty_provider',
            field=models.CharField(blank=True, default='Authorized Distributor', max_length=120, null=True),
        ),
    ]
