# Generated by Django 5.1.15 on 2026-08-23 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0008_alter_product_is_spare_part_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='iteminstance',
            name='mdms_remarks',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='MDMS Remarks / Verification Ref'),
        ),
        migrations.AddField(
            model_name='iteminstance',
            name='mdms_status',
            field=models.CharField(choices=[('REGISTERED_OFFICIAL', 'NTA MDMS Registered (Official Nepal Distributor)'), ('GRAY_UNREGISTERED', 'Unregistered / Gray Channel (Subject to NTA Notice)'), ('INDIVIDUAL_CUSTOMS_PAID', 'Individual Passenger Import (Customs Duty Paid)'), ('EXEMPT', 'Exempt / Non-Cellular Device')], db_index=True, default='REGISTERED_OFFICIAL', help_text='Compliance indicator for Nepal Telecommunications Authority MDMS system.', max_length=30, verbose_name='NTA MDMS Status'),
        ),
        migrations.AddField(
            model_name='iteminstance',
            name='mdms_verification_date',
            field=models.DateField(blank=True, null=True, verbose_name='MDMS Checked Date'),
        ),
        migrations.AddField(
            model_name='iteminstance',
            name='source_type',
            field=models.CharField(choices=[('NEW_PURCHASE_GRN', 'Brand New Inward (GRN Purchase)'), ('CUSTOMER_EXCHANGE_TRADE_IN', 'Customer Exchange / Buy-Back (Trade-In)'), ('REFURBISHED_RETURN', 'Refurbished / Workshop Intake')], db_index=True, default='NEW_PURCHASE_GRN', max_length=30, verbose_name='Device Acquisition Source'),
        ),
        migrations.AddField(
            model_name='iteminstance',
            name='trade_in_voucher_reference',
            field=models.CharField(blank=True, db_index=True, help_text='Links to the customer buy-back undertaking voucher if acquired via exchange.', max_length=60, null=True, verbose_name='Trade-In Voucher Reference'),
        ),
        migrations.AddField(
            model_name='product',
            name='default_mdms_status',
            field=models.CharField(choices=[('REGISTERED_OFFICIAL', 'NTA MDMS Registered (Official Nepal Distributor)'), ('GRAY_UNREGISTERED', 'Unregistered / Gray Channel (Subject to NTA Notice)'), ('INDIVIDUAL_CUSTOMS_PAID', 'Individual Passenger Import (Customs Duty Paid)'), ('EXEMPT', 'Exempt / Non-Cellular Device')], default='REGISTERED_OFFICIAL', help_text='Default status assigned to handsets received under this product model.', max_length=30, verbose_name='Default NTA MDMS Status'),
        ),
        migrations.AlterField(
            model_name='iteminstance',
            name='condition',
            field=models.CharField(choices=[('BRAND_NEW', 'Brand New / Sealed Box'), ('OPEN_BOX', 'Open Box / Like New'), ('REFURBISHED', 'Official Refurbished (Certified)'), ('USED_GRADE_A', 'Pre-Owned Grade A (Flawless / Trade-In)'), ('USED_GRADE_B', 'Pre-Owned Grade B (Minor Scratches / Trade-In)'), ('USED_GRADE_C', 'Pre-Owned Grade C (Heavy Wear / Trade-In)')], db_index=True, default='BRAND_NEW', max_length=25),
        ),
        migrations.AlterField(
            model_name='stockmovementlog',
            name='movement_type',
            field=models.CharField(choices=[('PURCHASE', 'Purchase Received (GRN Inward)'), ('SALE', 'POS Billing Sale (बिक्री)'), ('SALE_RETURN', 'Customer Return (फिर्ता)'), ('TRADE_IN_ACQUISITION', 'Trade-In / Phone Buy-Back Acquisition (+)'), ('TRADE_IN_SALE', 'Pre-Owned / Traded-in Phone Sale (-)'), ('TRANSFER_OUT', 'Branch Transfer Out'), ('TRANSFER_IN', 'Branch Transfer In'), ('ADJUSTMENT_ADD', 'Stock Count Correction (+)'), ('ADJUSTMENT_SUB', 'Damage / Lost / Expired (-)'), ('SERVICE_INTAKE', 'Repair Service Intake'), ('SERVICE_REPLACED_PART_DEDUCT', 'Service Spare Part Installed (-)'), ('SERVICE_DEFECTIVE_QUARANTINE', 'Defective Part Moved to Quarantine (+)'), ('RMA_VENDOR_DISPATCH', 'Defective Part Dispatched to Vendor (-)'), ('RMA_VENDOR_REPLACEMENT_IN', 'Replacement Received from Vendor (+)')], db_index=True, max_length=35),
        ),
    ]
