# Generated by Django 5.1.15 on 2026-08-25 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0009_iteminstance_mdms_remarks_iteminstance_mdms_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='iteminstance',
            name='imei_2_pending_scan',
            field=models.BooleanField(db_index=True, default=False, help_text='True if device is Dual-SIM and only IMEI 1 was captured during GRN. Instructs POS to capture IMEI 2 on sale.', verbose_name='IMEI 2 Pending Scan'),
        ),
    ]
