# Generated by Django 5.1.15 on 2026-08-25 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('branches', '0002_initial'),
        ('inventory', '0010_iteminstance_imei_2_pending_scan'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='iteminstance',
            constraint=models.UniqueConstraint(condition=models.Q(('imei_2__isnull', False), models.Q(('imei_2', ''), _negated=True)), fields=('imei_2',), name='unique_imei_2_when_present'),
        ),
    ]
