# Generated by Django 5.1.15 on 2026-08-26 06:08

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('branches', '0002_initial'),
        ('inventory', '0011_iteminstance_unique_imei_2_when_present'),
        ('purchases', '0006_goodsreceivednote_distributor_mdms_certified_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='iteminstance',
            name='imei_1',
            field=models.CharField(blank=True, db_index=True, max_length=35, null=True, verbose_name='IMEI 1'),
        ),
        migrations.AlterField(
            model_name='iteminstance',
            name='serial_number',
            field=models.CharField(blank=True, db_index=True, max_length=60, null=True),
        ),
        migrations.AddIndex(
            model_name='branchstock',
            index=models.Index(fields=['branch', 'quantity'], name='idx_bstock_branch_qty'),
        ),
        migrations.AddIndex(
            model_name='branchstock',
            index=models.Index(fields=['product', 'branch'], name='idx_bstock_prod_branch'),
        ),
        migrations.AddIndex(
            model_name='branchstock',
            index=models.Index(fields=['branch', 'quarantined_defective_quantity'], name='idx_bstock_branch_quar'),
        ),
        migrations.AddIndex(
            model_name='devicecomponentwarranty',
            index=models.Index(fields=['item_instance', 'status'], name='idx_devwarr_inst_status'),
        ),
        migrations.AddIndex(
            model_name='devicecomponentwarranty',
            index=models.Index(fields=['warranty_expiry_date', 'status'], name='idx_devwarr_exp_status'),
        ),
        migrations.AddIndex(
            model_name='iteminstance',
            index=models.Index(fields=['product', 'branch', 'status'], name='idx_instance_prod_br_status'),
        ),
        migrations.AddIndex(
            model_name='iteminstance',
            index=models.Index(fields=['imei_1', 'status'], name='idx_instance_imei1_status'),
        ),
        migrations.AddIndex(
            model_name='iteminstance',
            index=models.Index(fields=['imei_2', 'status'], name='idx_instance_imei2_status'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['category', 'brand'], name='idx_prod_cat_brand'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['name', 'selling_price'], name='idx_prod_name_price'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['rack_number', 'shelf_identifier'], name='idx_prod_rack_shelf'),
        ),
        migrations.AddIndex(
            model_name='productbatch',
            index=models.Index(fields=['product', 'branch', 'is_depleted'], name='idx_batch_prod_br_depleted'),
        ),
        migrations.AddIndex(
            model_name='productbatch',
            index=models.Index(fields=['purchase_date'], name='idx_batch_purch_date'),
        ),
        migrations.AddIndex(
            model_name='stockmovementlog',
            index=models.Index(fields=['product', 'branch', 'created_at'], name='idx_movelog_prod_br_date'),
        ),
        migrations.AddIndex(
            model_name='stockmovementlog',
            index=models.Index(fields=['movement_type', 'created_at'], name='idx_movelog_type_date'),
        ),
        migrations.AddIndex(
            model_name='stockmovementlog',
            index=models.Index(fields=['reference_document'], name='idx_movelog_ref_doc'),
        ),
        migrations.AddIndex(
            model_name='vendorrmaclaim',
            index=models.Index(fields=['branch', 'status'], name='idx_rma_branch_status'),
        ),
        migrations.AddIndex(
            model_name='vendorrmaclaim',
            index=models.Index(fields=['supplier', 'status'], name='idx_rma_supplier_status'),
        ),
        migrations.AddConstraint(
            model_name='iteminstance',
            constraint=models.UniqueConstraint(condition=models.Q(('imei_1__isnull', False), models.Q(('imei_1', ''), _negated=True)), fields=('imei_1',), name='unique_imei_1_when_present'),
        ),
        migrations.AddConstraint(
            model_name='iteminstance',
            constraint=models.UniqueConstraint(condition=models.Q(('serial_number__isnull', False), models.Q(('serial_number', ''), _negated=True)), fields=('serial_number',), name='unique_serial_number_when_present'),
        ),
    ]
