# Generated by Django 5.1.15 on 2026-08-26 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('branches', '0002_initial'),
        ('inventory', '0012_alter_iteminstance_imei_1_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='iteminstance',
            name='unique_imei_2_when_present',
        ),
        migrations.RemoveConstraint(
            model_name='iteminstance',
            name='unique_imei_1_when_present',
        ),
        migrations.RemoveConstraint(
            model_name='iteminstance',
            name='unique_serial_number_when_present',
        ),
        migrations.AlterField(
            model_name='iteminstance',
            name='status',
            field=models.CharField(choices=[('IN_STOCK', 'In Stock (उपलब्ध)'), ('RESERVED', 'Reserved in Cart / Booking'), ('SOLD', 'Sold (बिक्री भएको)'), ('UNDER_SERVICE', 'Under Service / Repair (मर्मतमा रहेको)'), ('RETURNED_DEFECTIVE', 'Returned Defective (खराब फिर्ता)'), ('TRANSFERRED', 'In Transit Transfer'), ('ARCHIVED', 'Archived / Re-traded (अभिलेख गरिएको)')], db_index=True, default='IN_STOCK', max_length=25),
        ),
        migrations.AddConstraint(
            model_name='iteminstance',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'IN_STOCK'), ('imei_1__isnull', False), models.Q(('imei_1', ''), _negated=True)), fields=('imei_1',), name='unique_active_in_stock_imei_1'),
        ),
        migrations.AddConstraint(
            model_name='iteminstance',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'IN_STOCK'), ('imei_2__isnull', False), models.Q(('imei_2', ''), _negated=True)), fields=('imei_2',), name='unique_active_in_stock_imei_2'),
        ),
        migrations.AddConstraint(
            model_name='iteminstance',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'IN_STOCK'), ('serial_number__isnull', False), models.Q(('serial_number', ''), _negated=True)), fields=('serial_number',), name='unique_active_in_stock_serial_number'),
        ),
    ]
