# Generated by Django 5.1.15 on 2026-08-30 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0013_remove_iteminstance_unique_imei_2_when_present_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='barcode',
            field=models.CharField(blank=True, db_index=True, help_text='Scan physical box barcode or leave completely blank if not needed.', max_length=100, null=True, unique=True, verbose_name='Barcode Number (EAN/UPC)'),
        ),
    ]
