# Generated by Django 5.1.15 on 2026-09-04 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0014_alter_product_barcode'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_discountable',
            field=models.BooleanField(default=True, help_text='If unchecked, no item-level or bill-level discount may be applied to this product.', verbose_name='Discount Allowed'),
        ),
    ]
