# Generated by Django 5.1.15 on 2026-09-23 04:36

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('branches', '0006_alter_branch_city_alter_branch_district'),
        ('inventory', '0015_product_is_discountable'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='brand',
            name='name',
            field=models.CharField(db_index=True, max_length=100, unique=True, verbose_name='Brand Name'),
        ),
        migrations.AlterField(
            model_name='iteminstance',
            name='customer_phone',
            field=models.CharField(blank=True, db_index=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='iteminstance',
            name='sold_invoice_reference',
            field=models.CharField(blank=True, db_index=True, max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='model_name',
            field=models.CharField(blank=True, db_index=True, max_length=150, null=True, verbose_name='Model Name'),
        ),
        migrations.AlterField(
            model_name='product',
            name='model_number',
            field=models.CharField(blank=True, db_index=True, max_length=100, null=True, verbose_name='Model Number'),
        ),
        migrations.AlterField(
            model_name='productcategory',
            name='code',
            field=models.CharField(db_index=True, max_length=20, unique=True, verbose_name='Code (e.g. MOB, ACC, OPT)'),
        ),
        migrations.AlterField(
            model_name='productcategory',
            name='name',
            field=models.CharField(db_index=True, max_length=100, unique=True, verbose_name='Category Name'),
        ),
        migrations.AlterField(
            model_name='productsubcategory',
            name='code',
            field=models.CharField(blank=True, db_index=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='productsubcategory',
            name='name',
            field=models.CharField(db_index=True, max_length=100, verbose_name='Sub-Category Name'),
        ),
        migrations.AlterField(
            model_name='stockmovementlog',
            name='imei_or_serial_number',
            field=models.CharField(blank=True, db_index=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='unitofmeasurement',
            name='code',
            field=models.CharField(db_index=True, max_length=10, unique=True, verbose_name='Short Code (e.g. PCS, PR, BOX)'),
        ),
        migrations.AlterField(
            model_name='unitofmeasurement',
            name='name',
            field=models.CharField(db_index=True, max_length=50, unique=True, verbose_name='Unit Name (e.g. Piece, Pair)'),
        ),
        migrations.AddIndex(
            model_name='brand',
            index=models.Index(fields=['name'], name='idx_brand_name'),
        ),
        migrations.AddIndex(
            model_name='iteminstance',
            index=models.Index(fields=['serial_number', 'status'], name='idx_inst_serial_status'),
        ),
        migrations.AddIndex(
            model_name='iteminstance',
            index=models.Index(fields=['device_barcode', 'status'], name='idx_inst_barcode_status'),
        ),
        migrations.AddIndex(
            model_name='iteminstance',
            index=models.Index(fields=['sold_invoice_reference'], name='idx_inst_sold_invoice'),
        ),
        migrations.AddIndex(
            model_name='iteminstance',
            index=models.Index(fields=['customer_phone'], name='idx_inst_cust_phone'),
        ),
        migrations.AddIndex(
            model_name='iteminstance',
            index=models.Index(fields=['status', 'created_at'], name='idx_inst_status_created'),
        ),
        migrations.AddIndex(
            model_name='iteminstance',
            index=models.Index(fields=['branch', 'status'], name='idx_inst_branch_status'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['model_name'], name='idx_prod_model_name'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['model_number'], name='idx_prod_model_num'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['brand', 'model_name'], name='idx_prod_brand_model'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['name'], name='idx_prod_name'),
        ),
        migrations.AddIndex(
            model_name='productcategory',
            index=models.Index(fields=['name'], name='idx_prodcat_name'),
        ),
        migrations.AddIndex(
            model_name='productcategory',
            index=models.Index(fields=['is_active', 'name'], name='idx_prodcat_active_name'),
        ),
        migrations.AddIndex(
            model_name='productsubcategory',
            index=models.Index(fields=['category', 'name'], name='idx_subcat_cat_name'),
        ),
        migrations.AddIndex(
            model_name='stockmovementlog',
            index=models.Index(fields=['imei_or_serial_number'], name='idx_movelog_imei_serial'),
        ),
        migrations.AddIndex(
            model_name='unitofmeasurement',
            index=models.Index(fields=['name'], name='idx_uom_name'),
        ),
    ]
