# Generated by Django 5.1.15 on 2026-10-01 17:08

import django.utils.timezone
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('branches', '0006_alter_branch_city_alter_branch_district'),
        ('inventory', '0016_alter_brand_name_alter_iteminstance_customer_phone_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productbatch',
            name='expiry_date',
            field=models.DateField(blank=True, null=True, verbose_name='Expiry Date (If Applicable)'),
        ),
        migrations.AlterField(
            model_name='iteminstance',
            name='batch_reference',
            field=models.CharField(blank=True, db_index=True, help_text='Custom batch code linked from GRN line or product batch lot.', max_length=100, null=True, verbose_name='Batch Reference Number'),
        ),
        migrations.AlterField(
            model_name='iteminstance',
            name='purchase_reference',
            field=models.CharField(blank=True, db_index=True, max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='iteminstance',
            name='status',
            field=models.CharField(choices=[('IN_STOCK', 'In Stock (उपलब्ध)'), ('RESERVED', 'Reserved in Cart / Booking'), ('SOLD', 'Sold (बिक्री भएको)'), ('UNDER_SERVICE', 'Under Service / Repair (मर्मतमा रहेको)'), ('RETURNED_DEFECTIVE', 'Returned Defective (खराब फिर्ता)'), ('RETURNED_TO_SUPPLIER', 'Returned to Supplier / Debit Note (सप्लायर फिर्ता)'), ('TRANSFERRED', 'In Transit Transfer'), ('ARCHIVED', 'Archived / Re-traded (अभिलेख गरिएको)')], db_index=True, default='IN_STOCK', max_length=25),
        ),
        migrations.AlterField(
            model_name='productbatch',
            name='batch_number',
            field=models.CharField(db_index=True, help_text='Physical manufacturer, distributor, or user-entered batch identifier.', max_length=100, verbose_name='Batch / Lot Number'),
        ),
        migrations.AlterField(
            model_name='productbatch',
            name='cost_price',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='Unit Landed Cost (NPR)'),
        ),
        migrations.AlterField(
            model_name='productbatch',
            name='grn_reference',
            field=models.CharField(blank=True, db_index=True, max_length=100, null=True, verbose_name='GRN Reference No.'),
        ),
        migrations.AlterField(
            model_name='productbatch',
            name='is_depleted',
            field=models.BooleanField(db_index=True, default=False, verbose_name='Is Depleted'),
        ),
        migrations.AlterField(
            model_name='productbatch',
            name='purchase_date',
            field=models.DateField(db_index=True, default=django.utils.timezone.now, verbose_name='Inward Purchase Date'),
        ),
        migrations.AlterField(
            model_name='productbatch',
            name='quantity_received',
            field=models.DecimalField(decimal_places=3, default=Decimal('0.000'), max_digits=12, verbose_name='Received Quantity'),
        ),
        migrations.AlterField(
            model_name='productbatch',
            name='quantity_remaining',
            field=models.DecimalField(db_index=True, decimal_places=3, default=Decimal('0.000'), max_digits=12, verbose_name='Remaining Quantity'),
        ),
        migrations.AlterField(
            model_name='productbatch',
            name='selling_price',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='Target Counter MRP (NPR)'),
        ),
        migrations.AlterField(
            model_name='productbatch',
            name='supplier_name',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Supplier / Vendor Name'),
        ),
        migrations.AddIndex(
            model_name='iteminstance',
            index=models.Index(fields=['purchase_reference'], name='idx_inst_purch_ref'),
        ),
        migrations.AddIndex(
            model_name='iteminstance',
            index=models.Index(fields=['batch_reference'], name='idx_inst_batch_ref'),
        ),
        migrations.AddIndex(
            model_name='productbatch',
            index=models.Index(fields=['batch_number'], name='idx_batch_number'),
        ),
        migrations.AddIndex(
            model_name='productbatch',
            index=models.Index(fields=['grn_reference'], name='idx_batch_grn_ref'),
        ),
    ]
