# Generated by Django 5.1.15 on 2026-08-20 15:30

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('branches', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScheduledReportLog',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('report_type', models.CharField(choices=[('DAILY_SALES', 'Daily Sales & Collection Summary'), ('STOCK_VALUATION', 'Inventory Stock Valuation'), ('CUSTOMER_UDHAARI', 'Outstanding Credit (Udhaari) Report'), ('SUPPLIER_PAYABLES', 'Supplier Payables Ledger'), ('DEAD_STOCK', 'Dead / Slow-Moving Inventory')], db_index=True, max_length=30)),
                ('export_format', models.CharField(default='CSV', max_length=10)),
                ('file_attachment', models.FileField(blank=True, null=True, upload_to='reports/%Y/%m/')),
                ('recipient_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('summary_metrics', models.JSONField(blank=True, default=dict)),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='branches.branch')),
            ],
            options={
                'verbose_name': 'Report Export Log',
                'verbose_name_plural': 'Report Export Logs',
                'db_table': 'rep_scheduled_logs',
                'ordering': ['-created_at'],
            },
        ),
    ]
