# Generated by Django 5.1.15 on 2026-08-22 07:09

import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('branches', '0002_initial'),
        ('inventory', '0004_iteminstance_batch_reference_iteminstance_sold_price_and_more'),
        ('reports', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='scheduledreportlog',
            name='report_type',
            field=models.CharField(choices=[('DAILY_SALES', 'Daily Sales & Collection Summary'), ('STOCK_VALUATION', 'Inventory Stock Valuation'), ('CUSTOMER_UDHAARI', 'Outstanding Credit (Udhaari) Report'), ('SUPPLIER_PAYABLES', 'Supplier Payables Ledger'), ('DEAD_STOCK', 'Dead / Slow-Moving Inventory'), ('PROFIT_LOSS', 'Gross Profit & Margin Realization')], db_index=True, max_length=30),
        ),
        migrations.CreateModel(
            name='InventoryValuationSnapshot',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('snapshot_date', models.DateField(db_index=True, verbose_name='Snapshot Date (AD)')),
                ('snapshot_date_bs', models.CharField(blank=True, max_length=15, null=True, verbose_name='Snapshot Date (BS)')),
                ('total_units_count', models.DecimalField(decimal_places=3, default=Decimal('0.000'), max_digits=14)),
                ('total_cost_valuation', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=16, verbose_name='Total Cost Valuation (NPR - Exact Inward Landed Costs)')),
                ('total_retail_valuation', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=16, verbose_name='Total Retail Valuation (NPR - Active Counter MRP)')),
                ('projected_margin', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=16, verbose_name='Projected Realizable Margin (NPR)')),
                ('notes', models.TextField(blank=True, null=True)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='valuation_snapshots', to='branches.branch')),
                ('generated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Inventory Valuation Snapshot',
                'verbose_name_plural': 'Inventory Valuation Snapshots',
                'db_table': 'rep_inventory_valuation_snapshots',
                'ordering': ['-snapshot_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProductCostHistory',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('date_effective', models.DateField(db_index=True, verbose_name='Effective Date')),
                ('old_cost_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('new_cost_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('old_selling_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('new_selling_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('source_reference', models.CharField(blank=True, help_text='GRN No. or Excel Import Ref', max_length=100, null=True)),
                ('remarks', models.CharField(blank=True, max_length=255, null=True)),
                ('changed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cost_history', to='inventory.product')),
            ],
            options={
                'verbose_name': 'Product Price Fluctuation History',
                'verbose_name_plural': 'Product Price Fluctuation Histories',
                'db_table': 'rep_product_cost_history',
                'ordering': ['-date_effective', '-created_at'],
            },
        ),
    ]
