# Generated by Django 5.1.15 on 2026-08-20 15:30

import django.db.models.deletion
import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('branches', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GRNItem',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('purchased_quantity', models.DecimalField(decimal_places=3, help_text='Quantity in the purchased package/unit', max_digits=10)),
                ('conversion_factor', models.DecimalField(decimal_places=3, default=Decimal('1.000'), help_text='Multiplier to convert to smallest base unit', max_digits=10)),
                ('base_unit_quantity', models.DecimalField(decimal_places=3, help_text='Effective units added to live stock counter', max_digits=12)),
                ('purchase_rate', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Unit Rate (NPR)')),
                ('discount_percent', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5)),
                ('is_vat_applicable', models.BooleanField(default=True)),
                ('vat_rate', models.DecimalField(decimal_places=2, default=Decimal('13.00'), max_digits=5)),
                ('line_total', models.DecimalField(decimal_places=2, max_digits=14)),
                ('scanned_imei_list', models.TextField(blank=True, help_text='Paste or scan IMEIs (one per line or comma-separated) for phones in this batch', null=True)),
            ],
            options={
                'verbose_name': 'GRN Item Line',
                'verbose_name_plural': 'GRN Item Lines',
                'db_table': 'pur_grn_items',
            },
        ),
        migrations.CreateModel(
            name='PurchaseOrder',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('po_number', models.CharField(db_index=True, max_length=50, unique=True, verbose_name='PO Number')),
                ('order_date', models.DateField()),
                ('expected_delivery_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft PO'), ('ISSUED', 'Issued to Supplier'), ('PARTIALLY_RECEIVED', 'Partially Received'), ('COMPLETED', 'Fully Received & Closed'), ('CANCELLED', 'Cancelled')], db_index=True, default='DRAFT', max_length=25)),
                ('subtotal', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('tax_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('total_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('notes', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Purchase Order',
                'verbose_name_plural': 'Purchase Orders',
                'db_table': 'pur_purchase_orders',
                'ordering': ['-order_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PurchaseOrderItem',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('ordered_quantity', models.DecimalField(decimal_places=3, max_digits=10)),
                ('received_quantity', models.DecimalField(decimal_places=3, default=Decimal('0.000'), max_digits=10)),
                ('unit_cost_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('line_total', models.DecimalField(decimal_places=2, max_digits=14)),
            ],
            options={
                'verbose_name': 'PO Item',
                'verbose_name_plural': 'PO Items',
                'db_table': 'pur_po_items',
            },
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('company_name', models.CharField(db_index=True, max_length=200, verbose_name='Supplier Company Name')),
                ('contact_person', models.CharField(max_length=150, verbose_name='Contact Person')),
                ('phone_number', models.CharField(max_length=25, unique=True, verbose_name='Mobile / Phone')),
                ('alt_phone', models.CharField(blank=True, max_length=25, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('address', models.CharField(max_length=255, verbose_name='Address (e.g. Tamrakar Complex, Pako)')),
                ('city', models.CharField(default='Kathmandu', max_length=100)),
                ('pan_number', models.CharField(blank=True, max_length=15, null=True, verbose_name='PAN Number')),
                ('vat_number', models.CharField(blank=True, max_length=20, null=True, verbose_name='VAT No.')),
                ('credit_period_days', models.PositiveIntegerField(default=30, verbose_name='Credit Terms (Days)')),
                ('current_balance', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Net outstanding balance payable to this supplier (+ indicates shop owes supplier)', max_digits=14)),
                ('bank_details', models.TextField(blank=True, help_text='Bank Name, Account Name & Acc No for Transfers', null=True)),
                ('notes', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Supplier',
                'verbose_name_plural': 'Suppliers',
                'db_table': 'pur_suppliers',
                'ordering': ['company_name'],
            },
        ),
        migrations.CreateModel(
            name='SupplierUdhaariLedger',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('transaction_type', models.CharField(choices=[('PURCHASE_BILL', 'Stock Purchase / GRN (+)'), ('PAYMENT', 'Supplier Payout (-)'), ('PURCHASE_RETURN', 'Defective Return to Vendor (-)'), ('ADJUSTMENT', 'Credit Note / Rate Difference Adjustment')], db_index=True, max_length=25)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('previous_balance', models.DecimalField(decimal_places=2, max_digits=14)),
                ('resulting_balance', models.DecimalField(decimal_places=2, max_digits=14)),
                ('payment_mode', models.CharField(blank=True, choices=[('CASH', 'Cash (नगद)'), ('BANK_TRANSFER', 'Bank Transfer / IPS (बैंक ट्रान्सफर)'), ('CHEQUE', 'Cheque (चेक)'), ('FONEPAY', 'FonePay QR / Digital'), ('OTHER', 'Other Adjustment')], max_length=30, null=True)),
                ('reference_number', models.CharField(blank=True, help_text='GRN No, Cheque No, Bank Ref', max_length=100, null=True)),
                ('cheque_date', models.DateField(blank=True, null=True)),
                ('cheque_cleared', models.BooleanField(default=True)),
                ('remarks', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Supplier Udhaari Entry',
                'verbose_name_plural': 'Supplier Udhaari Ledgers',
                'db_table': 'pur_supplier_ledger',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='GoodsReceivedNote',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('grn_number', models.CharField(db_index=True, max_length=50, unique=True, verbose_name='GRN No.')),
                ('supplier_bill_no', models.CharField(db_index=True, max_length=100, verbose_name='Supplier Invoice / Challan Ref No.')),
                ('bill_date', models.DateField(verbose_name='Bill / Challan Date (AD)')),
                ('bill_date_bs', models.CharField(blank=True, max_length=15, null=True, verbose_name='Bill Date (BS)')),
                ('status', models.CharField(choices=[('DRAFT', 'Draft / In-Inspection'), ('RECEIVED', 'Goods Verified & Stock Updated'), ('CANCELLED', 'Cancelled / Rejected')], db_index=True, default='DRAFT', max_length=20)),
                ('gross_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('discount_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('is_vat_bill', models.BooleanField(default=True, help_text='Check if supplier provided an estimate with 13% VAT calculated')),
                ('vat_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('extra_freight_charge', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('net_total_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('paid_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Amount paid on spot during stock receipt', max_digits=14)),
                ('due_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('estimate_disclaimer_noted', models.BooleanField(default=True, help_text='Marks this internal GRN voucher as non-tax calculation document')),
                ('remarks', models.TextField(blank=True, null=True)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='goods_receipts', to='branches.branch')),
            ],
            options={
                'verbose_name': 'Goods Received Note (GRN)',
                'verbose_name_plural': 'Goods Received Notes (GRN)',
                'db_table': 'pur_goods_received_notes',
                'ordering': ['-created_at'],
            },
        ),
    ]
