# Generated by Django 5.1.15 on 2026-08-22 05:26

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_alter_iteminstance_options_and_more'),
        ('purchases', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='goodsreceivednote',
            name='authorized_service_center',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Authorized Service Center Address/Contact'),
        ),
        migrations.AddField(
            model_name='goodsreceivednote',
            name='customs_import_charge',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='Customs / Duty / Tax (NPR)'),
        ),
        migrations.AddField(
            model_name='goodsreceivednote',
            name='other_handling_charge',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='Insurance / Unloading Cost (NPR)'),
        ),
        migrations.AddField(
            model_name='goodsreceivednote',
            name='supplier_product_code',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Supplier Batch / Product Code'),
        ),
        migrations.AddField(
            model_name='goodsreceivednote',
            name='total_landed_cost',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14, verbose_name='Total Landed Cost (NPR)'),
        ),
        migrations.AddField(
            model_name='goodsreceivednote',
            name='warranty_months',
            field=models.PositiveIntegerField(default=12, verbose_name='Warranty Period (Months)'),
        ),
        migrations.AddField(
            model_name='goodsreceivednote',
            name='warranty_provider',
            field=models.CharField(blank=True, default='Official National Distributor', max_length=150, null=True, verbose_name='Supplier Warranty Provider'),
        ),
        migrations.AddField(
            model_name='grnitem',
            name='supplier_item_code',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Supplier Item SKU / Code'),
        ),
        migrations.AddField(
            model_name='grnitem',
            name='unit_landed_cost',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='Unit Landed Cost (NPR)'),
        ),
        migrations.AddField(
            model_name='grnitem',
            name='warranty_months',
            field=models.PositiveIntegerField(default=12),
        ),
        migrations.AddField(
            model_name='grnitem',
            name='warranty_provider',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='goodsreceivednote',
            name='extra_freight_charge',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='Freight / Courier Charge (NPR)'),
        ),
        migrations.AlterField(
            model_name='goodsreceivednote',
            name='is_vat_bill',
            field=models.BooleanField(default=True, help_text='Check if supplier provided an estimate/invoice with 13% VAT calculated'),
        ),
        migrations.AlterField(
            model_name='grnitem',
            name='conversion_factor',
            field=models.DecimalField(decimal_places=3, default=Decimal('1.000'), help_text='Multiplier to convert to smallest base atomic unit', max_digits=10),
        ),
        migrations.AlterField(
            model_name='grnitem',
            name='unit_conversion',
            field=models.ForeignKey(blank=True, help_text='If bought in packaging unit (e.g. Box of 50)', null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.unitconversion'),
        ),
    ]
