# Generated by Django 5.1.15 on 2026-08-22 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchases', '0003_goodsreceivednote_authorized_service_center_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='grnitem',
            name='new_selling_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Updates master product counter rate upon verification', max_digits=12, null=True, verbose_name='New Target Selling Price / MRP (NPR)'),
        ),
        migrations.AlterField(
            model_name='goodsreceivednote',
            name='bill_date',
            field=models.DateField(db_index=True, verbose_name='Bill / Challan Date (AD)'),
        ),
        migrations.AlterField(
            model_name='grnitem',
            name='purchase_rate',
            field=models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Unit Purchase Rate (NPR)'),
        ),
    ]
