# Generated by Django 5.1.15 on 2026-08-23 07:50

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchases', '0004_grnitem_new_selling_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goodsreceivednote',
            name='estimate_disclaimer_noted',
            field=models.BooleanField(default=True, help_text='Marks this internal GRN voucher as internal proforma/estimation document'),
        ),
        migrations.AlterField(
            model_name='goodsreceivednote',
            name='is_vat_bill',
            field=models.BooleanField(default=False, help_text='Enable if the supplier provided a VAT bill with dynamic input tax calculation.', verbose_name='Is Tax / VAT Inward Bill'),
        ),
        migrations.AlterField(
            model_name='goodsreceivednote',
            name='vat_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='Input Tax / VAT Amount'),
        ),
        migrations.AlterField(
            model_name='grnitem',
            name='is_vat_applicable',
            field=models.BooleanField(default=False, verbose_name='Is Tax / VAT Applicable'),
        ),
        migrations.AlterField(
            model_name='grnitem',
            name='vat_rate',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5, verbose_name='Tax / VAT Rate (%)'),
        ),
    ]
