# Generated by Django 5.1.15 on 2026-08-23 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchases', '0005_alter_goodsreceivednote_estimate_disclaimer_noted_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='goodsreceivednote',
            name='distributor_mdms_certified',
            field=models.BooleanField(default=True, help_text='Certifies that all handset IMEIs in this consignment are official imports registered in NTA MDMS.', verbose_name='Distributor MDMS Certified'),
        ),
        migrations.AddField(
            model_name='goodsreceivednote',
            name='mdms_tax_invoice_ref',
            field=models.CharField(blank=True, help_text='Pragyapan Patra / Customs Declaration or Distributor MDMS Clearance Ref No.', max_length=100, null=True, verbose_name='Customs Entry / NTA Declaration No.'),
        ),
        migrations.AddField(
            model_name='grnitem',
            name='default_mdms_status',
            field=models.CharField(choices=[('REGISTERED_OFFICIAL', 'NTA MDMS Registered (Official Nepal Distributor)'), ('GRAY_UNREGISTERED', 'Unregistered / Gray Channel (Subject to NTA Notice)'), ('INDIVIDUAL_CUSTOMS_PAID', 'Individual Passenger Import (Customs Duty Paid)'), ('EXEMPT', 'Exempt / Non-Cellular Device')], default='REGISTERED_OFFICIAL', max_length=30, verbose_name='Line MDMS Status'),
        ),
    ]
