# Generated by Django 5.1.15 on 2026-08-27 07:13

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchases', '0006_goodsreceivednote_distributor_mdms_certified_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='supplier',
            options={'ordering': ['company_name'], 'verbose_name': 'Supplier / Distributor', 'verbose_name_plural': 'Suppliers & Distributors'},
        ),
        migrations.AddField(
            model_name='supplier',
            name='account_holder_name',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Account Holder Name'),
        ),
        migrations.AddField(
            model_name='supplier',
            name='balance_type',
            field=models.CharField(choices=[('PAYABLE', 'Payable to Supplier (हामीले तिर्नुपर्ने दायित्व)'), ('ADVANCE', 'Advance Paid to Supplier (अग्रिम भुक्तानी)')], default='PAYABLE', max_length=15, verbose_name='Opening Balance Nature'),
        ),
        migrations.AddField(
            model_name='supplier',
            name='bank_account_number',
            field=models.CharField(blank=True, max_length=60, null=True, verbose_name='Bank Account Number'),
        ),
        migrations.AddField(
            model_name='supplier',
            name='bank_branch',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Bank Branch Location'),
        ),
        migrations.AddField(
            model_name='supplier',
            name='bank_name',
            field=models.CharField(blank=True, max_length=120, null=True, verbose_name='Bank Name'),
        ),
        migrations.AddField(
            model_name='supplier',
            name='brand_authorization_details',
            field=models.TextField(blank=True, help_text='e.g. Authorized National Distributor for Samsung Nepal (Auth Ref: SAM-NP-2024)', null=True, verbose_name='Brand Authorization Certificate Details'),
        ),
        migrations.AddField(
            model_name='supplier',
            name='brands_supplied',
            field=models.TextField(blank=True, help_text='e.g. Samsung, Apple, Xiaomi, Vivo, Realme, Ray-Ban', null=True, verbose_name='Authorized Brands Supplied'),
        ),
        migrations.AddField(
            model_name='supplier',
            name='code',
            field=models.CharField(blank=True, db_index=True, help_text='Auto-generated sequential code (e.g. SUP-00001)', max_length=25, unique=True, verbose_name='Supplier Code'),
        ),
        migrations.AddField(
            model_name='supplier',
            name='country',
            field=models.CharField(default='Nepal', max_length=50, verbose_name='Country'),
        ),
        migrations.AddField(
            model_name='supplier',
            name='credit_limit',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Maximum allowed credit line with this vendor (0.00 for unlimited/cash-only)', max_digits=14, verbose_name='Credit Limit (NPR)'),
        ),
        migrations.AddField(
            model_name='supplier',
            name='defective_return_policy',
            field=models.TextField(blank=True, help_text='Standard return policies for swollen batteries, line displays, and dead boards.', null=True, verbose_name='General Defective RMA Return Policy'),
        ),
        migrations.AddField(
            model_name='supplier',
            name='designation',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Contact Person Designation'),
        ),
        migrations.AddField(
            model_name='supplier',
            name='distributor_tier',
            field=models.CharField(blank=True, choices=[('TIER_1_NATIONAL', 'Tier-1 National Importer (Official)'), ('TIER_2_REGIONAL', 'Tier-2 Regional Super Stockist'), ('MASTER_DEALER', 'Master Dealer / Area Distributor'), ('LOCAL_DEALER', 'Authorized Local Sub-Dealer')], max_length=30, null=True, verbose_name='Distributor / Dealer Tier'),
        ),
        migrations.AddField(
            model_name='supplier',
            name='doa_policy',
            field=models.TextField(blank=True, help_text='Terms for Dead On Arrival (DOA) instant unboxed handset replacement.', null=True, verbose_name='7-Day DOA Replacement Policy'),
        ),
        migrations.AddField(
            model_name='supplier',
            name='is_authorized_distributor',
            field=models.BooleanField(default=False, help_text='Check if this vendor is an official national or regional brand distributor in Nepal.', verbose_name='Is Authorized Brand Distributor'),
        ),
        migrations.AddField(
            model_name='supplier',
            name='is_preferred',
            field=models.BooleanField(default=False, verbose_name='Preferred / Regular Supplier'),
        ),
        migrations.AddField(
            model_name='supplier',
            name='kyc_document',
            field=models.FileField(blank=True, help_text='Upload PDF, JPG, or PNG copy of VAT/PAN certificate or authorized distributor agreement.', null=True, upload_to='suppliers/kyc/%Y/%m/', verbose_name='Company Registration / PAN Certificate Document'),
        ),
        migrations.AddField(
            model_name='supplier',
            name='last_payment_date',
            field=models.DateField(blank=True, null=True, verbose_name='Last Payment Date'),
        ),
        migrations.AddField(
            model_name='supplier',
            name='last_purchase_date',
            field=models.DateField(blank=True, null=True, verbose_name='Last Purchase Date'),
        ),
        migrations.AddField(
            model_name='supplier',
            name='opening_balance',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14, verbose_name='Opening Balance (NPR)'),
        ),
        migrations.AddField(
            model_name='supplier',
            name='preferred_payment_method',
            field=models.CharField(choices=[('BANK_TRANSFER', 'Bank Transfer / ConnectIPS (बैंक ट्रान्सफर)'), ('CHEQUE', 'Account Payee Cheque (चेक)'), ('DIGITAL_QR', 'FonePay / Digital QR (डिजिटल क्यूआर)'), ('CASH', 'Cash Counter (नगद)')], default='BANK_TRANSFER', max_length=25, verbose_name='Preferred Payment Mode'),
        ),
        migrations.AddField(
            model_name='supplier',
            name='product_categories_supplied',
            field=models.TextField(blank=True, help_text='e.g. Smartphones, Optical Frames, Tempered Glass, Chargers', null=True, verbose_name='Product Categories Supplied'),
        ),
        migrations.AddField(
            model_name='supplier',
            name='province',
            field=models.CharField(choices=[('Koshi', 'Koshi Province (कोशी प्रदेश)'), ('Madhesh', 'Madhesh Province (मधेश प्रदेश)'), ('Bagmati', 'Bagmati Province (बागमती प्रदेश)'), ('Gandaki', 'Gandaki Province (गण्डकी प्रदेश)'), ('Lumbini', 'Lumbini Province (लुम्बिनी प्रदेश)'), ('Karnali', 'Karnali Province (कर्णाली प्रदेश)'), ('Sudurpashchim', 'Sudurpashchim Province (सुदूरपश्चिम प्रदेश)')], default='Bagmati', max_length=50, verbose_name='Province (नेपालको प्रदेश)'),
        ),
        migrations.AddField(
            model_name='supplier',
            name='qr_payment_details',
            field=models.TextField(blank=True, help_text='Paste FonePay Merchant ID, UPI ID, or account transfer remarks.', null=True, verbose_name='FonePay / Merchant QR Details'),
        ),
        migrations.AddField(
            model_name='supplier',
            name='rating',
            field=models.PositiveSmallIntegerField(choices=[(1, '1 Star (Poor)'), (2, '2 Stars (Fair)'), (3, '3 Stars (Good)'), (4, '4 Stars (Very Good)'), (5, '5 Stars (Excellent)')], default=5, verbose_name='Vendor Performance Rating'),
        ),
        migrations.AddField(
            model_name='supplier',
            name='registration_number',
            field=models.CharField(db_index=True, default='PENDING-REG', max_length=100, verbose_name='Company Registrar / Govt Reg No.'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='supplier',
            name='status',
            field=models.CharField(choices=[('ACTIVE', 'Active & Verified (सक्रिय)'), ('INACTIVE', 'Inactive / Paused (निष्क्रिय)'), ('BLOCKED', 'Blocked / Disputed (रोक्का गरिएको)')], db_index=True, default='ACTIVE', max_length=20, verbose_name='Account Status'),
        ),
        migrations.AddField(
            model_name='supplier',
            name='supplier_type',
            field=models.CharField(choices=[('NATIONAL_DISTRIBUTOR', 'National Importer / Distributor (राष्ट्रिय आयातकर्ता)'), ('REGIONAL_WHOLESALER', 'Regional Wholesaler / Stockist (क्षेत्रीय थोक विक्रेता)'), ('MANUFACTURER', 'Authorized Brand Manufacturer (उत्पादक)'), ('LOCAL_TRADER', 'Local Dealer / Trader (स्थानीय बिक्रेता)'), ('SERVICE_PARTS_VENDOR', 'Spare Parts & Service Supplier (पार्ट्स आपूर्तिकर्ता)')], default='NATIONAL_DISTRIBUTOR', max_length=30, verbose_name='Supplier Classification'),
        ),
        migrations.AddField(
            model_name='supplier',
            name='warranty_claim_contact',
            field=models.TextField(blank=True, help_text='Physical service center address, engineer contact, and dispatch instructions.', null=True, verbose_name='Warranty Claim Lab / Service Center Location'),
        ),
        migrations.AddField(
            model_name='supplier',
            name='warranty_support_available',
            field=models.BooleanField(default=True, help_text='Indicates whether this distributor provides in-house warranty and spare parts support.', verbose_name='Warranty Support Available'),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='address',
            field=models.CharField(max_length=255, verbose_name='Street Address / Market Location'),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='alt_phone',
            field=models.CharField(blank=True, max_length=25, null=True, verbose_name='Alternate / Office Landline'),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='bank_details',
            field=models.TextField(blank=True, help_text='Consolidated bank text notes.', null=True, verbose_name='Legacy Banking Notes'),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='city',
            field=models.CharField(default='Kathmandu', max_length=100, verbose_name='City'),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='company_name',
            field=models.CharField(db_index=True, max_length=200, verbose_name='Company / Firm Name'),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='contact_person',
            field=models.CharField(max_length=150, verbose_name='Authorized Contact Person'),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='current_balance',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Positive balance indicates amount shop owes the supplier.', max_digits=14, verbose_name='Net Outstanding Balance (NPR)'),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Official Email Address'),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='notes',
            field=models.TextField(blank=True, null=True, verbose_name='General Remarks / Internal Notes'),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='phone_number',
            field=models.CharField(db_index=True, max_length=25, unique=True, verbose_name='Primary Mobile / Phone Number'),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='vat_number',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='VAT Registration No.'),
        ),
        migrations.AddIndex(
            model_name='supplier',
            index=models.Index(fields=['code'], name='idx_sup_code'),
        ),
        migrations.AddIndex(
            model_name='supplier',
            index=models.Index(fields=['company_name', 'status'], name='idx_sup_name_status'),
        ),
        migrations.AddIndex(
            model_name='supplier',
            index=models.Index(fields=['registration_number'], name='idx_sup_reg_no'),
        ),
    ]
