# Generated by Django 5.1.15 on 2026-08-27 07:19

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchases', '0007_alter_supplier_options_supplier_account_holder_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supplier',
            name='city',
            field=models.CharField(blank=True, default='Kathmandu', max_length=100, verbose_name='City'),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='country',
            field=models.CharField(blank=True, default='Nepal', max_length=50, verbose_name='Country'),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='credit_limit',
            field=models.DecimalField(blank=True, decimal_places=2, default=Decimal('0.00'), help_text='Maximum allowed credit line with this vendor (0.00 for unlimited/cash-only)', max_digits=14, null=True, verbose_name='Credit Limit (NPR)'),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='credit_period_days',
            field=models.PositiveIntegerField(blank=True, default=30, null=True, verbose_name='Credit Terms (Days)'),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='current_balance',
            field=models.DecimalField(blank=True, decimal_places=2, default=Decimal('0.00'), help_text='Positive balance indicates amount shop owes the supplier.', max_digits=14, null=True, verbose_name='Net Outstanding Balance (NPR)'),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='opening_balance',
            field=models.DecimalField(blank=True, decimal_places=2, default=Decimal('0.00'), max_digits=14, null=True, verbose_name='Opening Balance (NPR)'),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='rating',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, '1 Star (Poor)'), (2, '2 Stars (Fair)'), (3, '3 Stars (Good)'), (4, '4 Stars (Very Good)'), (5, '5 Stars (Excellent)')], default=5, null=True, verbose_name='Vendor Performance Rating'),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='registration_number',
            field=models.CharField(db_index=True, default='PENDING-REG', max_length=100, verbose_name='Company Registrar / Govt Reg No.'),
        ),
    ]
