# Generated by Django 5.1.15 on 2026-08-27 10:00

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchases', '0008_alter_supplier_city_alter_supplier_country_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grnitem',
            name='base_unit_quantity',
            field=models.DecimalField(blank=True, decimal_places=3, default=Decimal('1.000'), help_text='Effective units added to live stock counter', max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='grnitem',
            name='line_total',
            field=models.DecimalField(blank=True, decimal_places=2, default=Decimal('0.00'), max_digits=14, null=True),
        ),
        migrations.AlterField(
            model_name='grnitem',
            name='purchase_rate',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='Unit Purchase Rate (NPR)'),
        ),
        migrations.AlterField(
            model_name='grnitem',
            name='purchased_quantity',
            field=models.DecimalField(decimal_places=3, default=Decimal('1.000'), help_text='Quantity in the purchased package/unit', max_digits=10),
        ),
    ]
