# Generated by Django 5.1.15 on 2026-09-05 11:27

import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('branches', '0006_alter_branch_city_alter_branch_district'),
        ('inventory', '0015_product_is_discountable'),
        ('purchases', '0009_alter_grnitem_base_unit_quantity_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='supplier',
            name='warranty_claim_contact',
            field=models.TextField(blank=True, help_text='Physical service center address, engineer contact, and drop point...', null=True, verbose_name='Warranty Claim Lab / Service Center Location'),
        ),
        migrations.AlterField(
            model_name='supplierudhaariledger',
            name='reference_number',
            field=models.CharField(blank=True, help_text='GRN No, Cheque No, Bank Ref, Debit Note No', max_length=100, null=True),
        ),
        migrations.CreateModel(
            name='PurchaseReturn',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('return_number', models.CharField(db_index=True, max_length=50, unique=True, verbose_name='Debit Note / Return No.')),
                ('original_bill_reference', models.CharField(blank=True, max_length=100, null=True, verbose_name='Supplier Invoice / Challan Ref No.')),
                ('return_date', models.DateField(db_index=True, verbose_name='Return Date (AD)')),
                ('return_date_bs', models.CharField(blank=True, max_length=15, null=True, verbose_name='Return Date (BS)')),
                ('refund_mode', models.CharField(choices=[('DEDUCT_FROM_BALANCE', 'Deduct from Supplier Balance (उधारो कट्टी / हिसाब मिलान)'), ('CASH_REFUND', 'Cash / Bank Refund Received (नगद / बैंक फिर्ता)'), ('REPLACEMENT', 'Replacement Consignment Expected (सामान साट्ने)')], default='DEDUCT_FROM_BALANCE', max_length=30, verbose_name='Refund / Settlement Mode')),
                ('status', models.CharField(choices=[('DRAFT', 'Draft / In-Preparation (मस्यौदा)'), ('CONFIRMED', 'Confirmed & Stock Deducted (स्वीकृत / मौज्दात कट्टी)'), ('CANCELLED', 'Cancelled / Voided (रद्द गरिएको)')], db_index=True, default='CONFIRMED', max_length=20, verbose_name='Voucher Status')),
                ('total_return_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14, verbose_name='Total Return Value (NPR)')),
                ('tax_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='Tax / VAT Amount (NPR)')),
                ('net_refund_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14, verbose_name='Net Refund / Debit Note Amount (NPR)')),
                ('remarks', models.TextField(blank=True, null=True, verbose_name='Reason / Remarks for Return')),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='purchase_returns', to='branches.branch', verbose_name='Branch / Outlet')),
                ('original_grn', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='purchase_returns', to='purchases.goodsreceivednote', verbose_name='Original GRN Reference')),
                ('processed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='processed_purchase_returns', to=settings.AUTH_USER_MODEL, verbose_name='Processed By')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='purchase_returns', to='purchases.supplier', verbose_name='Supplier / Distributor')),
            ],
            options={
                'verbose_name': 'Purchase Return / Debit Note',
                'verbose_name_plural': 'Purchase Returns / Debit Notes',
                'db_table': 'pur_purchase_returns',
                'ordering': ['-return_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PurchaseReturnItem',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('returned_quantity', models.DecimalField(decimal_places=3, default=Decimal('1.000'), max_digits=10, verbose_name='Returned Quantity')),
                ('conversion_factor', models.DecimalField(decimal_places=3, default=Decimal('1.000'), max_digits=10, verbose_name='Conversion Factor')),
                ('base_unit_quantity', models.DecimalField(decimal_places=3, default=Decimal('1.000'), max_digits=12, verbose_name='Base Unit Quantity Deducted')),
                ('purchase_rate', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='Unit Purchase Rate (NPR)')),
                ('tax_rate', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5, verbose_name='Tax / VAT Rate (%)')),
                ('tax_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='Tax / VAT Amount (NPR)')),
                ('line_total', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14, verbose_name='Line Total (NPR)')),
                ('returned_imei_list', models.TextField(blank=True, help_text='Comma or newline separated 15-digit IMEIs returned to vendor', null=True, verbose_name='Returned IMEIs / Serials')),
                ('return_reason', models.CharField(blank=True, help_text='e.g. Factory Defect, Damaged Box, Dead on Arrival, Wrong Model Received', max_length=255, null=True, verbose_name='Specific Defect / Reason for Line')),
                ('item_instance', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='purchase_return_records', to='inventory.iteminstance', verbose_name='Linked Serialized Unit')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='purchase_return_items', to='inventory.product', verbose_name='Product / Handset Model')),
                ('purchase_return', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='purchases.purchasereturn', verbose_name='Purchase Return / Debit Note')),
                ('unit_conversion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.unitconversion', verbose_name='Packaging Unit')),
            ],
            options={
                'verbose_name': 'Purchase Return Item',
                'verbose_name_plural': 'Purchase Return Items',
                'db_table': 'pur_purchase_return_items',
            },
        ),
    ]
