# Generated by Django 5.1.15 on 2026-09-08 08:11

import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('branches', '0006_alter_branch_city_alter_branch_district'),
        ('purchases', '0010_alter_supplier_warranty_claim_contact_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='goodsreceivednote',
            options={'ordering': ['-bill_date', '-created_at'], 'verbose_name': 'Goods Received Note (GRN)', 'verbose_name_plural': 'Goods Received Notes (GRN)'},
        ),
        migrations.AddField(
            model_name='goodsreceivednote',
            name='fiscal_year',
            field=models.CharField(blank=True, db_index=True, help_text='Nepali Fiscal Year derived from BS date (e.g. 2080/81, 2081/82).', max_length=10, null=True, verbose_name='Fiscal Year (BS)'),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='fiscal_year',
            field=models.CharField(blank=True, db_index=True, help_text='Nepali Fiscal Year derived from BS date (e.g. 2080/81, 2081/82).', max_length=10, null=True, verbose_name='Fiscal Year (BS)'),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='order_date_bs',
            field=models.CharField(blank=True, db_index=True, help_text='Bikram Sambat formatted date string (YYYY-MM-DD).', max_length=15, null=True, verbose_name='PO Order Date (BS)'),
        ),
        migrations.AddField(
            model_name='purchasereturn',
            name='fiscal_year',
            field=models.CharField(blank=True, db_index=True, help_text='Nepali Fiscal Year derived from BS date (e.g. 2080/81, 2081/82).', max_length=10, null=True, verbose_name='Fiscal Year (BS)'),
        ),
        migrations.AlterField(
            model_name='goodsreceivednote',
            name='bill_date',
            field=models.DateField(db_index=True, default=django.utils.timezone.now, help_text='Gregorian date for database indexing and accounting. Allows manual historical import dates from 2080 B.S.', verbose_name='Bill / Challan Date (AD)'),
        ),
        migrations.AlterField(
            model_name='goodsreceivednote',
            name='bill_date_bs',
            field=models.CharField(blank=True, db_index=True, help_text='Bikram Sambat formatted date string (YYYY-MM-DD).', max_length=15, null=True, verbose_name='Bill Date (BS)'),
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='order_date',
            field=models.DateField(db_index=True, default=django.utils.timezone.now, help_text='Gregorian date for database indexing. Allows manual historical import dates.', verbose_name='PO Order Date (AD)'),
        ),
        migrations.AlterField(
            model_name='purchasereturn',
            name='return_date',
            field=models.DateField(db_index=True, default=django.utils.timezone.now, help_text='Gregorian date for database indexing. Allows manual historical import dates.', verbose_name='Return Date (AD)'),
        ),
        migrations.AlterField(
            model_name='purchasereturn',
            name='return_date_bs',
            field=models.CharField(blank=True, db_index=True, help_text='Bikram Sambat formatted date string (YYYY-MM-DD).', max_length=15, null=True, verbose_name='Return Date (BS)'),
        ),
        migrations.AddIndex(
            model_name='goodsreceivednote',
            index=models.Index(fields=['bill_date', 'status', 'branch'], name='idx_grn_date_status_branch'),
        ),
        migrations.AddIndex(
            model_name='goodsreceivednote',
            index=models.Index(fields=['fiscal_year', 'branch'], name='idx_grn_fy_branch'),
        ),
        migrations.AddIndex(
            model_name='goodsreceivednote',
            index=models.Index(fields=['supplier', 'bill_date'], name='idx_grn_supplier_date'),
        ),
        migrations.AddIndex(
            model_name='goodsreceivednote',
            index=models.Index(fields=['supplier_bill_no'], name='idx_grn_supp_bill'),
        ),
        migrations.AddIndex(
            model_name='goodsreceivednote',
            index=models.Index(fields=['grn_number'], name='idx_grn_num'),
        ),
        migrations.AddIndex(
            model_name='purchaseorder',
            index=models.Index(fields=['order_date', 'status', 'branch'], name='idx_po_date_status_branch'),
        ),
        migrations.AddIndex(
            model_name='purchaseorder',
            index=models.Index(fields=['fiscal_year', 'branch'], name='idx_po_fy_branch'),
        ),
        migrations.AddIndex(
            model_name='purchaseorder',
            index=models.Index(fields=['po_number'], name='idx_po_num'),
        ),
        migrations.AddIndex(
            model_name='purchasereturn',
            index=models.Index(fields=['return_date', 'branch'], name='idx_pret_date_branch'),
        ),
        migrations.AddIndex(
            model_name='purchasereturn',
            index=models.Index(fields=['fiscal_year', 'branch'], name='idx_pret_fy_branch'),
        ),
        migrations.AddIndex(
            model_name='purchasereturn',
            index=models.Index(fields=['return_number'], name='idx_pret_num'),
        ),
    ]
