# Generated by Django 5.1.15 on 2026-09-17 15:08

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchases', '0011_alter_goodsreceivednote_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supplier',
            name='current_balance',
            field=models.DecimalField(blank=True, decimal_places=2, default=Decimal('0.00'), help_text='Positive balance indicates amount shop owes the supplier. Auto-calculated from ledger.', max_digits=14, null=True, verbose_name='Net Outstanding Balance (NPR)'),
        ),
        migrations.AlterField(
            model_name='supplierudhaariledger',
            name='payment_mode',
            field=models.CharField(blank=True, choices=[('CASH', 'Cash (नगद)'), ('BANK_TRANSFER', 'Bank Transfer / IPS (बैंक ट्रान्सफर)'), ('CHEQUE', 'Cheque (चेक)'), ('FONEPAY', 'FonePay QR / Digital'), ('OTHER', 'Other Adjustment / Opening Balance')], max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='supplierudhaariledger',
            name='transaction_type',
            field=models.CharField(choices=[('OPENING_BALANCE', 'Opening Balance (सुरुवाती मौज्दात)'), ('PURCHASE_BILL', 'Stock Purchase / GRN (+)'), ('PAYMENT', 'Supplier Payout (-)'), ('PURCHASE_RETURN', 'Defective Return to Vendor (-)'), ('ADJUSTMENT', 'Credit Note / Rate Difference Adjustment')], db_index=True, max_length=25),
        ),
    ]
