# Generated by Django 5.1.15 on 2026-09-23 04:59

from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('branches', '0006_alter_branch_city_alter_branch_district'),
        ('inventory', '0016_alter_brand_name_alter_iteminstance_customer_phone_and_more'),
        ('purchases', '0012_alter_supplier_current_balance_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='supplier',
            name='contact_person',
            field=models.CharField(db_index=True, max_length=150, verbose_name='Authorized Contact Person'),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='current_balance',
            field=models.DecimalField(blank=True, db_index=True, decimal_places=2, default=Decimal('0.00'), help_text='Positive balance indicates amount shop owes the supplier. Auto-calculated from ledger.', max_digits=14, null=True, verbose_name='Net Outstanding Balance (NPR)'),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='pan_number',
            field=models.CharField(blank=True, db_index=True, max_length=15, null=True, verbose_name='PAN Number'),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='vat_number',
            field=models.CharField(blank=True, db_index=True, max_length=20, null=True, verbose_name='VAT Registration No.'),
        ),
        migrations.AddIndex(
            model_name='grnitem',
            index=models.Index(fields=['grn', 'product'], name='idx_grn_item_grn_prod'),
        ),
        migrations.AddIndex(
            model_name='purchaseorder',
            index=models.Index(fields=['supplier', 'order_date'], name='idx_po_supplier_date'),
        ),
        migrations.AddIndex(
            model_name='purchaseorderitem',
            index=models.Index(fields=['purchase_order', 'product'], name='idx_po_item_po_prod'),
        ),
        migrations.AddIndex(
            model_name='purchasereturn',
            index=models.Index(fields=['supplier', 'return_date'], name='idx_pret_supp_date'),
        ),
        migrations.AddIndex(
            model_name='purchasereturnitem',
            index=models.Index(fields=['purchase_return', 'product'], name='idx_pret_item_ret_prod'),
        ),
        migrations.AddIndex(
            model_name='supplier',
            index=models.Index(fields=['company_name'], name='idx_sup_company_name'),
        ),
        migrations.AddIndex(
            model_name='supplier',
            index=models.Index(fields=['contact_person'], name='idx_sup_contact_person'),
        ),
        migrations.AddIndex(
            model_name='supplier',
            index=models.Index(fields=['phone_number'], name='idx_sup_phone_num'),
        ),
        migrations.AddIndex(
            model_name='supplier',
            index=models.Index(fields=['pan_number'], name='idx_sup_pan_num'),
        ),
        migrations.AddIndex(
            model_name='supplier',
            index=models.Index(fields=['vat_number'], name='idx_sup_vat_num'),
        ),
        migrations.AddIndex(
            model_name='supplier',
            index=models.Index(fields=['current_balance'], name='idx_sup_current_balance'),
        ),
        migrations.AddIndex(
            model_name='supplierudhaariledger',
            index=models.Index(fields=['supplier', 'transaction_type'], name='idx_sup_ledg_sup_type'),
        ),
        migrations.AddIndex(
            model_name='supplierudhaariledger',
            index=models.Index(fields=['supplier', '-created_at'], name='idx_sup_ledg_sup_created'),
        ),
        migrations.AddIndex(
            model_name='supplierudhaariledger',
            index=models.Index(fields=['branch', '-created_at'], name='idx_sup_ledg_br_created'),
        ),
        migrations.AddIndex(
            model_name='supplierudhaariledger',
            index=models.Index(fields=['reference_number'], name='idx_sup_ledg_ref_no'),
        ),
    ]
