# Generated by Django 5.1.15 on 2026-09-23 18:45

import django.utils.timezone
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchases', '0013_alter_supplier_contact_person_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='goodsreceivednote',
            name='bill_discount_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Cash rupee deduction calculated from bill discount input.', max_digits=12, verbose_name='Bill Discount Amount (NPR)'),
        ),
        migrations.AddField(
            model_name='goodsreceivednote',
            name='bill_discount_input_value',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Value typed by user: flat rupee discount or percentage discount on entire bill.', max_digits=12, verbose_name='Bill Discount Input Value'),
        ),
        migrations.AddField(
            model_name='goodsreceivednote',
            name='bill_discount_type',
            field=models.CharField(choices=[('NONE', 'No Bill Discount'), ('PERCENTAGE', 'Percentage (%)'), ('AMOUNT', 'Flat Amount (रू)')], default='NONE', max_length=15, verbose_name='Bill Discount Mode'),
        ),
        migrations.AddField(
            model_name='goodsreceivednote',
            name='taxable_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Net pre-VAT merchandise value (Gross Lines - Total Discounts).', max_digits=14, verbose_name='Pre-VAT Taxable Base (NPR)'),
        ),
        migrations.AddField(
            model_name='goodsreceivednote',
            name='total_line_discount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Sum of individual item line rupee deductions.', max_digits=12, verbose_name='Total Line Discounts (NPR)'),
        ),
        migrations.AddField(
            model_name='goodsreceivednote',
            name='vat_rate',
            field=models.DecimalField(decimal_places=2, default=Decimal('13.00'), max_digits=5, verbose_name='VAT Rate (%)'),
        ),
        migrations.AddField(
            model_name='grnitem',
            name='discount_input_value',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Store user input: either percentage (e.g. 5) or cash amount (e.g. 2000).', max_digits=12, verbose_name='Discount Input'),
        ),
        migrations.AddField(
            model_name='grnitem',
            name='discount_type',
            field=models.CharField(choices=[('NONE', 'No Discount'), ('PERCENTAGE', 'Percentage (%)'), ('AMOUNT', 'Flat Amount (रू)')], default='NONE', max_length=15, verbose_name='Discount Type'),
        ),
        migrations.AddField(
            model_name='grnitem',
            name='gross_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Pre-discount gross value = Quantity * Purchase Rate', max_digits=14, verbose_name='Line Gross Pre-VAT (NPR)'),
        ),
        migrations.AddField(
            model_name='grnitem',
            name='item_discount_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Exact cash rupee deduction applied to this line.', max_digits=12, verbose_name='Discount Amount (NPR)'),
        ),
        migrations.AlterField(
            model_name='goodsreceivednote',
            name='bill_date',
            field=models.DateField(db_index=True, default=django.utils.timezone.now, help_text='Gregorian date for indexing. Allows manual historical import dates from 2080 B.S.', verbose_name='Bill / Challan Date (AD)'),
        ),
        migrations.AlterField(
            model_name='goodsreceivednote',
            name='discount_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Total Line Discounts + Whole Bill Discount.', max_digits=12, verbose_name='Consolidated Total Discount (NPR)'),
        ),
        migrations.AlterField(
            model_name='goodsreceivednote',
            name='due_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Invoice Total - Paid Amount. Automatically posted to supplier credit ledger.', max_digits=14, verbose_name='Net Due / Supplier Debt (NPR)'),
        ),
        migrations.AlterField(
            model_name='goodsreceivednote',
            name='gross_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Sum of all item line pre-VAT merchandise values before discounts.', max_digits=14, verbose_name='Gross Pre-VAT Amount (NPR)'),
        ),
        migrations.AlterField(
            model_name='goodsreceivednote',
            name='is_vat_bill',
            field=models.BooleanField(default=False, help_text='Enable if supplier issued an official VAT invoice. Calculates 13% on Taxable Pre-VAT Base.', verbose_name='13% VAT Inward Tax Bill'),
        ),
        migrations.AlterField(
            model_name='goodsreceivednote',
            name='net_total_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Net invoice payable to supplier = Pre-VAT Taxable Base + 13% VAT Amount.', max_digits=14, verbose_name='Supplier Invoice Total (NPR)'),
        ),
        migrations.AlterField(
            model_name='goodsreceivednote',
            name='other_handling_charge',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='Insurance / Handling Cost (NPR)'),
        ),
        migrations.AlterField(
            model_name='goodsreceivednote',
            name='paid_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Cash, cheque, or digital amount paid on delivery.', max_digits=14, verbose_name='Paid Amount on Receipt (NPR)'),
        ),
        migrations.AlterField(
            model_name='goodsreceivednote',
            name='total_landed_cost',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Pre-VAT Taxable Merchandise Base + Total Freight, Customs & Handling Overheads.', max_digits=14, verbose_name='Total Landed Cost Valuation / COGS (NPR)'),
        ),
        migrations.AlterField(
            model_name='goodsreceivednote',
            name='vat_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='13% VAT on Pre-VAT Taxable Base when VAT toggle is ON; Rs. 0.00 when OFF.', max_digits=12, verbose_name='Dedicated 13% Input VAT (NPR)'),
        ),
        migrations.AlterField(
            model_name='grnitem',
            name='discount_percent',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Calculated percentage equivalent for audit and analytics.', max_digits=5, verbose_name='Effective Discount (%)'),
        ),
        migrations.AlterField(
            model_name='grnitem',
            name='is_vat_applicable',
            field=models.BooleanField(default=True, help_text='Uncheck if this specific product is zero-rated or tax-exempt under Nepal Tax Schedule.', verbose_name='Is VAT Applicable'),
        ),
        migrations.AlterField(
            model_name='grnitem',
            name='line_total',
            field=models.DecimalField(blank=True, decimal_places=2, default=Decimal('0.00'), help_text='Line Gross - Discount Amount.', max_digits=14, null=True, verbose_name='Pre-VAT Net Total (NPR)'),
        ),
        migrations.AlterField(
            model_name='grnitem',
            name='purchase_rate',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='Unit Purchase Rate (Pre-VAT NPR)'),
        ),
        migrations.AlterField(
            model_name='grnitem',
            name='unit_landed_cost',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Final Pre-VAT unit cost including allocated freight, customs, and bill discounts.', max_digits=12, verbose_name='Unit Landed Cost (NPR)'),
        ),
        migrations.AlterField(
            model_name='grnitem',
            name='vat_rate',
            field=models.DecimalField(decimal_places=2, default=Decimal('13.00'), max_digits=5, verbose_name='Tax / VAT Rate (%)'),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='current_balance',
            field=models.DecimalField(blank=True, db_index=True, decimal_places=2, default=Decimal('0.00'), help_text='Positive balance indicates amount shop owes supplier. Auto-calculated from ledger.', max_digits=14, null=True, verbose_name='Net Outstanding Balance (NPR)'),
        ),
    ]
