# Generated by Django 5.1.15 on 2026-09-30 04:39

import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('branches', '0006_alter_branch_city_alter_branch_district'),
        ('purchases', '0014_goodsreceivednote_bill_discount_amount_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='supplierudhaariledger',
            options={'ordering': ['-entry_date', '-created_at'], 'verbose_name': 'Supplier Udhaari Entry', 'verbose_name_plural': 'Supplier Udhaari Ledgers'},
        ),
        migrations.AddField(
            model_name='supplierudhaariledger',
            name='entry_date',
            field=models.DateField(db_index=True, default=django.utils.timezone.now, help_text='Gregorian date of the invoice, payout, or adjustment.', verbose_name='Transaction Date (AD)'),
        ),
        migrations.AddField(
            model_name='supplierudhaariledger',
            name='entry_date_bs',
            field=models.CharField(blank=True, db_index=True, help_text='Nepali Bikram Sambat date string (YYYY-MM-DD).', max_length=15, null=True, verbose_name='Transaction Date (BS)'),
        ),
        migrations.AlterField(
            model_name='goodsreceivednote',
            name='bill_date',
            field=models.DateField(db_index=True, default=django.utils.timezone.now, help_text='Gregorian date for indexing. Automatically synced with B.S. date.', verbose_name='Bill / Challan Date (AD)'),
        ),
        migrations.AlterField(
            model_name='goodsreceivednote',
            name='bill_date_bs',
            field=models.CharField(blank=True, db_index=True, help_text='Bikram Sambat formatted date string (YYYY-MM-DD). Takes precedence if provided.', max_length=15, null=True, verbose_name='Bill Date (BS)'),
        ),
        migrations.AlterField(
            model_name='goodsreceivednote',
            name='fiscal_year',
            field=models.CharField(blank=True, db_index=True, help_text='Nepali Fiscal Year derived from BS date (e.g. 2080/81, 2081/82, 2082/83, 2083/84).', max_length=10, null=True, verbose_name='Fiscal Year (BS)'),
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='fiscal_year',
            field=models.CharField(blank=True, db_index=True, help_text='Nepali Fiscal Year derived from BS date (e.g. 2080/81, 2081/82, 2082/83, 2083/84).', max_length=10, null=True, verbose_name='Fiscal Year (BS)'),
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='order_date',
            field=models.DateField(db_index=True, default=django.utils.timezone.now, help_text='Gregorian date for database indexing. Automatically synced with B.S. date.', verbose_name='PO Order Date (AD)'),
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='order_date_bs',
            field=models.CharField(blank=True, db_index=True, help_text='Bikram Sambat formatted date string (YYYY-MM-DD). Takes precedence if provided.', max_length=15, null=True, verbose_name='PO Order Date (BS)'),
        ),
        migrations.AlterField(
            model_name='purchasereturn',
            name='fiscal_year',
            field=models.CharField(blank=True, db_index=True, help_text='Nepali Fiscal Year derived from BS date (e.g. 2080/81, 2081/82, 2082/83, 2083/84).', max_length=10, null=True, verbose_name='Fiscal Year (BS)'),
        ),
        migrations.AlterField(
            model_name='purchasereturn',
            name='return_date',
            field=models.DateField(db_index=True, default=django.utils.timezone.now, help_text='Gregorian date for database indexing. Automatically synced with B.S. date.', verbose_name='Return Date (AD)'),
        ),
        migrations.AlterField(
            model_name='purchasereturn',
            name='return_date_bs',
            field=models.CharField(blank=True, db_index=True, help_text='Bikram Sambat formatted date string (YYYY-MM-DD). Takes precedence if provided.', max_length=15, null=True, verbose_name='Return Date (BS)'),
        ),
        migrations.AddIndex(
            model_name='supplierudhaariledger',
            index=models.Index(fields=['supplier', '-entry_date'], name='idx_sup_ledg_sup_edate'),
        ),
        migrations.AddIndex(
            model_name='supplierudhaariledger',
            index=models.Index(fields=['branch', '-entry_date'], name='idx_sup_ledg_br_edate'),
        ),
        migrations.AddIndex(
            model_name='supplierudhaariledger',
            index=models.Index(fields=['entry_date_bs'], name='idx_sup_ledg_bs_date'),
        ),
    ]
