# Generated by Django 5.1.15 on 2026-10-01 16:38

import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('branches', '0006_alter_branch_city_alter_branch_district'),
        ('inventory', '0016_alter_brand_name_alter_iteminstance_customer_phone_and_more'),
        ('purchases', '0015_alter_supplierudhaariledger_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='goodsreceivednote',
            name='challan_date',
            field=models.DateField(blank=True, db_index=True, null=True, verbose_name='Challan Date (AD)'),
        ),
        migrations.AddField(
            model_name='goodsreceivednote',
            name='challan_date_bs',
            field=models.CharField(blank=True, db_index=True, max_length=15, null=True, verbose_name='Challan Date (BS)'),
        ),
        migrations.AddField(
            model_name='goodsreceivednote',
            name='challan_no',
            field=models.CharField(blank=True, db_index=True, max_length=100, null=True, verbose_name='Challan / Delivery Ref No.'),
        ),
        migrations.AddField(
            model_name='goodsreceivednote',
            name='consignment_narration',
            field=models.TextField(blank=True, help_text='Transaction note for general ledger.', null=True, verbose_name='General Consignment Narration'),
        ),
        migrations.AddField(
            model_name='goodsreceivednote',
            name='insurance_charge',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='Transit Insurance (NPR)'),
        ),
        migrations.AddField(
            model_name='goodsreceivednote',
            name='internal_notes',
            field=models.TextField(blank=True, help_text='Approvals, QC test references, gate passes, etc.', null=True, verbose_name='Internal Notes & Audit Reference'),
        ),
        migrations.AddField(
            model_name='goodsreceivednote',
            name='other_overheads_charge',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='Other Direct Overheads (NPR)'),
        ),
        migrations.AddField(
            model_name='goodsreceivednote',
            name='receiving_notes',
            field=models.TextField(blank=True, help_text='Seal conditions, carton numbers, driver remarks, etc.', null=True, verbose_name='Receiving / Physical Inspection Notes'),
        ),
        migrations.AddField(
            model_name='goodsreceivednote',
            name='vat_handling_mode',
            field=models.CharField(choices=[('EXCLUSIVE', 'VAT Excluded (Added on Top of Rate)'), ('INCLUSIVE', 'VAT Included (Extracted from Rate)')], db_index=True, default='EXCLUSIVE', help_text='Exclusive: VAT calculated on top. Inclusive: VAT broken out from entered rate.', max_length=15, verbose_name='VAT Handling Mode'),
        ),
        migrations.AddField(
            model_name='grnitem',
            name='batch_number',
            field=models.CharField(blank=True, db_index=True, help_text='Physical manufacturer / supplier batch code (e.g. BT-2026-A1)', max_length=100, null=True, verbose_name='Batch Number'),
        ),
        migrations.AlterField(
            model_name='goodsreceivednote',
            name='bill_date',
            field=models.DateField(db_index=True, default=django.utils.timezone.now, help_text='Gregorian date for indexing. Automatically synced with B.S. date.', verbose_name='Bill / Invoice Date (AD)'),
        ),
        migrations.AlterField(
            model_name='goodsreceivednote',
            name='other_handling_charge',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='Handling & Unloading Cost (NPR)'),
        ),
        migrations.AlterField(
            model_name='goodsreceivednote',
            name='remarks',
            field=models.TextField(blank=True, help_text='Maintained for backward compatibility.', null=True, verbose_name='Consolidated Remarks (Legacy)'),
        ),
        migrations.AlterField(
            model_name='goodsreceivednote',
            name='supplier_bill_no',
            field=models.CharField(db_index=True, max_length=100, verbose_name='Supplier Invoice / Bill Ref No.'),
        ),
        migrations.AlterField(
            model_name='goodsreceivednote',
            name='total_landed_cost',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Pre-VAT Taxable Merchandise Base + Total Freight, Customs, Handling, Insurance & Other Overheads.', max_digits=14, verbose_name='Total Landed Cost Valuation / COGS (NPR)'),
        ),
        migrations.AlterField(
            model_name='grnitem',
            name='purchase_rate',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='Unit Purchase Rate (NPR)'),
        ),
        migrations.AlterField(
            model_name='grnitem',
            name='unit_landed_cost',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Final Pre-VAT unit cost including allocated freight, customs, insurance, handling, and bill discounts.', max_digits=12, verbose_name='Unit Landed Cost (NPR)'),
        ),
        migrations.AddIndex(
            model_name='goodsreceivednote',
            index=models.Index(fields=['challan_no'], name='idx_grn_challan_no'),
        ),
        migrations.AddIndex(
            model_name='grnitem',
            index=models.Index(fields=['batch_number'], name='idx_grn_item_batch_no'),
        ),
    ]
