# Generated by Django 5.1.15 on 2026-10-04 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchases', '0016_goodsreceivednote_challan_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supplier',
            name='supplier_type',
            field=models.CharField(choices=[('NATIONAL_DISTRIBUTOR', 'National Importer / Distributor'), ('REGIONAL_WHOLESALER', 'Regional Wholesaler'), ('MANUFACTURER', 'Manufacturer'), ('LOCAL_TRADER', 'Local Dealer / Trader'), ('SERVICE_PARTS_VENDOR', 'Parts & Service Supplier')], default='NATIONAL_DISTRIBUTOR', max_length=30, verbose_name='Supplier Classification'),
        ),
    ]
