# Generated by Django 5.1.15 on 2026-10-05 05:47

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchases', '0017_alter_supplier_supplier_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goodsreceivednote',
            name='net_total_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Net invoice payable to supplier = Pre-VAT Merchandise Base + 13% VAT Amount.', max_digits=14, verbose_name='Supplier Invoice Total (NPR)'),
        ),
        migrations.AlterField(
            model_name='goodsreceivednote',
            name='vat_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Sum of item-level VAT on Pre-VAT Taxable Base when VAT toggle is ON; Rs. 0.00 when OFF.', max_digits=12, verbose_name='Dedicated 13% Input VAT (NPR)'),
        ),
    ]
