# Generated by Django 5.1.15 on 2026-10-06 05:35

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchases', '0018_alter_goodsreceivednote_net_total_amount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goodsreceivednote',
            name='is_vat_bill',
            field=models.BooleanField(default=False, help_text='Automatically checked if any items carry 13% VAT; false for 0% PAN bills.', verbose_name='13% VAT Inward Tax Bill'),
        ),
        migrations.AlterField(
            model_name='goodsreceivednote',
            name='total_landed_cost',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Net Pre-VAT Merchandise Base + 5 Overheads (Freight, Customs, Handling, Insurance, Other).', max_digits=14, verbose_name='Total Landed Cost Valuation / COGS (NPR)'),
        ),
        migrations.AlterField(
            model_name='goodsreceivednote',
            name='vat_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Sum of item-level 13% VAT on Taxable Base. Strictly 0.00 for non-VAT items.', max_digits=12, verbose_name='Dedicated 13% Input VAT (NPR)'),
        ),
        migrations.AlterField(
            model_name='grnitem',
            name='is_vat_applicable',
            field=models.BooleanField(default=True, help_text='Automatically set to True for 13% lines; False for 0% exempt lines.', verbose_name='Is VAT Applicable'),
        ),
        migrations.AlterField(
            model_name='grnitem',
            name='vat_rate',
            field=models.DecimalField(choices=[(Decimal('13.00'), '13% (Standard VAT)'), (Decimal('0.00'), '0% (Exempt / PAN)')], decimal_places=2, default=Decimal('13.00'), help_text='Locked to 13.00% (Taxable) or 0.00% (Exempt).', max_digits=5, verbose_name='Tax / VAT Rate (%)'),
        ),
    ]
