# Generated by Django 5.1.15 on 2026-10-07 13:54

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchases', '0019_alter_goodsreceivednote_is_vat_bill_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='grnitem',
            name='tax_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Exact VAT amount calculated for this line item.', max_digits=12, verbose_name='Tax / VAT Amount (NPR)'),
        ),
        migrations.AlterField(
            model_name='goodsreceivednote',
            name='is_vat_bill',
            field=models.BooleanField(default=False, help_text='Automatically set to True if any line carries 13% VAT; False for 0% PAN bills.', verbose_name='13% VAT Inward Tax Bill'),
        ),
        migrations.AlterField(
            model_name='goodsreceivednote',
            name='taxable_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Net pre-VAT merchandise value of 13% taxable lines after allocated discounts.', max_digits=14, verbose_name='Pre-VAT Taxable Base (NPR)'),
        ),
        migrations.AlterField(
            model_name='goodsreceivednote',
            name='vat_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text="Sum of item-level 13% VAT amounts. Always equals the sum of line items' tax_amount.", max_digits=12, verbose_name='Dedicated 13% Input VAT (NPR)'),
        ),
    ]
