# Generated by Django 5.1.15 on 2026-08-20 15:30

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('code', models.CharField(db_index=True, max_length=20, unique=True, verbose_name='Branch Code')),
                ('name', models.CharField(max_length=150, verbose_name='Branch / Outlet Name')),
                ('name_np', models.CharField(blank=True, max_length=150, null=True, verbose_name='Branch Name (Nepali)')),
                ('is_main_branch', models.BooleanField(default=False, verbose_name='Is Main/Central Branch')),
                ('address', models.CharField(max_length=255, verbose_name='Location Address (e.g. New Road)')),
                ('city', models.CharField(default='Kathmandu', max_length=100)),
                ('district', models.CharField(default='Kathmandu', max_length=100)),
                ('province', models.CharField(choices=[('Koshi', 'Koshi Province'), ('Madhesh', 'Madhesh Province'), ('Bagmati', 'Bagmati Province'), ('Gandaki', 'Gandaki Province'), ('Lumbini', 'Lumbini Province'), ('Karnali', 'Karnali Province'), ('Sudurpashchim', 'Sudurpashchim Province')], default='Bagmati', max_length=50)),
                ('phone_number', models.CharField(max_length=25, verbose_name='Branch Phone / Mobile')),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('invoice_prefix', models.CharField(default='EST', help_text='Prefix attached to sequential estimate slips (e.g. EST-NR-0001)', max_length=10)),
                ('header_contact_info', models.TextField(blank=True, help_text='Lines printed below header on thermal slips (e.g., Phone, Ward No, Landline)')),
                ('footer_estimate_note', models.CharField(default='* Estimation slip only. Exchange possible within 7 days with this estimate slip. *', max_length=255, verbose_name='Slip Footer Note')),
            ],
            options={
                'verbose_name': 'Branch / Outlet',
                'verbose_name_plural': 'Branches & Outlets',
                'db_table': 'branch_locations',
                'ordering': ['-is_main_branch', 'name'],
            },
        ),
        migrations.CreateModel(
            name='StockTransferRequest',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('transfer_no', models.CharField(db_index=True, max_length=30, unique=True)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft / Pending Approval'), ('DISPATCHED', 'Dispatched / In-Transit'), ('RECEIVED', 'Received & Stock Updated'), ('REJECTED', 'Rejected / Cancelled')], db_index=True, default='DRAFT', max_length=20)),
                ('transfer_date', models.DateField(auto_now_add=True)),
                ('notes', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Stock Transfer',
                'verbose_name_plural': 'Stock Transfers',
                'db_table': 'branch_stock_transfers',
                'ordering': ['-created_at'],
            },
        ),
    ]
