# Generated by Django 5.1.15 on 2026-08-20 15:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('branches', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='branch',
            name='manager',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_branches', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='stocktransferrequest',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transfers_approved', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='stocktransferrequest',
            name='destination_branch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transfers_received', to='branches.branch'),
        ),
        migrations.AddField(
            model_name='stocktransferrequest',
            name='received_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transfers_received_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='stocktransferrequest',
            name='requested_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transfers_requested', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='stocktransferrequest',
            name='source_branch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transfers_sent', to='branches.branch'),
        ),
    ]
