# Generated by Django 5.1.15 on 2026-08-26 07:22

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('branches', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='branch',
            name='invoice_prefix',
            field=models.CharField(default='EST', help_text='Prefix attached to sequential estimate slips (e.g. EST-NR-000001)', max_length=10),
        ),
        migrations.CreateModel(
            name='BranchDocumentSequence',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('document_type', models.CharField(choices=[('SALES_ESTIMATE', 'Sales Estimate Slip (EST)'), ('REPAIR_TICKET', 'Repair / Service Ticket (SRV)'), ('STOCK_TRANSFER', 'Stock Transfer Requisition (TRF)'), ('GOODS_RECEIPT', 'Goods Received Note (GRN)'), ('TRADE_IN_VOUCHER', 'Trade-In / Buy-Back Voucher (EXC)'), ('SALES_RETURN', 'Sales Return Voucher (RET)'), ('VENDOR_RMA', 'Vendor RMA Claim (RMA)')], db_index=True, max_length=30, verbose_name='Document Type')),
                ('prefix', models.CharField(blank=True, help_text='Prefix override (e.g. EST-NR, SRV-KTM). If blank, uses system defaults.', max_length=20, null=True, verbose_name='Document Prefix')),
                ('last_number', models.PositiveBigIntegerField(default=0, verbose_name='Last Allocated Sequence Number')),
                ('padding_digits', models.PositiveIntegerField(default=6, verbose_name='Zero Padding Digits (e.g. 6 -> 000001)')),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='document_sequences', to='branches.branch', verbose_name='Branch / Outlet')),
            ],
            options={
                'verbose_name': 'Branch Document Sequence Counter',
                'verbose_name_plural': 'Branch Document Sequence Counters',
                'db_table': 'branch_document_sequences',
                'ordering': ['branch', 'document_type'],
                'unique_together': {('branch', 'document_type')},
            },
        ),
    ]
