# Generated by Django 5.1.15 on 2026-08-30 04:32

import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('branches', '0003_alter_branch_invoice_prefix_branchdocumentsequence'),
        ('inventory', '0013_remove_iteminstance_unique_imei_2_when_present_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='stocktransferrequest',
            options={'ordering': ['-created_at'], 'verbose_name': 'Stock Transfer Request', 'verbose_name_plural': 'Stock Transfer Requests'},
        ),
        migrations.RemoveField(
            model_name='stocktransferrequest',
            name='approved_by',
        ),
        migrations.AddField(
            model_name='stocktransferrequest',
            name='dispatched_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transfers_dispatched', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='stocktransferrequest',
            name='dispatched_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='stocktransferrequest',
            name='received_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='stocktransferrequest',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Draft / Pending Approval'), ('DISPATCHED', 'Dispatched / In-Transit'), ('RECEIVED', 'Received & Stock Updated'), ('CANCELLED', 'Cancelled / Rejected')], db_index=True, default='DRAFT', max_length=20),
        ),
        migrations.CreateModel(
            name='StockTransferItem',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('quantity', models.DecimalField(decimal_places=3, default=Decimal('1.000'), max_digits=10, verbose_name='Transferred Quantity')),
                ('scanned_imei_or_serial', models.TextField(blank=True, help_text='Comma or newline separated 15-digit IMEIs for smartphone models', null=True, verbose_name='Scanned IMEIs / Serials')),
                ('notes', models.CharField(blank=True, max_length=255, null=True, verbose_name='Line Remarks')),
                ('item_instance', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transfer_records', to='inventory.iteminstance', verbose_name='Linked Serialized Unit')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transfer_items', to='inventory.product', verbose_name='Product / Handset Model')),
                ('transfer_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='branches.stocktransferrequest', verbose_name='Transfer Requisition')),
            ],
            options={
                'verbose_name': 'Stock Transfer Line Item',
                'verbose_name_plural': 'Stock Transfer Line Items',
                'db_table': 'branch_stock_transfer_items',
            },
        ),
    ]
