# Generated by Django 5.1.15 on 2026-08-31 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('branches', '0004_alter_stocktransferrequest_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='branch',
            name='company_name',
            field=models.CharField(blank=True, help_text='Official business name displayed on headers, receipts, and POS screens. If blank, inherits from Central Head Office or System Configuration.', max_length=200, null=True, verbose_name='Company / Shop Business Name (English)'),
        ),
        migrations.AddField(
            model_name='branch',
            name='company_name_np',
            field=models.CharField(blank=True, help_text='Devanagari company name for localized customer slips (e.g. स्मार्ट मोबाइल तथा अप्टिकल हब).', max_length=200, null=True, verbose_name='Company / Shop Business Name (Nepali)'),
        ),
        migrations.AddField(
            model_name='branch',
            name='logo',
            field=models.ImageField(blank=True, help_text='Optional: Upload company logo (PNG, JPG, WebP, SVG). If not uploaded, the system cleanly displays company text.', null=True, upload_to='branches/logos/%Y/%m/', verbose_name='Company / Outlet Logo'),
        ),
        migrations.AlterField(
            model_name='branch',
            name='address',
            field=models.CharField(max_length=255, verbose_name='Location Address (e.g. Ward No. 22, New Road)'),
        ),
        migrations.AlterField(
            model_name='branch',
            name='is_main_branch',
            field=models.BooleanField(default=False, verbose_name='Is Main / Central Head Office'),
        ),
        migrations.AlterField(
            model_name='branch',
            name='name',
            field=models.CharField(max_length=150, verbose_name='Branch / Outlet Name (e.g. New Road Branch)'),
        ),
    ]
