# Generated by Django 5.1.15 on 2026-08-31 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('branches', '0005_branch_company_name_branch_company_name_np_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='branch',
            name='city',
            field=models.CharField(blank=True, default='Kathmandu', max_length=100),
        ),
        migrations.AlterField(
            model_name='branch',
            name='district',
            field=models.CharField(blank=True, default='Kathmandu', max_length=100),
        ),
    ]
