# Generated by Django 5.1.15 on 2026-08-20 15:30

import django.db.models.deletion
import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('branches', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='POSHoldCart',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('hold_reference', models.CharField(db_index=True, max_length=50, unique=True)),
                ('customer_name', models.CharField(blank=True, max_length=150, null=True)),
                ('customer_phone', models.CharField(blank=True, max_length=25, null=True)),
                ('cart_payload', models.JSONField(default=dict, help_text='JSON snapshot of cart line items, package units, and prices')),
                ('subtotal', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('discount_percent', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5)),
                ('notes', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'verbose_name': 'Held POS Cart',
                'verbose_name_plural': 'Held POS Carts',
                'db_table': 'pos_held_carts',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CashDrawerSession',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('session_number', models.CharField(db_index=True, max_length=50, unique=True)),
                ('opening_time', models.DateTimeField(auto_now_add=True)),
                ('closing_time', models.DateTimeField(blank=True, null=True)),
                ('opening_cash', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='Opening Float Cash (सुरुवाती नगद)')),
                ('expected_closing_cash', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14, verbose_name='Calculated Cash in Drawer')),
                ('actual_closing_cash', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14, verbose_name='Counted Cash at Shift End (गनेको नगद)')),
                ('cash_discrepancy', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Discrepancy (Actual - Expected). Negative indicates cash shortage.', max_digits=10)),
                ('total_sales_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('total_cash_sales', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('total_digital_sales', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('total_credit_sales', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('total_returns_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('status', models.CharField(choices=[('OPEN', 'Open / Active Shift (सक्रिय)'), ('CLOSED', 'Closed & Reconciled (बन्द गरिएको)')], db_index=True, default='OPEN', max_length=20)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='drawer_sessions', to='branches.branch')),
            ],
            options={
                'verbose_name': 'Cash Drawer Session',
                'verbose_name_plural': 'Cash Drawer Sessions',
                'db_table': 'pos_cash_drawer_sessions',
                'ordering': ['-created_at'],
            },
        ),
    ]
