# Generated by Django 5.1.15 on 2026-09-04 08:33

from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('branches', '0006_alter_branch_city_alter_branch_district'),
        ('customers', '0002_initial'),
        ('pos', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='posholdcart',
            name='bill_discount_type',
            field=models.CharField(choices=[('PERCENTAGE', 'Percentage (%)'), ('FIXED', 'Fixed Amount (Rs.)'), ('NONE', 'No Discount')], db_index=True, default='PERCENTAGE', help_text='Specifies whether bill discount is evaluated as percentage or flat NPR cash amount', max_length=15, verbose_name='Bill Discount Type'),
        ),
        migrations.AddField(
            model_name='posholdcart',
            name='bill_discount_value',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Raw input value entered by cashier (% or Rs.)', max_digits=12, verbose_name='Bill Discount Value'),
        ),
        migrations.AlterField(
            model_name='posholdcart',
            name='cart_payload',
            field=models.JSONField(default=dict, help_text='Complete JSON snapshot of cart line items, pricing, package units, dual-IMEIs, and discount parameters'),
        ),
        migrations.AlterField(
            model_name='posholdcart',
            name='discount_percent',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Effective discount percentage for responsive and legacy display', max_digits=5, verbose_name='Effective Discount (%)'),
        ),
        migrations.AddIndex(
            model_name='posholdcart',
            index=models.Index(fields=['branch', 'created_at'], name='idx_hold_branch_created'),
        ),
        migrations.AddIndex(
            model_name='posholdcart',
            index=models.Index(fields=['hold_reference'], name='idx_hold_ref'),
        ),
    ]
