# Generated by Django 5.1.15 on 2026-09-04 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0003_posholdcart_bill_discount_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posholdcart',
            name='bill_discount_type',
            field=models.CharField(choices=[('AMOUNT', 'Fixed Amount (Rs.)'), ('PERCENTAGE', 'Percentage (%)'), ('FIXED', 'Fixed Amount [Legacy Alias] (Rs.)'), ('NONE', 'No Discount')], db_index=True, default='PERCENTAGE', help_text='Specifies whether bill discount is evaluated as percentage, fixed amount, or none.', max_length=15, verbose_name='Bill Discount Type'),
        ),
        migrations.AlterField(
            model_name='posholdcart',
            name='cart_payload',
            field=models.JSONField(default=dict, help_text='Complete JSON snapshot of cart line items, pricing, package units, dual-IMEIs, and discount parameters (type, raw value, and effective percent).'),
        ),
    ]
