# Generated by Django 5.1.15 on 2026-09-27 05:06

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('branches', '0006_alter_branch_city_alter_branch_district'),
        ('customers', '0004_alter_customer_options_and_more'),
        ('pos', '0004_alter_posholdcart_bill_discount_type_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='posholdcart',
            name='customer_pan',
            field=models.CharField(blank=True, db_index=True, max_length=25, null=True, verbose_name='Customer PAN'),
        ),
        migrations.AddField(
            model_name='posholdcart',
            name='repair_ticket_id',
            field=models.PositiveIntegerField(blank=True, help_text='Linked Workshop Repair Ticket ID held with cart.', null=True, verbose_name='Repair Ticket ID'),
        ),
        migrations.AddField(
            model_name='posholdcart',
            name='trade_in_voucher_id',
            field=models.PositiveIntegerField(blank=True, help_text='Linked Buy-Back Trade-In voucher ID held with cart.', null=True, verbose_name='Trade-In Voucher ID'),
        ),
        migrations.AlterField(
            model_name='posholdcart',
            name='cart_payload',
            field=models.JSONField(default=dict, help_text='Complete JSON snapshot of cart line items, pricing, package units, dual-IMEIs, repair handover, trade-in, and discount parameters.'),
        ),
        migrations.AddIndex(
            model_name='posholdcart',
            index=models.Index(fields=['customer_pan'], name='idx_hold_cust_pan'),
        ),
    ]
